- gravity-forms/gw-custom-activation-template.php
This PR adds the [custom activation template](https://gravitywiz.com/customizing-gravity-forms-user-registration-activation-page/) snippet to the repo and fixes an issue with newer versions of GFUR where the `page` parameter has been changed to `gfur_activation`.
Ticket: [#19745](https://secure.helpscout.net/conversation/1275451153/19745?folderId=3808239)
> Fixed a compatibility issue with WP 5.5 and newer versions of GFUR.

- gp-populate-anything/gppa-disable-all-fields-with-submit-button.js
This is a new snippet to disable all fields on a form when GPPA is querying the back-end and the submit button is disabled.
It uses `gppa_disable_form_navigation_toggling` to detect when GPPA is about to disable the submit button and immediately disables any form element that is not currently disabled (while also tagging such elements with a `data-gppa-disabled` attribute).
Once GPPA is done and it is about to re-enable the submit button, the same filter is checked and this snippet reverses its actions.
> Added a new snippet to disable all form inputs with the submit button.

- gravity-forms/gw-cache-buster.php
@spivurno Just heads up, this was already reviewed but I think it got lost in the snippet-library creation fog. I'm merging it right away and sending to Scott for an issue.
> Updated `gw-gravity-forms-cache-buster.php` to 0.3 which passes URL params.

- gravity-forms/gw-gravity-forms-rounding.php
This PR renames the filters from `gw_rounding_xxx` to `gw_round_xxx` to match the rest of the filters and class names.
It also addresses an issue where a custom filter without an actionValue set in the class name would default to the `round` method (e.g. `gw-round-nearest9` would be broken while `gw-round-nearest-9` would work).
> Fixed filter name to match the standard rounding class names.

- gravity-forms/gw-unique-id-exclude-characters.php
This PR adds the GPUID Exclude Chars snippet to the library. It also [fixes an issue](https://github.com/gravitywiz/snippet-library/commit/d3b7cdc8bdd87b04b9944c8896c101bf3f856cb7) with generated GPUIDs.
`array_diff()` doesn't reset array keys, which caused the random replace loop to fail sometimes and end up replacing an excluded character with a `null` causing the UID to be shorter than the specified length.
The fix uses `array_values()` to copy the generated array, ensuring that keys will be sequential.
> Add GPUID Exclude Chars Snippet

- gravity-forms/gw-create-coupon.php
**Initial Comment from first PR**
This is a PR adding support to set a start date for Woocommerce Coupons. WooCommerce Coupons don't have a field or attribute to set the start date, so the start date value passed is assigned to the post_date variable. This means that, if the date is in the future it will schedule the coupon post but if it's in the past or it's the current date it will publish the coupon.
The start_date parameter is expected to be an element within the meta array and in this format; '2020-12-11'. If no start_date value is passed, the current date is used.
Update
@spivurno I've made changes per your feedback in the first PR. Thanks
> Added Support to Set WooCommerce Coupon Start Date

- gravity-forms/gw-form-list-active-by-default.php
This PR converts the Form List Active by Default snippet to a plugin since it doesn't require any configuration.
> Converts gw-form-list-active-by-default.php to a plugin

- gravity-forms/gw-require-list-columns.php
This PR imports the [Require All Columns of List Field](https://gravitywiz.com/require-all-columns-of-list-field/) snippet.
It also fixes an issue where validation would fail if the value passed is `0`. [`empty()`](https://www.php.net/manual/en/function.empty.php) returns true for `'0'` and `0` which is not the desired effect here.
HS: 21317
> Require List Columns

- gravity-forms/gw-update-posts.php
This PR adds a new snippet that will update WP post titles and content with values from GF entry. Usage example:
```
'title'   => 2,
'content' => 3
) );
```
> Added new snippet: gw-update-posts.php

- gravity-forms/gw-populate-date.php
This PR fixes an issue where this snippet would fail to populate the `$format` variable if the target field is not a date field and a format was not specified in the snippet's configuration.
The `get_format()` method already had a fallback but a call to it was skipped if a format was not passed as one of the arguments during setup.
#21705.
> Fixed an issue where populating to a non-date field without specifying a format would fail.

- gp-nested-forms/gpnf-clear-session-after-save-and-continue.php
This PR replaces the content of the GPNF clear session snippet as its functionality has been migrated to GPNF's core.
Future PRs may remove the snippet's file if needed.
> Replaced GPNF save and continue snippet with a comment indicating its migration.

- gp-nested-forms/gpnf-map-child-entries-to-acf-repeater-field.php
Assigned the ACF Repeater field name to a variable to make it easy for users to configure the snippet. We missed this when we were tweaking the code.
> Assigned the ACF Repeater field name to a Variable.

- gravity-forms/gw-update-posts.php
This PR adds support for mapping custom fields in post updates. Usage:
```
'title'   => 2,
'content' => 3,
'meta'    => array(
'custom_field'	  => 4,
'another_custom_field' => 5
)
) );
```
> Added support for mapping custom fields.

- gravity-forms/gw-gravity-forms-populate-form.php
This PR imports the GW GFPF snippet to the library.
It also adds a new option to allow users to override the snippets population and instead rely on GF's dynamic population feature.
For example, if a user of this snippet uses the URL parameter to import an entry (`eid=xxx`), they can now also use other parameters (`eid=xxx&arg1=yyy&arg2=zzz`) to fill configured fields in the form atop the entry's data.
#22783
> Add GW Gravity Forms Populate Form Snippet

- gp-ecommerce-fields/gpecf-customize-order-summary-markup-with-modifier.php
- gp-ecommerce-fields/gpecf-customize-order-summary-markup.php
- gp-ecommerce-fields/gpecf-itemized-product-options-order-summary-markup.php
This PR adds itemized product options order summary markup.
This also moves custom order summary markup gists used in [gpecf_order_sumary_markup docs](https://gravitywiz.com/documentation/gpecf_order_sumary_markup/) into snippet library.
> Add gpecf-itemized-product-options-order-summary-markup.php

- gravity-forms/gw-submit-to-access.php
This PR fixes a compatibility issue with the Events Calendar and GWSA.
If a user uses [this specific hook](https://theeventscalendar.com/support/forums/topic/events-custom-fields-missing-since-4-8-1-update/) to enable WP Custom Fields and then sets a `gwsa_requires_submission_redirect` custom field on any event, the `wp_redirect()` does not execute on the master events list page (`{domain}/events/`) as expect, but the `exit()` call directly afterwards causes the page to stop loading.
This ends up breaking the listing page if any single event is set to require submission before access (and also has a URL redirect).
#22826
> Fixed a potential issue where GWSA may cause the Events Calendar to show a blank page.

- gravity-forms/gw-gravity-forms-custom-js.php
This PR fixes an issue with GF 2.5 and the Custom JS snippet.
GF 2.5 seems to fire the `gform_form_settings` hook before `save_custom_js_setting`, causing this snippet to display an outdated version of the JS code and requiring a page refresh before showing the latest version.
The commit here tweaks `add_custom_js_setting()` to favor the posted value if it's available and differs from the saved version.
#23065
> Fixed a compatibility issue with GF 2.5.

- gravity-forms/gw-inventory.php
This PR removes a rouge `</div>` that causes display issues if the snippet is used on a page that contains multiple forms.
#23109
> Fixed a potential HTML markup issue.

- gravity-forms/gw-gravity-forms-rename-uploaded-files.php
This PR imports the [Rename  Uploaded Files](https://gravitywiz.com/rename-uploaded-files-for-gravity-form/) snippet to the library.
It also adds a new option `ignore_extension` to allow renamed files to maintain the sequence regardless of the uploaded extension.
For example, if files are to be renamed `Hello`, and four files 2x`jpg` and 2x`png` are uploaded, the standard behavior would result in:
`Hello.jpg`
`Hello1.jpg`
`Hello.png`
`Hello1.png`
With the `ignore_extension` option set to `true` the new behavior would be:
`Hello.jpg`
`Hello1.jpg`
`Hello2.png`
`Hello3.png`
#22992
> Added Rename Uploaded Files

- gravity-forms/gw-cache-buster.php
This PR fixes an issue with the way Cache Buster passes a form's attribute to the Gravity Form constructor.
The implementation of `rgar()` accepts objects only if they are (or implement) [`ArrayAccess`](https://www.php.net/manual/en/class.arrayaccess.php). This caused `rgar` to fail and in turn passed `null` into GF.
The solution here was to modify the `json_decode` call to return an associative array instead of an object.
#23101
> Fixed an issue where Cache Buster would not display a form's title.

- gravity-forms/gw-cache-buster.php
This PR fixes the parsing of the `title` and `description` attributes in shortcodes.
Passing `false` as a string to Gravity Forms' `GFFormDisplay::get_form()` ends up being evaluated as `true` since there's no type checking involved.
The commit in this PR explicitly uses `filter_var` with `FILTER_VALIDATE_BOOLEAN` to correct for that. It also adds `true` as the default setting to match GF's signature.
#23249
> Fixed parsing of `title` and `description` boolean values in shortcodes.

- gravity-forms/gw-form-list-active-by-default.php
This PR fixes a potential crash if GF is not installed or has been deactivated.
#23384
> Fixed a potential crash in GW Form List Active by Default if GF is not active.

- gp-easy-passthrough/gpep-edit-entry.php
This PR adds support for partial entries. It also uses the `class` approach for encapsulation and easier configuration.
Currently when partial entries are enabled and used alongside GPEP and this snippet, a temporary empty entry is left behind each time a form is submitted.
With the new option added, we simply delete the stale partial entry if the user chose to enable it.
#23339, #23599
> Added partial entries support to GPEP Edit Entry snippet.

- gravity-forms/gw-inventory.php
This PR adds the usage example back to gw-inventory.php. It was previously removed, but after further discussion we decided to add usage examples back to the snippets.
> Added usage example back to gw-inventory.php

- gp-easy-passthrough/gpep-edit-entry.php
This PR renames the wrapping class name for GPEP Edit Entry snippet to match our naming convention.
> Renamed class from `GPEPEditEntry` to `GPEP_Edit_Entry`.

- gravity-forms/gw-gravity-forms-populate-form.php
This PR fixes an issue with the Populate Form with Entry snippet.
If a field is marked as having `No Duplicates` in its settings, the snippet will not work as `gform_entry_id_pre_save_lead` is fired after validation has been completed.
To fix that, this PR adds a new `validate_field` method to filter `gform_field_validation`. It checks if a field that has failed validation did so due to a duplicate entry error while also ensuring that the snippet is being used to update the entry. If all these conditions are met, it overrides the validation error.
#23712
> Fixed an issue with field set with `No Duplicates` causing update to fail.

- gravity-forms/gw-cache-buster.php
This PR fixes an initialization issue when GPPA is used with GW Cache Buster.
It piggy-backs on `gpnf_init_nested_form` if GPPA is detected in the returned markup, and then fires `gform_post_render` to ensure that GPPA has been fully initialized.
#23661
> Fixed a compatibility issue with GPPA.

- gravity-forms/gw-choice-counter.php
This PR fixes an issue between GPPA and the choice counter snippet.
On field hydration GPPA overwrites fields in the DOM which can cause any event listeners that are attached to get lost.
The commit here delegates the event listeners to the parent form instead of the field itself. It also adds a new listener for `gppa_updated_batch_fields` to ensure the count remains accurate in case the counted field is overwritten.
#23913
> GPPA Choice Counter Issue

- gp-nested-forms/gp-nested-forms-delay-child-notifications-for-parent-payment.php
This PR imports the GPNF Delay Child Notifications for Parent Payment snippet.
It also fixes an issue where notifications were sent twice by filtering on `gform_entry_post_save` and specific parent form IDs.
#23899 / DWC.
> Added GPNF Delay Child Notifications to the library

- gravity-forms/gw-cache-buster.php
This PR fixes an issue where `field_values` were not being passed properly in the short code.
An example cause would look like: `[gravityform id="233" title="false" cachebuster="1" description="false" field_values="webinar_code=123-456-789"]`.
GF expects the `$field_values` parameter to be an associative array. The commit here fixes that by using `parse_str()`.
#24038
> Fixed an issue where field values were not passed properly to GF.

- gravity-forms/gw-update-posts.php
This PR adds support for updating multiple taxonomies with a single form entry. For example, you could update the post's categories and custom taxonomies at the same time.
> Add support for updating multiple taxonomies in a single entry.

- gravity-forms/gw-set-list-field-rows-by-field-value.php
This PR updates the selector for the quantity field from `#ginput_quantity_240_5` to `#input_240_5_1` as the markup has changed in GF 2.5.
There's also a note in the documentation for GF 2.4 and earlier noting this change. But by default the example follows GF 2.5 now.
#24906
> Updated snippet documentation to reflect GF 2.5 changes.

- gravity-forms/gw-set-list-field-rows-by-field-value.php
Snippet: gw-set-list-field-rows-by-field-value.php
This PR fixes a markup issue with GF 2.5. By default, the new markup doesn't use tables for List fields.
This caused the snippet to add an unlimited number of fields with every interaction as it was not able to get the current number accurately.
With a version check, the updated snippet will now look for `.gfield_list_group` in GF 2.5 with a fallback to the table method for 2.4 and below.
[#24871](https://secure.helpscout.net/conversation/1527600936/24871/)
> Fixed an issue with GF2.5 where rows were not counted correctly.

- gravity-forms/gw-gravity-forms-rounding.php
This PR removes a rogue `debugger` statement left in `gw-gravity-forms-rounding.php`.
[#24946](https://secure.helpscout.net/conversation/1531948301/24946?folderId=3808239)
> Removed JS `debugger` from gw-gravity-forms-rounding.php.

- gravity-forms/gw-all-fields-template.php
The `nopricingfields` modifier doesn't seem to apply to the "Order Summary" label.
This PR uses a second filter `gform_display_product_summary` to ensure it's hidden.
Ticket: [#25152](https://secure.helpscout.net/conversation/1539696626/25152/)
> Fixed an issue where "Order Summary" label would still appear when using `nopricingfields` modifier.

- gravity-forms/gw-all-fields-template.php
This PR amends #106 to ensure that "Order Summary" label is not displayed when using the `nopricingfields` modifier.
#106 failed as it removed the `gform_display_product_summary` filter prematurely which caused the label to show if other modifiers (e.g. `exclude`) are used along with `nopricingfields`.
The commit here uses a closure instead to ensure that the filter is only removed after it's been fired once.
Ticket: [#25152](https://secure.helpscout.net/conversation/1539696626/25152?folderId=3808239)
> Fixed an issue where `nopricingfields` may still show order summary when other modifiers are used.

- gp-unique-id/gpuid-retroactively-populate-unique-ids.php
This PR adds the [`gpuid-retroactively-populate-unique-ids.php`](https://gist.github.com/spivurno/535b74a34c0830adf1b770fed0de7812) to the snippet library.
It also fixes an issue where the snippet may cause a PHP fatal error when used with the Code Snippets plugin by utilizing WordPress's `init` hook to ensure that GPUID is loaded.
Ticket: [#25217](https://secure.helpscout.net/conversation/1540675886/25217?folderId=3808239)
> Add and fix gpuid-retroactively-populate-unique-ids.php

- gp-populate-anything/gppa-populate-child-entries.php
This PR fixes an issue where [gppa-populate-child-entries](https://github.com/gravitywiz/snippet-library/blob/master/gp-populate-anything/gppa-populate-child-entries.php) would generate a JS error in multi-paged forms.
This snippet ([Loom demo by David](https://www.loom.com/share/7b26b18f78624e0ca4bcd2b574636b8b)) assumed that GPNF would have instantiated Knockout.JS on page load. It already used the correct filter `gpnf_session_initialized`, however, the for loop needed to be inside that closure as well.
Ticket: [#25190](https://secure.helpscout.net/conversation/1539872947/25190?folderId=3808239)
> Fixed an issue where `gppa-populate-child-entries.php` may generate a JS error in multi-page forms.

- gravity-forms/gw-set-list-field-rows-by-field-value.php
This PR fixes an issue where the add/remove icons on a list field were still visible after activating this snippet.
I couldn't find an earlier version where we hid them, but the [demo on our site's documentation](http://demos.gravitywiz.com/set-number-of-list-field-rows-by-field-value/) has inline CSS that hides those icons.
Ticket: [#25350](https://secure.helpscout.net/conversation/1546148997/25350?folderId=3808239)
> Fixed an issue in `gw-set-list-field-rows-by-field-value` where List field icons were not hidden.

- gp-easy-passthrough/gpep-edit-entry.php
[HS#25575](https://secure.helpscout.net/conversation/1556161149/25575)
This PR adds support for bypassing GP Limit Submissions feeds when editing an entry. It does some significant refactoring so we'll want to retest these three scenarios.
1. Default functionality — updating an entry.
2. Deleting a partial entry when Partial Entries is active and `delete_partial` parameter is `true`.
3. Limit Submission feeds are bypassed when editing an entry.
> Added support for bypassing Limit Submissions feeds when editing an entry.

- gravity-forms/gw-validate-that-a-value-exists.php
This PR fixes a compatibility issue with GPPA. Validate that a value exists injected JS in GPPA's XHR responses.
The issue was two fold:
1) GPPA did not indicate while loading psuedo form to hydrate that it's an AJAX call (while applying `gform_pre_render`).
2) We could skip all checks as soon as we know that `$is_ajax_enabled` is true in the snippet.
Also for safety, a check if `GFFormDisplay` exists. This seemed inconsistent while using GPPA and ended up causing 500 errors.
Ticket: [#25828](https://secure.helpscout.net/conversation/1567861775/25828?folderId=3808239)
[GPPA PR](https://github.com/gravitywiz/gp-populate-anything/pull/213).
> Fixed a compatibility issue between `gw-validate-that-a-value-exists.php` and GPPA.

- gravity-forms/gw-create-coupon.php
This PR fixes an issue with the `gw-create-coupon` snippet's handling of start date with WooCommerce.
The snippet is supposed to set the coupons to start immediately, however if the timezone is behind GMT (e.g. `America/New_York`) the coupon gets scheduled to a time in the future and is not available for immediate use.
The fix here was to swap `gmdate()` with `current_datetime()` to respect the timezone set in WP.
Ticket: [#26099](https://secure.helpscout.net/conversation/1577829998/26099?folderId=3808239)
> Fixed an issue where `gw-create-coupon` scheduled coupons using GMT instead of the timezone configured in WordPress.

- gravity-forms/gw-update-posts.php
**[HS#26075](https://secure.helpscout.net/conversation/1576510052/26075/)**
This PR adds supports for removing the selected post's featured image if no value is submitted for featured image field specified in the configuration.
My primary concern with this is that we currently have no way to repopulate the current featured image from the post. It might be better to make this an opt-in feature with an additional configuration parameter. Thoughts?
> Added support for removing featured image if no value is submitted.

- gravity-forms/gw-cache-buster.php
GF 2.5 expects `$_POST` to be an empty `Array` before applying defaults to Checkbox fields.
While this is a Gravity Forms core issue, emptying out `$_POST` in GWCB resolves this issue.
I've modified @claygriffiths's patch slightly by not retaining `$_POST` in a variable. We `die()` immediately after GF outputs the form's markup.
Ticket: [#26188](https://secure.helpscout.net/conversation/1580050306/26188/)
> Fixed an issue with GF 2.5 Checkbox fields and `gw-cache-buster`.

- gravity-forms/gw-update-posts.php
This PR expands #127 by deleting custom fields if the source is empty and `delete_if_empty` option is specified.
Ticket: [#26286](https://secure.helpscout.net/conversation/1584354402/26286?folderId=3808239)
> Improved `delete_if_empty` argument by adding support for custom fields.

- gravity-forms/gw-progress-meter.php
[HS#26779](https://secure.helpscout.net/conversation/1605460958/26779/)
This PR adds support for automatically formatting numbers with thousands separators in progress bar labels. As part of this change, we had to switch from `%d` as our number placeholder to `%s`. We automatically account and convert for custom labels that might be using the `%d` by first converting them to `%s`.
A few examples of what this will look like:
> Added support for automatically formatting numbers (e.g. thousands separators) in labels.

- gravity-forms/gw-update-posts.php
Added support to update the Post slug using a Field Value. The parameter name is 'slug' and the user will be required to enter the ID of the field.
> Added support to Update Post Name (Slug)

- gravity-forms/gw-all-fields-template.php
This PR fixes our `apply_filters()` calls as well as the listeners for [gform_merge_tag_filter](https://docs.gravityforms.com/gform_merge_tag_filter/).
It looks like the snippet was missing the 6th parameters (`$format`).
The commit here adds it to the parameters list and also passes '`html`' by default when applying the filter.
Ticket: [#25603](https://secure.helpscout.net/conversation/1557163349/25603/)
> Fixed the number of arguments used with the `gform_merge_tag_filter` filter.

- gravity-forms/gw-restrict-states-in-address-fields.php
Bit of a hack but I think it makes the snippet a lot more practical! Thoughts? 
**Edit:** This also fixes an issue where all Address fields were validated even when a `field_id` was specified.
> Added support for filtering the displayed states based on the allowed states.

- gp-limit-choices/gplc-field-groups.php
This PR fixes a couple of issues that surface when using GPLC Field Groups snippet with conditionally shown/hidden fields that target the same output field.
The first issue is that the `gwlc_choice_counts_query` implementation did not consider whether all the fields in a group are visible, this caused the snippet to always return the result of the last defined GPLC group. This was fixed by utilizing `GFFormsModel::get_current_lead()` and applying `gform_pre_render` to ensure that conditionally hidden fields are treated as such.
The second issue had to do with the JS slug using the target field ID. Multiple initialization of the class that target the same field would only result in JS being rendered for the first instance. This was resolved by appending the hash to the slug.
Tickets: …
> Fixed an issue where `gplc-field-groups` snippet did not work properly when used with conditional logic and multiple fields.

- gravity-forms/gw-populate-date.php
This PR fixes a compatibility issue with GPPA and gw-populate-date snippet when using a Field Value Object to populate the source field.
The commit here adds `gppa_updated_batch_fields` to the list of events the snippet listens to when updating the target field.
Ticket: [#27144](https://secure.helpscout.net/conversation/1619932499/27144/)
> Fixed a compatibility issue between the `gw-populate-date` snippet and newer versions of GPPA.

- gravity-forms/gw-coupons-exclude-products.php
This PR migrates the [gw-coupons-exclude-products](https://gist.github.com/spivurno/351f6a936285604f5802) snippet to the library.
Additionally it fixes an issue where excluded fields may still be processed when GP E-commerce Fields is active as it uses the same `gform_coupons_discount_amount` filter and may run after this snippet excludes fields.
The fix here was to increase the priority to ensure that the snippet runs last and that excluded products are not reflected in coupons.
Ticket: [#27178](https://secure.helpscout.net/conversation/1621675354/27178?folderId=3808239)
> Fixed a potential issue where GPECF may interfere with the `gw-coupon-exclude-products` snippet.

- gravity-forms/gw-update-posts.php
This PR adds GV edit compatibility via `gravityview/edit_entry/after_update` to the `gw-update-posts` snippet.
Ticket: [#27431](https://secure.helpscout.net/conversation/1632041411/27431?folderId=3808239)
> Fixed a compatibility issue where posts weren't updated after an entry is updated via Gravity View.

- gravity-forms/gw-first-error-focus.php
[HS#27092](https://secure.helpscout.net/conversation/1618555630/27092)
This PR resolves an issue where the first field error was scrolled to but not given focus. The issue was introduced in 2e13614229491dee355ce8eb3406c7fda0c57a3b where scrolling was delayed but the focus was not. A field that is not in the viewport cannot be focused (I guess?).
To resolve this, we simply set the focus after the element has been scrolled to.
> Fixed issue where first field with error was scrolled to but not focused.

- gravity-forms/gw-populate-date.php
This PR resolves an issue where GPPA-populated fields and Live Merge Tags did not work when they were dependent on a GW-Populate-Dates-populated field. GWPD was populating the fields _after_ Populate Anything had already done its magic. 
Video of the use case recorded for the customer here: https://www.loom.com/share/db373ccd9c274712bfd118d8bdc37a86
> Fixed issue where GPPA-populated fields (and Live Merge Tags) did not work when dependent on a GW-Populate-Date-populated field.

- gravity-forms/gw-populate-date.php
This PR fixes an issue where a date field that's been modified by the snippet would revert back to the calculated date on submission.
It looks like the option `override_on_submission` was added before, but it was not being applied when a `source_field_id` existed.
Ticket: [#27634](https://secure.helpscout.net/conversation/1639770700/27634?folderId=3808239)
> Fixed an issue where `gw-populate-date` over-wrote populated date on form submission.

- gravity-forms/gw-all-fields-template.php
[HS#27798](https://secure.helpscout.net/conversation/1646375677/27798)
This PR adds the `gwaft_template_paths` filter to allow filtering the available template paths including the ability to add a new template path.
Customer is using a builder plugin with no active theme. Not even sure how that's possible but this filter should help. 😄
> Added `gwaft_template_paths` filter to allow adding custom template paths.

- gravity-forms/gw-multi-file-merge-tag.php
This PR adds support for the `{all_fields}` merge tag by utilizing the `gform_merge_tag_filter` filter.
Ticket: [#27719](https://secure.helpscout.net/conversation/1642757936/27719?folderId=3808239)
> Added support for `{all_fields}` merge tag in the `gw-multi-file-merge-tag` snippet.

- gp-populate-anything/gppa-lmt-modifier-img.php
- gravity-forms/gw-all-fields-template.php
[HS#27799](https://secure.helpscout.net/conversation/1646377681/27799)
This PR updates GPPA's `:img` modifier snippet to support outputting raw URLs as images in addition to the existing functionality of outputting images for attachment ID values.
The field's value can be a single URL or a comma-delimited list of URLs. This is relevant when populating values from Single and Multi-file Upload fields into a text-based field (e.g. Single Line Text).
> Added support for using the `:img` modifier with fields populated with URLs rather than attachment IDs as well.

- gravity-forms/gw-all-fields-template.php
[HS#27866](https://secure.helpscout.net/conversation/1647862627/27866)
> Added support for using the :exclude modifier to exclude child fields within a Nested Form on the `{all_fields}` merge tag.

- gp-inventory/gpi-inventory-shortcode.php
Add support for getting the inventories of fields using the Advanced inventory. If the Resource uses scopes, you can pass scope values using the new `scope_values` attribute.
Depends on `gpi_property_map_values` which is added in https://github.com/gravitywiz/gp-inventory/pull/19.
> gpi-inventory-shortcode.php: add support for Advanced inventory type and Scopes.

- gravity-forms/gw-time-sensitive-choices.php
[HS#28731](https://secure.helpscout.net/conversation/1689485544/28731)
With the growing popularity of GP Inventory, more users were requesting the ability to filter a "time slot" field such that times before the current time were not available _but_ only if the selected date was the current date.
This PR majorly refactors our existing Time Sensitive Choices snippet to achieve this goal.
> Added support for filtering times based on a Date field.

- gp-easy-passthrough/gpep-edit-entry.php
[HS#29155](https://secure.helpscout.net/conversation/1703886460/29155)
User wanted to conditionally edit the entry. This filter will allow him to do this with the following sample code:
```
add_filter( 'gpepee_edit_entry_id_123', function( $update_entry_id, $form_id ) {
// Update "4" to the field ID you want to check the value of.
if ( rgpost( 'input_1' ) === 'Add New' ) {
$update_entry_id = false;
}
return $update_entry_id;
}, 10, 2 );
```
One sneaky but significant change I made in this PR (unrelated to the filter) is changing from which form the edit entry ID is fetched when fetching from the session. For some reason, it was setup to pull from the target form's session rather than the source form's session.
This doesn't make sense as the entire point of the snippet is to edit the same …
> Added `gpepee_edit_entry_id` filter to allow modifying the entry ID used to target the entry to be edited.

- gravity-forms/gw-multi-file-merge-tag.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/1715878813/29602?folderId=5969086
💬 Slack: https://gravitywiz.slack.com/archives/G013UJV42D9/p1638560412001200
The default config for the multi-form-merge snippet doesn't explicitly handle the .jpeg extension, which is a distinction from .jpg.
> Added .jpeg extension to multi-file-merge default config

- gravity-forms/gw-validate-that-a-value-exists.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/1736245847/30206?folderId=5969086
This fixes (and future-proofs) the URL to load the spinner from for gravity-forms/gw-validate-that-a-value-exists.php
> Fixed the URL to load the spinner animation from

- gravity-forms/gw-round-robin.php
[HS#29963](https://secure.helpscout.net/conversation/1728316556/29963/)
The previous logic here expected the value of the choices to be an email field in order to make it available for selection in the notification. This PR adds support for GPPA-populated fields.
> Added support for selecting GPPA-populated choice fields in notifications.

- gp-inventory/gpi-waiting-list.php
Although the exhausted choices were selectable, they were not submittable.  The additional gpi_remove_choices filter will ensure that the choices are not removed which will ensure that the validation is bypassed when the form is submitted.
> Added gpi_remove_choices fitler

- gravity-forms/gw-time-sensitive-choices.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/1777997481/31297?folderId=1530128
Add a setting to remove past choices instead of disabling them.
_Without choices removed_
_Choices removed_
> GW Time Sensitive Choices: Added new `remove_choices` setting to remove past choices instead of disabling them

- gravity-forms/gw-format-date-merge-tags.php
[Ticket](https://secure.helpscout.net/conversation/1818729044/32606?folderId=14964#thread-5355725313)
The snippet causes a fatal error if $field is null. This PR fixes that issue by checking if $field exists before it checks for the input type.
> Added checks to ensure that field exist before checking for input type

- gravity-forms/gw-all-fields-template.php
The [gform_merge_tag_filter](https://docs.gravityforms.com/gform_merge_tag_filter/) filter expects 6 parameters and according to [this user's comment](https://secure.helpscout.net/conversation/1833639630/33106/#thread-5401589427), they were experiencing a fatal error when the snippet is used together with Campaign Tracker plugin.
> ~ Increased merge tag filter parameter number to 6

- gp-inventory/gpi-inventory-shortcode.php
[HS#31028](https://secure.helpscout.net/conversation/1769445143/31028)
Customer is using a Date field scope on a Single Product field. I've added exploratory support for displaying all dates that have consumed inventory. 
**Editor**
**Frontend**
This PR also includes a filter for modifying the scope's display value so that values can be easily formatted by need.
```php
add_filter( 'gpis_scope_display_value_848_2', function( $display_value ) {
return date( 'M j, y', strtotime( $display_value ) );
} );
```
**Frontend**
Added support for choice-based inventories.
**Editor**
**Frontend**
**Form Exports**
1. Single Product, Single Scope: https://gwiz.io/34Zfpfa
2. Choice Product, Single Scope: https://gwiz.io/3gQOR2p
> Added support for wildcard scope (*).

- gravity-forms/gw-require-list-columns.php
[HS#33924 ](https://secure.helpscout.net/conversation/1857899857/33924/)
When requiring specific columns, only the first row was validated. Based on the July 14, 2015 change log notice [on the article](https://gravitywiz.com/require-all-columns-of-list-field/), it looks like we've fixed this before? Not sure why it didn't stick.
> Fixed issue where requiring specific columns did not apply to subsequent rows (again).

- gp-unique-id/gpuid-shared-sequences.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/1862157634
⚠️ Related PR(s): https://github.com/gravitywiz/gp-unique-id/pull/15
Fixed issue where sequential IDs would not work as expected when using the Shared Sequential ID snippet with prefixes/suffixes.
> Shared Sequential ID issue

- gravity-forms/gw-calc-subtotal.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/1870799578
Fixed an issue where the subtotal merged tag is not read or parsed when the form is submitted together with a gravity form PayPal plugin.
> Subtotal merged tag issue

- gravity-forms/gw-set-list-field-rows-by-field-value.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/1862022699
Fixed issue where list column titles are not aligned when +/- buttons are set to hidden.
> List column titles alignment issue

- gp-limit-submissions/gpls-include-cpt-in-embed-url-post-page-rule.php
Hook Documentation : https://gravitywiz.com/documentation/gpls_rule_get_post_args/#include-posts-of-a-custom-post-type-in-the-embed-url-post-page-rule
> Include CPT posts in Embed URL › Post/Page rule

- gp-easy-passthrough/gpep-disable-passthrough-with-query-parameter.php
Hook Documentation: https://gravitywiz.com/documentation/gpep_field_values/#disabling-passthrough-with-query-parameter
> Disabling Passthrough With Query Parameter

- gp-file-upload-pro/gpfup-limit-duration-of-mp4-moc-files.js
Hook Documentation: https://gravitywiz.com/documentation/gpfup_before_upload/#limit-duration-of-mp4-mov-files-to-10-seconds
> Limit Duration of MP4/MOV Files

- gp-pay-per-word/gpppw-pay-per-character.js
- gp-pay-per-word/gpppw-pay-per-character.php
The string splitting functions cannot handle non-ascii bytes like umlauts (äöü) or emojis and would generate more than one array element for them.
In result, this whole function would return a character count of 6 (or 5 in JS) for this String: `Hiö🍻`, which is only 4 long.
The solution would return 4 as length of the string above in both cases.
See this link for a Demo on the PHP-site: https://www.tehplayground.com/PdKHf9u7UNoYH6c5
And the JSFiddle for the js-site: https://jsfiddle.net/xjrqczh4/
> gp-pay-per-word fixes counting bug

- gravity-forms/gw-cache-buster.php
[HS#36500](https://secure.helpscout.net/conversation/1942202155/36500/)
After switching languages via WPML, the current language was not honored when rendering the form via Cache Buster. 
WPML sets a cookie on the page load after switching languages but Cache Buster was triggering the AJAX request to fetch the form markup prior to that cookie being set. My solution was to simply pass the "lang" through as a parameter in the AJAX request which is automatically picked up by WPML allowing it to correctly identify the current language when the form is rendered via the Cache Buster AJAX request.
> Fixed issue where WPML's current language was not honored the first page load after switching languages.

- .github/workflows/php-lint-master.yml
- .github/workflows/php-lint-pr.yml
PHPCS was getting quite noisy in PRs since it was checking all files in the repository. This would cause PRs to fail checks even if everything in the PR was fine.
I decided to keep our existing action that checks all files and I set it to run on pushes to `master` that way we still have a global check.
> Updated PHPCS GitHub Action to only run on blames in PRs rather than all files.

- gp-limit-checkboxes/gplcb-validate-minimum-limit-when-required.php
Hook Documentation: https://gravitywiz.com/documentation/gplcb_should_validate_minimum/#only-validate-minimum-limit-when-field-is-required-or-when-at-least-one-checkbox-has-been-checked
> Validate Minimum Limit Only When Field is Required

- gp-multi-page-navigation/gpmpn-disable-submission-from-last-page-with-errors.php
Hook Documentation: https://gravitywiz.com/documentation/gpmpn_enable_submission_from_last_page_with_errors/#examples
> Disable Submission From Last Page With Errors

- gp-multi-page-navigation/gpmpn-change-the-next-page-with-errors-button-label.php
Hook Documentation: https://gravitywiz.com/documentation/gpmpn_frontend_labels/#examples
> Change the “Next Page with Errors” Button Label

- gp-nested-forms/gpnf-disable-nested-form-field-dynamic-values.php
Hook Documentation: https://gravitywiz.com/documentation/gpnf_should_use_static_value/#disable-nested-form-field-dynamic-values
> Disable Nested Form Field Dynamic Values

- gp-nested-forms/gpnf-repopulate-parent-merge-tags-when-editing-entries.js
Snippet Documentation: https://gravitywiz.com/documentation/gpnf_replace_parent_merge_tag_on_edit-js/#re-populate-parent-merge-tags-when-editing-entries-replacing-any-previously-saved-value
>  Repopulate Parent Merge Tags When Editing Entries

- gp-file-upload-pro/gpfup-display-images-in-entry-details.php
Also, removed support for displaying non-image file types and made links mandatory.
By limiting the scope of this we can simplifying the styling requirement significantly and still meet the requesting user's requirements. Until I share this and he wants it displayed the exact same way as GPFUP. 😅
Thoughts?
> Added styling support for displaying images as a grid.

- .editorconfig
- gravity-forms/gw-first-error-focus.php
https://secure.helpscout.net/conversation/1963934628
- Added `.editorconfig`
- Fixed issue with multi-page forms where validation error that is no longer active would be scroled to.
- Fixed issue where multi-page forms would not scroll to the top.
> `gw-first-error-focus`: Fixed improper scrolling issue on multipage forms

- gp-populate-anything/gppa-increase-query-limit.php
📓 Notion: https://www.notion.so/gravitywiz/gppa_query_limit-577a20c4e27a48e98557d9b51d2d0a06
The contents of the snippet were a duplicate of [another snippet](https://github.com/gravitywiz/snippet-library/blob/master/gp-populate-anything/gppa-change-query-limit-by-field.php). This corrects that to match the [example in the docs](https://gravitywiz.com/documentation/gppa_query_limit/#change-the-query-limit-to-750-for-all-dynamically-populated-fields).
> Fix gppa-increase-query-limit.php to be correct snippet.

- gp-nested-forms/gpnf-triggered-population.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/1973533007/37541?folderId=6987275
This snippet is supposed to add child form entries when a configured checkbox / radio button is selected and then remove that child entry item when de-selected.
There are a couple of items at play here that this PR addresses:
1. This was originally written to support radio buttons only and didn't work correctly with multi-select. The reason is because we weren't checking to see if the field was `checked` before calling `addChildEntry` in the `onchange` handler. Thus, when the field was de-selected (`!checked`), the add function would still be called.
2. The `removeChildEntry` function had not been implemented yet. Thus, even when it was called it didn't actually do anything.
Please note that this now …
> Fixed issue in `gp-nested-forms/gpnf-triggered-population` where nested form entries were not removed when unselecting the configured checkbox

- gp-nested-forms/gpnf-nested-entries-max-message.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/1976741186/37641/
This adds a snippet that allows you to modify the "add" button message next to nested form entry tables.
As an example:
> Added snippet that modifies the nested form button text content

- gravity-forms/gw-choice-counter.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/1975203407/37592?folderId=6987275
The choice counter snippet was not working when counting from a field populated by Populate Anything. This was because, as the field changed (was repopulated), we did not update / rebind the event handler functions so when the choice fields changed (e.g. were checked) the count wouldn't get updated.
> Fixed `gw-choice-counter` bug where count would not update when choices were populated from GP Populate Anything.

- gravity-forms/gw-tiny-mailing-list.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/1991551454/38176
In the past, Gravity Forms didn't support parsing multiple merge tags on choice-based fields. In order to work around this we removed the modifier in certain contexts. This created a conflict with a solution I'm working on for a customer that would allow them to use the All Fields Template plugin to filter a Nested Form field down to an Email field and a custom template that checks for the `:tinyml` modifier alter the markup to return a comma-delimited list rather than an unordered HTML list.
```php
<?php
/**
* @var $items
* @var $modifiers
*/
if ( function_exists( 'gw_all_fields_template' ) ) {
$modifiers = gw_all_fields_template()->parse_modifiers( $modifiers );
if ( array_key_exists( 'tinyml', $modifiers ) ) { …
```
> Removed code that removed the `:tinyml` modifier. Gravity Forms appears to support multiple modifiers for choice-based fields now!

- gravity-forms/gw-list-field-as-choices-usage.php
- gravity-forms/gw-list-field-as-choices.php
gravity-forms/gw-list-field-as-choices
The current logic does not allow the $values array to be customized/populated from additional sources that in-progress initial form submission. The PR filter adds support for scenarios involving an existing entry or value array customization. The usage example shows how it can be used with an existing entry via a Gravity Flow User Input step.
> gw-list-field-as-choices.php: Add `gwlfac_list_field_values` filter to allow filtering the List field values that will be used to populate choices.

- gravity-forms/gw-save-and-continue-auto-load.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/1989981370/38073/
This was loading up incorrect draft entry data when in the GPEB editor context. The fix is to add a check to _not_ do that if in the GPEB editor context.
> Fixed issue where Auto Save & Continue would conflict with editing entries using GPEB

- gp-populate-anything/gppa-populate-child-entries.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/1995729085/38292/
Customer was experiencing an issue populating child entry data into the parent form when traversing a multi-page AJAX form with conditional logic enabled. I was able to reproduce the same issue when an AJAX-enabled form was reloaded with a validation error.
The root issue is that the "gpnf_session_initialized" action that this snippet relies on is not triggered for subsequent loads of an AJAX-enabled form. I've updated the code to check if the session has already been initialized and if so to setup the Parent Entry ID field to trigger change events per usual.
> Fixed issue where child entry changes did not trigger a GPPA refresh when traversing AJAX-enabled forms.

- gp-inventory/gpi-waiting-list.php
Ticket: https://secure.helpscout.net/conversation/2004338008/38520/
The GPI waiting list snippet wasn't working and it appears to be because of the position of the function_exists statement. It looks like at the time this is checked GPI hasn't been instantiated so it returns false and doesn't run the code. The solution I applied is to move the function_exists check into the add_hook function, as its first statement.
> Moved function_exists into add_hook function

- gravity-forms/gw-populate-date.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2010411216/38704?folderId=14965
Customer desired to modify a user-entered date by a given number of weekdays and display that date immediately. The Populate Dates snippet supports modifying dates "live"; however, it previously did not support the "weekday" keyword.
Example configuration:
```
new GW_Populate_Date( array(
'form_id'         => 123,
'source_field_id' => 4,
'target_field_id' => 5,
'modifier'        => '+7 weekdays',
) );
```
> Added support for using "weekday" and "weekdays" keyword in modifier.

- gravity-forms/gw-conditionally-disable-checkboxes.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/1991229383/38164/
Related PRs:
https://github.com/gravitywiz/gwlimitchoices/pull/18
​https://github.com/gravitywiz/gp-inventory/pull/59
Much like GP Limit Checkboxes is currently accounted for, add support for not un-disabling checkboxes disabled by GP Limit Choices or GP Inventory.
> `gw-conditionally-disable-checkboxes.js`: Improve compatibility with GP Limit Choices and GP Inventory

- gravity-forms/gw-require-unique-values-usage.php
- gravity-forms/gw-require-unique-values.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2015924398/38889?folderId=3808239
[Gravity Forms: Require Unique Values for Different Fields](https://gravitywiz.com/gravity-forms-require-unique-values-for-different-fields/#download-snippet) makes the case-insensitive comparison. This update adds the case-sensitive argument, with its default as false.
> Updated "Require Unique Values for Different Fields" snippet with case sensitive option

- gravity-forms/gw-limit-multiselect.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2020716657/39063/
The issue was occuring because the `limitMultiSelect()` logic was only running when the configured select field changed. This meant that when returning to the select on a multi-page form, the limit logic may not have run yet and thus the user would be able to select more than the limit.
The fix is to run `limitMultiSelect()` each time the configured select comes into view.
> `gravity-forms/gw-limit-multiselect.js`: Fixed issue where multi select limit did not work correctly when going backwards on multi-page forms.

- gp-multi-page-navigation/gpmpn-render-all-page-links-on-load.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2025453715/39250?folderId=3808239
With GPEP + GPMPN if we use the [snippet](https://github.com/gravitywiz/snippet-library/blob/master/gp-easy-passthrough/gpep-edit-entry.php) for GPEP Edit entry, the form entry load appears as if it still creating a new entry (not editing). This snippet reloads all the links, so the edit entry look is there.
> `gpmpn-render-all-page-links-on-load.js`: Added new snippet to load all multi page navigation links when editing entries with GPEP.

- dangerfile.ts
Adds `Refactored` to the whitelist of allowed prefixes for commit messages.
> Tooling: Added `Refactored` to the list of available commit message prefixes and linked to Notion.

- gp-nested-forms/gpnf-override-parent-merge-tag-on-submission.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2015154047/38861/ 
It is difficult to configure `gpnf-override-parent-merge-tag-on-submission.php` for multiple child forms. This enables users to more easily apply the logic to multiple child forms.
- Refactors the snippet to a class to match our preferred snippet style.
- Support instantiating one instance of `GPNF_Override_Parent_Merge_Tags` per child form a user wants to configure.
- Support instantiating a single instance of `GPNF_Override_Parent_Merge_Tags` with no arguments to apply this to all child forms.
> `gpnf-override-parent-merge-tag-on-submission`: Updated to a class and made configuration for multiple child forms easier.

- gp-populate-anything/gppa-include-static-choices.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2030410700/39418?folderId=3808239
This updates the snippet `gppa-include-static-choices.php` to include ascending and descending sorting options. Use the CSS class `gppa-sort-static-choices-asc` or `gppa-sort-static-choices-desc` to enable the sorting
> `gppa-include-static-choices.php`: Updated snippet to include sorting options for static choices.

- gp-nested-forms/gpnf-child-products-in-parent-order-summary.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2022459557/39108?folderId=3808239
Nested Form Fields with live merge tags are not rendered completely. This fix includes the live merge tag processing for those fields.
> `gpnf-child-products-in-parent-order-summary.php`: Updated snippet to process Live Merge Tags for Nested Form Fields.

- gp-populate-anything/gppa-filter-by-relative-dates.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2030467703/39423?folderId=3808239
This adds merge tags of the format `{relative:anything_accepted_by_strtotime}` to be usable with the relative date snippet.
Example usage:
> `gppa-filter-by-relative-dates.php`: Updated snippet to use custom values which are valid for strtotime.

- gp-address-autocomplete/gpaa-custom-map-styles.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2036232747/39608?folderId=6987275
This new snippet demonstrates how to apply custom styles to a GPAA Map Field.
> `gpaa-custom-map-styles.js`: Added new snippet to demonstrate how to customize GPAA Map Field styles.

- gp-address-autocomplete/gpaa-map-marker-placed-auto-zoom.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2031360180/39451/
Adds a snippet that automatically sets map zoom level each time a marker is placed on the Address Autocomplete Map Field.
> `gpaa-map-marker-placed-auto-zoom.js`: Added new snippet to automatically set new map zoom level when a marker is placed.

- gp-easy-passthrough/gpep-edit-entry.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2039412111/39736?folderId=7098280
For multi-sites, GPEP Edit Entry crashes the website. This fix adds a check for Gravity Forms (`rgar` exists) to prevent the issue.
> `gpep-edit-entry.php`: Fixed GPEP Edit Entry Failing on Multisite.

- gravity-forms/gw-set-post-status-by-field-value-advanced.php
- gravity-forms/gw-set-post-status-by-field-value.php
`gw-set-post-status-by-field-value-advanced.php`: Fixed filename to match snippet.
📓 Notion: 
- https://www.notion.so/gravitywiz/Set-Post-Status-by-Field-Value-493f586087464ae6af13094e20c659b8
- https://www.notion.so/gravitywiz/Set-Post-Status-by-Field-Value-Advanced-4e46fa7876bd4ffbb1ea5ba2611e99f9
Renamed `gw-set-post-status-by-field-value.php` to `set-post-status-by-field-value-advanced.php` and migrated `gw-set-post-status-by-field-value.php` from Gists. Also updated Form and Field IDs to match [Snippet Library — Code Organization Formatting, and Naming](https://www.notion.so/gravitywiz/Snippet-Library-Code-Organization-Formatting-and-Naming-d5bee101d9674dfc98d7ec007867de2b) guidelines.
> `gw-set-post-status-by-field-value.php`: Migrated from GitHub Gists.

- gravity-forms/gw-populate-date.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2048953389/40044?folderId=3808239
When the target field is the same, the script name for all cases gets parsed to the same value. Adding the source field in the name ensures the uniqueness of each script name (and thus makes sure all scripts do fire).
> `gw-populate-date.php`: Fixed multiple source fields targetting same target field.

- gravity-forms/gw-export-multi-input-fields-single-colum.php
📓 Notion: https://www.notion.so/gravitywiz/How-do-I-export-multi-input-fields-in-a-single-column-with-Gravity-Forms-e15b331d5a7c4ad1899a781ae8f4b111
Migrated from [Gists](https://gist.github.com/spivurno/12031dcbaef3d87a8db5#file-gw-gravity-forms-export-multi-input-fields-single-colum-php)
> `gw-export-multi-input-fields-single-column.php`: Migrated from GitHub Gists.

- gp-nested-forms/gpnf-override-parent-merge-tag-on-submission.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2042741038/39830?folderId=3808239
This PR updates the should include and should exclude condition to fix the customer reported issue.
> `gpnf-override-parent-merge-tag-on-submission.php`: Fixed override parent merge tag on submission.

- gp-nested-forms/gpnf-auto-attach-child-files.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2011825626/38759/
- Refactors `gpnf-auto-attach-child-files` into a class.
- Moves configuration logic to constructor args so that users can easily create multiple, unique configurations.
- Adds `child_form_upload_field_ids` config option to limit which child form upload fields are included in a notification.
> `gpnf-auto-attach-child-files`: Refactored for greater configuration flexibility.

- gp-limit-checkboxes/gplcb-set-max-by-field-value.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2057426842/40321?folderId=3808239
Limit Number of Checkboxes depending on the selection made in the dropdown field did not work with Product Field. This update adds compatibility to the snippet for Product Field.
> `gplcb-set-max-by-field-value.js`: Updated snippet Set Max Limit by Field Value to work with product fields.

- gp-address-autocomplete/gpaa-autocomplete-zip.js
- gp-address-autocomplete/gpaa-autocomplete-zip.php
📓 Notion: https://www.notion.so/gravitywiz/Add-gpaa-autocomplete-zip-to-Snippet-Library-5727b64b895b43a6a40441bc94f0abbe
Migrating `gpaa-autocomplete-zip.js` and  `gpaa-autocomplete-zip.php` from [this Gist](https://gist.github.com/scyt/509118977b57f9f5581bbe804deb328c).
> `gpaa-autocomplete-zip.js`: Migrated from GitHub Gists.

- experimental/gpi-gpnf-exclude-child-entries-when-attached-to-a-partial-entry.php
- experimental/gpnf-add-child-entry-on-render.php
- experimental/gw-gfapc-map-multiple-fields-to-taxonomy.php
- gp-populate-anything/gppa-multi-value-contains.php
- gp-unique-id/gpuid-use-uid-field-in-conditional-logic.php
- gravity-forms/gw-zip-files.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2068662957/40696?folderId=3808239
Nested form entries have their uploads overridden on `$nested_archive_files` (associative array in play) which causes only the last nested form entry to be sent via zip. This update first adds all entry files at separate array indexes, then when processing archive files, we pluck and only copy the values to avoid `[path]` overrides when prep-ing the archive files array. This ensure all files from each nested form entry are successfully added to the zip
> `gw-zip-files.php`: Updated snippet to ensure all nested form entry uploads are added to zip.

- gravity-forms/gw-multi-file-merge-tag.php
- Added new "markup/container" property for specifying container markup that will contain all file markup.
- Added `gwmfmt_tags` filter for creating custom tags (like {filesize}). 
- Fixed issue in default markup.
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2065421606/40617/
Customer wanted to more easily define a container as part of her Multi-file Merge Tag template and also to include the file's file size in the generated markup.
This snippet uses the new `gwmfmt_tags` filter to add a custom tag for {filesize} which renders the filesize in kb's.
```php
add_filter( 'gwmfmt_tags_123', function( $tags, $file ) {
$tags['{filesize}'] = round( filesize( GFFormsModel::get_physical_file_path( $file ) ) / 1000 ) . 'KB';
return $tags;
}, 10, 2 );
```
Example of the configuration that …
> `gw-multi-file-merge-tag.php`: Added new "markup/container" property for specifying container markup that will contain all file markup.

- gravity-forms/gw-zip-files.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2068662957/40696?folderId=3808239
The `archive_files` method for the zip files snippet was hooked on `gform_entry_created`. The file renamer does the file renaming hooked at `gform_entry_post_save`. While the file entry still got the nested form renamed file pattern (entry save processed), the parent form did not because the zip was getting created before the file renamer operation was executed. The update here just makes the `archive_files` method execute on the same hook as the file rename operation but slightly later. The File Renamer has its filter hook call at priority 9, the snippet here does it at priority 10.
> `gw-zip-files.php`: Updated snippet to ensure zip has renamed file names done with GP File Renamer.

- gravity-forms/gw-populate-date.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2076433976/41028?folderId=3808239
When the desired populate date arithmetic was computing Hours 1 and onwards, the AM to PM conversion happened fine. The only issue was with Hour 12. This PR adds a condition to the logic to check the hour "12" when AM to PM swap should occur.
> `gw-populate-date.php`: Updated snippet to fix the hour 12 not updating to PM with arithmetic.

- gravity-forms/gw-require-unique-values.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2084259592/41399?folderId=3808239
By default, the snippet is designed to compare the values in two different fields and confirm that they are different.
This alters the behavior if a single field ID is passed and that field is a List field, we would process it for unique values over columns. For example,
A | B | C
A | D | E
Fails. A is present multiple times in the first column.
A | B | C
D | A | E
Passes. A is present multiple times but in different columns.
> `gw-require-unique-values.php`: Updated snippet to support checking over unique values on columns for List field type.

- gp-copy-cat/gpcc-selectively-copy-based-on-radio-choice.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2085288395/41436?folderId=3808239
https://www.loom.com/share/93e760f1004d402289151c57af780889
The source field for the copy cat operation is static by default, this snippet gives the capability of dynamically selecting the source field over a radio button choice list. Ensure the field IDs are stored on the radio button values, the ones which need to be targetted for copying.
> `gpcc-selectively-copy-based-on-radio-choice.js`: Added a snippet toselectively copy cat values.

- gp-notification-scheduler/gpns-gravityview-notifications-on-approve.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2083497762/41364?folderId=3808239
Using GPNS with GravityView's Approve/Disapprove is causing notifications to not send if the notification delay passes before the entry is approved. This snippet approach aims at overriding the notification delay timestamp comparison.
> `gpns-gravityview-notifications-on-approve.php`: Added a snippet for GravityView Notification Trigger.

- gp-copy-cat/gpcc-custom-copy-text-to-list.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2085199023/41433?folderId=3808239
Activating Copy Cat to copy a value to a list field that has Auto List Field active resets the number of list rows. This snippet overrides the standard logic with custom logic to only copy the value, and not reset the number of list rows.
https://www.loom.com/share/6e00d0f1edf54a7e8ff8fa0b38655ffd
> `gpcc-custom-copy-text-to-list.js`: Added snippet to support Auto List Field with Copy Cat on a Text field.

- gravity-forms/gw-choice-counter.php
Can be used to count  the number of Radio Button fields with a specific choice checked (e.g. "N/A").
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2105380160/42151/
Customer needed a way to count the number of times an "N/A" choice was selected across a number of Radio Button fields. @saifsultanc recently added support for counting specific choices to this snippet (https://github.com/gravitywiz/snippet-library/pull/586) so it seemed like a natural extension to add support for Radio Buttons.
> `gw-choice-counter.php`: Added support for counting Radio Button choices.

- gp-file-renamer/gpfr-allow-commas.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2103452211/42095/ 
* Relies on a new, unreleased filter in GPFR called `gpfr_sanitize_file_name_chars`.
* Removes commas from the list of dissallowed characters when renaming files with GPFR.
> `gpfr-allow-commas.php`: Added initial support.

- gp-ecommerce-fields/gpecf-deduct-deposit.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2075899506/40995?folderId=3808239
Check for Gravity Forms before initializing to prevent fatal errors, if Gravity Forms is not enabled.
> `gpecf-deduct-deposit.php`: Updated snippet to prevent fatal error when Gravity Forms is disabled.

- gp-populate-anything/gppa-strip-slashes-from-result-choices-text.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2096156781/41821?folderId=3808239
Strip slashes from GPPA populated choice text.
> `gpaa-strip-slashes-from-result-choices-text`: Added snippet to strip slashes from input choice text values.

- gravity-forms/gw-daily-form-schedule.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2118691329/42505?folderId=3808239
Add a check to skip processing for forms having set schedule start and end dates on Form Settings.
> `gw-daily-form-schedule.php`: Updated snippet to skip when schedule start and end dates are set on Form Settings.

- gravity-forms/gw-choice-counter.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2120099163/42554/
If hidden via conditional logic, the count field when unhidden would display empty instead of 0. This update overrides that. The rest of the functionality works normally.
> `gw-choice-counter.php`: Updated snippet to tackle count field issue when hidden via conditional logic.

- gp-unique-id/gpuid-generate-new-uid-when-duplicated-with-gfapi.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2126485010/42870/
Inspired by [snippet](https://github.com/gravitywiz/snippet-library/blob/7dee45a52df562d9574b64d4a021aea0a95850b3/gp-unique-id/gpuid-generate-new-uid-when-duplicated.php), this snippet regenerates UID for newly created entries via GFAPI - this will get a unique ID for duplicated entries.
> `gpuid-generate-new-uid-when-duplicated-with-gfapi.php`: Added snippet to regenerate Unique ID for GFAPI created entry.

- gravity-forms/gw-update-posts.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2128193021/42965?folderId=3775888
This pull request adds support for updating the Post date and time using the Date and Time fields, respectively. The parameter to set the post date and time will be an array named date_time, with two keys, namely date and time, and the value set to the date and time field, respectively. 
'date_time'    => array(
'date' => 2,
'time' => 3,
),
) );
> `gw-update-posts.php`: Added support to update post date and time.

- gravity-forms/gw-restrict-states-in-address-fields.php
Alter validation and code example at bottom to support the 2 state abbreviation as key such as in example 1 of gform_us_states (https://docs.gravityforms.com/gform_us_states/).
> Alter validation and code example at bottom to support the 2 state abbr

- gravity-forms/gw-multiple-entries-list-field.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2128964925/42994?folderId=7098280
The snippet creates entries from the list fields as per the field mapping rules defined. However, any notifications assigned under Gravity Forms Settings are not fired. This snippet adds the call to Gravity Forms notifications to fire them if they are defined under settings.
> `gw-multiple-entries-list-field.php`: Updated snippet to send notifications for created entries.

- gravity-forms/gw-include-post-permalink.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2137721499/43399/
User wanted to use our {post_permalink} merge tag with the Advanced Post Creation add-on. This PR adds support for it.
To test, you will need to:
1. Install and activated Gravity Forms Advanced Post Creation (APC).
2. Create an APC feed.
3. Add {post_permalink} to your confirmation.
4. Submit the form and confirm that the merge tag is replaced in the confirmation with the actual generated post's permalink.
> `gw-include-post-permalink.php`: Added support for the Advanced Post Creation add-on.

- gravity-forms/gw-update-posts.php
https://www.notion.so/gravitywiz/Update-How-to-Update-Posts-Update-Posts-Date-and-Time-2c6804a35da642eba85b49ffaec5b2aa
Added support to set the post date with a single value like 11 which can be a Date or Time field ID. If it is a Date field, the time is set to midnight. If it is a Time field, the date is set to the current date. 
'post_date'  => 11, // This can be either the Date or Time field ID.
) );
It also supports setting the Post date with an array of Date and Time field IDs like so
new GW_Update_Posts( array(  
'form_id' => 123,  
'post_id' => 1,  
'post_date' => array(  
'date' => 11,  
'time' => 12,  
),  
) );
> Update post date with either a date or time or both.

- gp-populate-anything/gppa-populate-all-results.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2135407267/43315/
Customer was attempting to use our "Populate All Results" snippet to populate all the names entered in a Name field across multiple child entries as a comma-delimited list in a Single Line Text field.
Previously, the snippet used the `$object_type->get_object_prop_value()` method which did not correctly handle joining the values for multi-input field's like Name fields. The `GPPA_Object_Type_GF_Entry::maybe_combine_multi_input_entry_template()` method bound to the `gppa_process_template` filter does but we need to call `GP_Populate_Anything::process_template()` to fetch the value so that it can be automatically applied.
@claygriffiths My specific concern here is just performance. I've already done my best to …
> `gppa-populate-all-results.php`: Updated to call `process_template()` so each object value is passed through all template filters.

- gravity-forms/gw-update-posts.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2149126204/43950?folderId=3808239
On debugging, I found that `$post_date` array wasnt' populated with the `date` and `time` values (for the case when we have both date and time passed with the snippet). This update just adds those missing values.
A simple form export is attached. How I tested it:
'form_id' => 221,
'post_date' => array(
'date' => 3,
'time' => 4,
),
) );
To test, please update form_id and post_id as per your local setup.
[gravityforms-export-2023-02-08.json.zip](https://github.com/gravitywiz/snippet-library/files/10686402/gravityforms-export-2023-02-08.json.zip)
> `gw-update-posts.php`: Fixed an issue where the post time would not be updated if directly passing a Time field's ID in the snippet config.

- gp-copy-cat/gpcc-copy-label.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2144521119/43725/
Updated snippet to include copy cat value functionality for Radio Button field.
> `gpcc-copy-label.js`: Updated snippet to include radio button copying values.

- gravity-forms/gw-advanced-merge-tags.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2079000554/41152/
Customer wanted a way to provide a hint of the field's value while masking most of it for privacy. 
Added the `:mask` modifier which will show the first and last letter and replace the rest of the output with asterisks. For email values, it splits the username and domain and masks them separately.
> `gw-advanced-merge-tags.php`: Added support for `:mask` modifier.

- gp-populate-anything/gppa-strip-slashes-from-result-value.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2096156781/41821?folderId=3808239
Strip slashes from GPPA populated value. Possible enhancements to look at could include running over all fields and detecting the existence of specific patterns of values which need to be decoded/strip slashes from.
> `gppa-strip-slashes-from-result-value.php`: Added snippet to strip slashes from GPPA populated value.

- experimental/gw-force-greater-end-time.js
When a form has a start time field and end time field, whereby the end time is supposed to be greater than the start time, this 
snippet populates the end time field with a time one hour ahead of the start time value. Also, it prevents the user from entering a time in the past. 
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2152005323/44085?folderId=3775888
> `gw-force-greater-end-time.js`: Added new snippet for Gravity Forms that forces users to enter a greater end time.

- gravity-forms/gw-currency-symbol-right-to-left.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2154262234/44174?folderId=2844288
Gravity Forms includes the `code` parameter in `gform_currencies`. Updating the snippet to also include that parameter.
> `gw-currency-symbol-right-to-left.php`: Updated to include `code` parameter.

- gp-nested-forms/gpnf-close-modal-on-esc-or-outside-click.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2158727063/44397?folderId=3808239
Close the modal when either escape key is pressed, or any click is done outside the modal area.
Here is how it works (~15 seconds):
https://www.loom.com/share/ab0e3a42d9a64652bd485840c218d459
> `gpnf-close-modal-on-esc-or-outside-click.js`: Added snippet to close modal when ESC key is pressed, or when mouse clicked outside modal area.

- gp-advanced-save-and-continue/gpasc-use-submission-values-for-draft-names.php
⛑️ Ticket(s):
* https://secure.helpscout.net/conversation/2163412284/44602/
* https://secure.helpscout.net/conversation/2164442912/44658/
Uses draft submission values for draft display names.
> `gpasc-use-submission-values-for-draft-names.php`: Added example snippet to use draft submission values as draft names.

- gravity-forms/gw-conditional-logic-entry-meta.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2137935962/43410/
Customer wanted to use Unique ID fields to filter entries via GP Email Users. By default, Unique ID fields are not available for conditional logic and as such they do not appear in the feed conditional logic setting used by GPEU. This snippet adds support for specifying field types that should be available for conditional logic on submission but not on form rendering and implements support for Unique ID fields specifically.
> `gw-conditional-logic-entry-meta.php`: Added support for Unique ID fields for use in GP Email Users.

- gravity-forms/gw-daily-form-schedule.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2044912193/39905/
Customer had a [Daily Form Schedule](https://gravitywiz.com/gravity-forms-daily-form-schedule/) setup spanning from Friday to Tuesday. The form was incorrectly blocked on Friday's and Saturday's due to an issue in how the schedule start date was calculated for interweek schedules. It was returning the date for the previous Friday. 
I've updated the logic to compare the current day of the week with the scheduled day of the week. If the current day of the week is less than the scheduled day of the week, then we assume the schedule is for "last week". Otherwise, we assume it is for "this week".
> Fixed issue where some interweek schedules did not work as expected.

- gravity-forms/gw-all-fields-template.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2056454691/40284/
Fixed an issue where using the `:nopricingfields` modifier on one field unintentionally applied the same effect to subsequent merge tags on the page.
I'm still a little fuzzy as to the exact reason this is happening but I narrowed it down to the fact that the filter was being bound multiple times and somehow not removing itself correctly.
This PR simplifies the code around this functionality and adds a new condition to only bind the filter if it has not yet been bound.
> Fixed issue where `:nopricingfields` modifier applied to subsequent merge tags on the form.

- gp-easy-passthrough/gpep-edit-entry.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/1984777991/37879
When using our [GPEP Edit Entries](https://gravitywiz.com/edit-gravity-forms-entries-on-the-front-end/) snippet, inventory reserved by entry being edited was not released, allowing the user to change their selection or even successfully submit the form (when using a Single Product field).
This PR adds support for that.
**Note:** Unlike other instances where we've adding support for releasing inventory (Nested Forms, GravityView), I opted to include this code here in the snippet rather than in GP Inventory itself. As we continue to develop and market Entry Blocks, it will replace this snippet so I'm hesitant to add code for a soon-to-be deprecated snippet in GP Inventory.
> gpep-edit-entry.php: Added support for releasing inventory reserved by the entry currently being edited.

- gp-ecommerce-fields/gpecf-tax-inclusive-order-summary-markup.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2172401409/45012?folderId=14964#thread-6474318188
This snippet uses a custom tax item to display an order summary with tax-inclusive calculations, mostly preferred in EU countries. 
It adds support to applying the tax-inclusive order summary markup to all forms. 
https://www.loom.com/share/5806b1d635844acb8615ff885afabce6
> `gpecf-tax-inclusive-order-summary-markup.php`: Added a new snippet to display a tax inclusive order summary.

- gravity-forms/gw-populate-date.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2177018899/45180?folderId=3808239
The script slug generated only took into account the source field id and target field id. Thus, when we had a scenario wherein the same source and target fields were aimed at, but with different modifier fields only the first one programmatically would work. This adds the modifier input id to the script slug thus resolving the issue.
Here is how it works now:
https://www.loom.com/share/cde9a6c3f69d4be69238a1fc25c586dd
> `gw-populate-date.php`: Fixed an issue with same source and target fields not working with different modifiers.

- gravity-forms/gw-prevent-duplicate-selections.js
⛑️ Ticket(s): https://secure.helpscout.net/link/to/conversation
Improve compatibility with GP Limit Checkboxes by utilizing new `gplc_excluded_input_selectors` JS filter hook added in https://github.com/gravitywiz/gwlimitcheckboxes/pull/17.
> `gw-prevent-duplicate-selections.js`: Improved compatibility with GP Limit Checkboxes.

- gravity-forms/gw-conditional-logic-operator-is-in.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2184530148/45561?folderId=3808239
Fixing PHP8 warnings.
> `gw-conditional-logic-operator-is-in.php`: Fixed PHP8 warnings for GW Conditional Logic Operator Is In.

- gravity-forms/gw-manual-entries.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2182975851/45466?folderId=7098280
The "Add New Entry" button shows on the Stripe Sales screen when the snippet is enabled. This update fixes that.
**_BEFORE:_**
**_AFTER:_**
> `gw-manual-entries.php`: Fixed an issue with Manual Entries button diplaying on Stripe Sales View.

- gp-advanced-phone-field/gpapf-disable-validation.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2207029432/46494/
Related to https://github.com/gravitywiz/gp-advanced-phone-field/pull/14
Fixed an issue with the Advanced Phone Number Validation snippet no longer working.
A ~1 min screencast of the old snippet, new snippet, and new snippet (when deactivated):
https://www.loom.com/share/b17ab80f4ba846bbaffde20e4930f3dc
> `gpapf-disable-validation.php`: Fixed an issue with Advanced Phone Number Validation Snippet not working.

- gravity-forms/gw-double-confirmation-fields.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2199448706/46185?folderId=3808239
The snippet does not skip the value comparison for field(s) that are hidden. Thus, even if all other fields match a hidden field would still keep on trigerring the failed validation. This update adds a check to ensure if a field is hidden, it is not taken as part of the value comparison.
A quick screencast of how it works: https://www.loom.com/share/dcd24eea34454711baad66556e9b7a84
> `gw-double-confirmation-fields.php`: Fixed an issue where the snippet would try to match for values of hidden fields.

- gravity-forms/gw-inventory.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2220460632/47304/
Customer has a form where users can request funding. There is a hard cap of $10,000 available for funding. He wants to prevent the total amount requested across all entries from exceeding this cap. 
This snippet is well equipped to handle this scenario except that it previously did not support currency-formatted Number fields. Now it does. 👨‍🏭
> `gw-inventory.php`: Added support for tracking "inventory" on currency-formatted Number fields.

- gravity-forms/gw-random-fields.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2226609602/47623/
The `modify_target_page` method gets stuck when the form is single page. This adds a check to skip that.
> `gw-random-fields.php`: Fixed an issue with single page form and random fields.

- gravity-forms/gw-all-fields-template.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2226818943/47628/
I wanted to use an underscored modifier as part my solution for the above ticket like so:
`:my_custom_template`
Previously, the modifier regex would return three separate modifiers for that: "my", "custom", "template". This slight tweak to the modifier regex adds support for underscores.
> `gw-all-fields-template`: Improved modifier regex to allow modifiers to contain underscores.

- gravity-forms/gw-submit-to-access.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2219398699/47227/
`GFFormDisplay::print_form_scripts()` was being called inside an output buffer which conflicted with Yoast SEO's output buffer.
> `gw-submit-to-access.php`: Fixed a potential conflict with Yoast SEO due to output buffer conflicts.

- gp-limit-checkboxes/gplcb-gppt-min-limit-soft-validation.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2192148507/45901?folderId=1530128
Relies on https://github.com/gravitywiz/gwlimitcheckboxes/pull/18
We've decided to go with a snippet route here as most of GP Limit Checkboxes' validation logic exists on the PHP side, especially when filters and complex group logic is involved.
> `gplcb-gppt-min-limit-soft-validation.js`: Added snippet to check minimum limit of Limit Checkboxes with Page Transitions' Soft Validation.

- gravity-forms/gw-merge-tag-tab.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2220926133/47348?folderId=3808239
This adds a merge tag `{tab}` for tabbed space. The context of adding this snippet is for usage with GP QR codes.
For a simple form with two text fields:
We are testing this with `[gpqr]{Single Line Text A:1}{tab}{Single Line Text B:2}{tab}[/gpqr] `
________________________________________________________________________________________________________________________________
**Before the merge tag added**
________________________________________________________________________________________________________________________________
**After the merge tag added (tabbed value is visible)**
> `gw-merge-tag-tab.php`: Added merge tag `{tab}` for tabbed space.

- gp-media-library/gpml-apc-attach-files-to-post.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2236815395/48148/
Attach Files uploaded via GPML to Posts created with GFAPC + ACF.
https://www.loom.com/share/7087869f092c4b9ea5c18e92d7ca1469
https://www.loom.com/share/f2480807382f4fd2a622db0f89e65351
> `gpml-apc-attach-files-to-post.php`: Added a snippet to attach files to posts created with Gravity Forms APC and ACF.

- gp-nested-forms/gpnf-child-entry-id-modifier.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2261594766/49479?folderId=3808239
Fixed an issue with character encoding. Using `DOMDocument::load` implies the text will be regarded in ISO-8859-1, which is the HTTP/1.1 standard character set. This results in UTF-8 strings being misinterpreted. 
To resolve this, we prepend an XML encoding declaration to the text
**_BEFORE:_**
**_AFTER:_**
> `gpnf-child-entry-id-modifier.php`: Fixed an issue with character encoding.

- gp-advanced-save-and-continue/gpasc-use-dropdown-to-toggle-enabled.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2151546100/44070?folderId=6987275 
Allows you to enable/disable GPASC based on the current the `value` of a dropdown field.
:warning: This is reliant on this GPASC change: https://github.com/gravitywiz/gp-advanced-save-and-continue/pull/16
> `gpasc-use-dropdown-to-toggle-enabled.js`: Added snippet to enable/disable GPASC based on a dropdown populated value.

- experimental/gppa-object-type-json-api.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2273072569/50303/
https://secure.helpscout.net/conversation/2275362111/50406?folderId=3808239
The snippet fails to work with GPPA 2.0, because GPPA 2.0 also stores the 'limit' value in the same array. A simple rule, would be as follows:
```
array(
0 => array(
0 => array(
'property' => 'name',
'operator' => 'contains',
'value' => 'faa'
)
),
'limit' => 750
);
```
This update adds a conditional logic to skip processing for non-array values.
> `gppa-object-type-json-api.php`: Fixed an issue with the snippet not working with GPPA 2.0+.

- gravity-forms/gw-all-fields-template.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2282427365/50946?folderId=3808239
On our snippet, we tap `gform_merge_tag_filter` at priority 11:
`add_filter( 'gform_merge_tag_filter', array( $this, 'all_fields_extra_options' ), 11, 6 );`
GravityView does it at priority 20:
`add_filter( 'gform_merge_tag_filter', array( 'GravityView_Merge_Tags', 'process_modifiers' ), 20, 5 );`
(gravityview/includes/class-gravityview-merge-tags.php)
To prevent GravityView from overriding the behaviour of GW All Fields Template, in this case specifically the List field, we should hook our filter call after what GravityView does.
**The "Child" form** and **The "Child" enter for testing**:
**GravityView set up with "Custom Content"**:
**_BEFORE:_**
**_AFTER:_**
> `gw-all-fields-template.php`: Fixed a conflict with GravityView.

- gravity-forms/gw-multi-file-merge-tag.php
Had a Gravity Wiz customer request this functionality via Image Hopper support.
Allow users to change the merge tag template for both File Upload fields and Image Hopper fields (uses the exact same underlying storage mechanism as a Multi File Upload field). 
This change allows other fields to be easily added in the future, should support need to be added.
> `gravity-forms/gw-multi-file-merge-tag.php:` Added support for Image Hopper fields.

- gravity-forms/gw-none-of-the-above-checkbox.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2296570360/52069?folderId=3808239
The snippet did not fire when "None" choice was selected by default.
**_BEFORE (on page load):_**
**_AFTER (on page load):_**
**Screencast with the update:**
https://www.loom.com/share/49355316a09d41e3bcb22f9649730846
> `gw-none-of-the-above-checkbox.js`: Fixed an issue with the snippet not firing for when None of the Above choice was selected by default.

- gravityforms-openai/gfoai-process-shortcodes-on-prompt.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2292239606/51747?folderId=7098280
By default, shortcodes are not processed on the message prompts. This snippet gives the ability to customize this, and process the message prompts on Chat Completion Messages.
Example OpenAI feed setting:
```php
function my_shortcode_test() { 
return 'This is my shortcode.';
}
add_shortcode( 'my_shortcode', 'my_shortcode_test' );
```
How the message prompts are processed:
> `gfoai-process-shortcodes-on-prompt.php`: Added a snippet to process shortcodes on the Message Prompts.

- gp-ecommerce-fields/gpecf-set-discount-amount-by-field-value.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2299585841/52198?folderId=3808239
When using the snippet, the Discount field's value isn't updating on the front end. It is only reflected after the form is submitted.
BEFORE:
https://www.loom.com/share/a9ecb44762c3400ba8321cc0de3e1759
AFTER:
https://www.loom.com/share/c1f2cc21fb0d47b59ba6d69571634bc3
> `gpecf-set-discount-amount-by-field-value.php`: Fixed an issue with the snippet not dynamically updating the discount value.

- gravity-forms/gw-conditionally-disable-checkboxes.js
⛑️ Ticket(s): Don't know.
A customer was confused on how to use this snippet with a Option field configured as a Checkbox. Explained about needing to include the price in the specified choice value.
> `gw-conditionally-disable-checkboxes.js`: Updated instructions for clarity on using choice values and handling values that contain prices.

- gravity-forms/gw-advanced-conditional-shortcodes.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2327129106/53384?folderId=3808239
A code logic update to the snippet.
The loop logic is :
```
foreach ( $conditions as $condition ) {
$is_match = GFFormsModel::matches_operation( $condition['value'], $condition['compare'], $condition['operator'] );
if ( $relation == 'any' && $is_match ) {
$conditional_met = true;
break;
} elseif ( $relation == 'all' && ! $is_match ) {
$conditional_met = false;
}
}
```
Just like for `any` relation and match found, we can set `$conditional_met` to true and just break from the loop, we should do the same break from the loop when for `all` relation we get even one not matching.
> `gw-advanced-conditional-shortcodes.php`: Fixed an issue with missing break on the conditional shortcodes snippet.

- gp-advanced-save-and-continue/gpasc-add-spinner-during-auto-save.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2295536795/52038/
💻 Github: https://github.com/gravitywiz/gp-advanced-save-and-continue/pull/34 
Adds a new snippet leveraging the [gpasc_auto_save_started-js](https://gravitywiz.com/documentation/gpasc_auto_save_started-js/) and [gpasc_auto_save_started-js](https://gravitywiz.com/documentation/gpasc_auto_save_started-js/) action hooks to show/hide a spinner during autosave requests.
> `gpasc-add-spinner-during-autosave`: Added new snippet to show/hide a snipper during a GPASC auto save request.

- gravity-forms/gw-cache-buster.php
💬 Slack: https://gravitywiz.slack.com/archives/C03T0CNL8AV/p1693304528635109?thread_ts=1692977024.600819&cid=C03T0CNL8AV
🆘 HelpScout: https://secure.helpscout.net/conversation/2318327951/52962/
https://www.loom.com/share/12e8a695e16f43be9f8720553ec7712b?sid=a561a02a-00c7-4c46-bb92-9ec8fa69e6e4
> `gw-cache-buster.php`: Fixed issue where default `gform_post_render` event suppression was not working after a string change in GF's init script.

- gp-advanced-save-and-continue/gpasc-radio-button-toggle.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2151546100/44070?folderId=6987275 
Adds snippet to allow radio buttons to toggle ASC on/off.
See also the required sister code change within GPASC: https://github.com/gravitywiz/gp-advanced-save-and-continue/pull/9
> `gpasc-radio-button-toggle.js`: Added snippet to toggle GPASC auto save client side using radio buttons.

- gravity-forms/gw-gravity-forms-rename-uploaded-files.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/1994083346/38231?folderId=6987275
We were not removing "/" or "." chars from new file names inputted by users in the `gw-gravity-forms-rename-uploaded-files.php` snippet.
The result is that users could ultimately manipulate the directory which a file was uploaded to which is insecure.
> `gw-gravity-forms-rename-uploaded-files.php`: Fixed issue where forward slashes and dots were not being removed from user inputted filenames.

- gp-file-renamer/gpfr-global-filename-template.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2330760345/53504?folderId=6987275 
Calling `get_template_value()` more than once per file can be problematic as it can cause the `{i}` merge tag to be incremented twice as fast as it should be.
This change leverages a new filter, `gpfr_filename_template`, that allows the filename template to be modified before `get_template_value()` is called internally within GPFR.
🚨 Relies on the changes in this GPNF pull request: https://github.com/gravitywiz/gp-file-renamer/pull/13
> `gpfr-global-filename-template.php`: Fixed issue where `{i}` merge tag would increment twice as fast as it should.

- gravity-forms/gw-dynamic-range.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2367056173/54949?folderId=3808239
The snippet doesn't work if the field used to set the min and max attributes are dynamically populated.
BEFORE:
https://www.loom.com/share/6410c8dfeb4b4ea8bf7b2295ca820659
AFTER:
https://www.loom.com/share/2f66ffff239446a089981a271cbab5f7
> `gw-dynamic-range.php`: Added support for dynamically populated min-max fields to work with dynamic range logic.

- gp-nested-forms/gpnf-populate-parent-entry-id.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2372876723/55235/ 
The `gpnf_session_script_data_` filter callback registered here was not returning a value which was breakin' some things.
> `gpnf-populate-parent-entry-id.php`: Fixed issue where `gpnf_session_script_data_` filter callback was not returning the filtered value.

- gp-file-renamer/gpfr-apply-rename-to-every-field.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2330760345/53504?folderId=6987275 
If using the `gpfr_filename_template` to automatically set a filename template for every field, it can become quite laborious to go through every single field and add a "dummy" template. This allows you to automatically apply GPFR to any field you want to on the fly.
🚨 Relies on the changes in this GPNF pull request: https://github.com/gravitywiz/gp-file-renamer/pull/13
> `gpfr-apply-rename-to-every-field.php`: Added snippet to apply GPFR to every field, no matter if there is an existing template value or not.

- gravity-forms/gw-prevent-duplicate-selections.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2377401092/55467?folderId=3808239
[This snippet](https://github.com/gravitywiz/snippet-library/blob/master/gravity-forms/gw-prevent-duplicate-selections.js) applies to Placeholder values, but it shouldn't.
Placeholder values should not be disabled.
**Both forms have the same placeholder values.**
**Before update** (on form load, second dropdown's Placeholder isn't selectable)
**After update** (on form load):
> `gw-prevent-duplicate-selections.js`: Fixed an issue with placeholder value getting disabled.

- gp-copy-cat/gpcc-copy-label.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2377837725/55492
The snippet to copy the label of a choice-based field, when using Copy Cat, doesn't work on a Checkbox field. It only supports Dropdown and radio button fields. This update adds support for the checkbox field.
BEFORE:
https://www.loom.com/share/255f3dbe2e234d9694bf29ce3114a662
AFTER:
https://www.loom.com/share/731daa5781c1404489a290d83336c6ec
> `gpcc-copy-label.js`: Fixed an issue with copying labels from checkbox selections.

- gp-media-library/gpml-ajax-upload.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2376105432/55428?folderId=3808239
Adding a `form_id` parameter to allow configuring GPML Ajax Upload snippet per form.
How it works?
https://www.loom.com/share/eff1688fbff6474d80250632e841f561
> `gpml-ajax-upload.php`: Updated snippet to ensure Ajax Upload can be applied to specific forms.

- gravity-forms/gw-modify-thousand-separator.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2382639486/55734?folderId=6987275 
Adds a snippet to remove the `thousand_separator` from a currency field.
> `gw-modify-thousand-separator.php`: Added new snippet to modify or remove the thousands separator in a currency field.

- gravity-forms/gw-gravity-forms-rename-uploaded-files.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2401416833/56482?folderId=3808239
The {filename} merge tag doesn't work when using the Rename uploaded files snippet. Inadvertently, we were processing `GFCommon::replace_variables` on the initial `$template` after having replaced the `{filename}` value from it (if present). This update fixes that issue.
**_THE FORM:_**
_**THE SNIPPET SETUP:**_
**_THE TEST CASE:_**
**_BEFORE:_**
**_AFTER:_**
> `gw-gravity-forms-rename-uploaded-files.php`: Fixed an issue where filename merge tag did not work.

- gravity-forms/gw-none-of-the-above-checkbox.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2398204713/56361/
[This snippet](https://github.com/gravitywiz/snippet-library/blob/master/gravity-forms/gw-none-of-the-above-checkbox.js) is not working. A JS error is output into the console on page load.
**BEFORE:**
**AFTER:**
> `gw-none-of-the-above-checkbox.js`: Fixed an issue with the snippet not working.

- gp-easy-passthrough/gpep-edit-entry.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2398744738/56383/
**Video Overview**: https://www.loom.com/share/152186005083436d860d43362ea4609c
If you edit an entry with existing values, and during the edit, an existing value's field is hidden via conditional logic, one would expect that this value would be deleted, but it is not.
This PR resolves that issue by using `GFAPI::update_entry()` with the entry that has been generated based on the current submission. The current submission entry may differ from the entry stored in the database as GF's default form submission process does not delete values for conditionally hidden fields, only saves/updates new field values.
**Note:** We'll probably want to implement this for Entry Blocks at some point.
> `gpep-edit-entry.php`: Added support for deleting values for conditionally hidden fields on edit.

- gravity-forms/gw-update-posts.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2402316918/56523?folderId=3808239
When the Update Posts snippet is active on this user's form, the confirmation message doesn't display after submitting the form.
We disable `wp_update_post` param `$fire_after_hooks` to ensure we do see the confirmation.
**Confirmation message setting on form:**
**BEFORE:**
**AFTER:**
> `gw-update-posts.php`: Fixed an issue with confirmation message not displaying.

- gp-entry-blocks/gpeb-readonly-on-edit.php
- gp-read-only/gpro-readonly-on-edit.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2402596321/56535?folderId=3808239
Snippet updated to add field disabled functionality to GravityView and Gravity Flow User Input steps, along with GP Entry Blocks.
**GPEB (text disabled to edit)**
**GravityView (text disabled to edit)**
**Gravity Flow (text disabled to edit)**
> `gpro-readonly-on-edit.php`: Added a snippet to provide disable editing functionality on GPEB, GravityView and Gravity Flow User Input.

- gp-address-autocomplete/gpaa-use-full-street-address.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2416758649/57134?folderId=3808239
If the address includes a /XX number at the end of the first address line, you can select the address from the GPAA returned results, but the /XX number is removed.
**BEFORE:**
**AFTER:**
> `gpaa-use-full-street-address.js`: Added snippet to use full street address for countries like Poland.

- gravity-forms/gw-prevent-duplicate-selections.js
📓 Notion: https://www.notion.so/gravitywiz/GPADVS-1-1-Disabled-Choices-d910084a1ed24bd8947fdd6df242a2a9?pvs=4 
This enabled support for this snippet on GPADVS enabled multi-select fields.
> `gravity-forms/gw-prevent-duplicate-selections.js`: Added support for GPADVS enabled multi-select fields.

- gravity-forms/gw-include-post-permalink.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2438396771/58350?folderId=3808239
The Post permalink snippet doesn't work with the latest version of Gravity Forms Advanced Post Creation Add-On.
As a fix, this update adds a 'retry logic' to ensure we do fetch the post id. Changing the priority of the hooks `add_filter( 'gform_replace_merge_tags', array( $this, 'replace_merge_tag' ), 10, 3 );` wasn't giving a consistent resolution. The retry logic gave 100% results on my testing.
Video demo of the issue (Credits @sbassah):
https://www.loom.com/share/dfc79bc1eda6424ab8bc7c4d457a6982?sid=7cf4436b-f7fe-434c-9a7b-07f3b4dbfa9a
After this update, the merge tag always works.
> `gw-include-post-permalink.php`: Fixed an issue with Post ID not fetching with merge tags with APC addon updates.

- gravity-forms/gw-gravity-forms-custom-js.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2451951378/58904?folderId=3808239
The Custom JS settings do not show when navigating to form settings via the form selector in the top left corner of Gravity Forms.
The initial logic is just to check the `subview` on the `$_GET`, but when we are loaded to the form settings via the form selector on the top left, the `subview` is blank. Even though the default view does still render the main Form Settings page. For this, we can add a case check - when `view` does confirm `settings` but `subview` is empty / not set.
**BEFORE:**
https://www.loom.com/share/840f0632eebe4f19906827cf99eb4fc0
**AFTER:**
https://www.loom.com/share/1d46572075df42028c833fcafcc33d5a
> `gw-gravity-forms-custom-js.php`: Fixed an issue with Custom JS not rendering in some scenarios.

- gravity-forms/gw-cache-buster.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2438335097/58348
Cache Buster incorrectly suppresses the default `gform_post_render` event for _all_ forms regardless of whether Cache Buster was enabled for that form or if that form was being rendered in a context that is applicable for Cache Buster.
Hilariously, I already tried to fix this once here (https://github.com/gravitywiz/snippet-library/commit/651990849fa8da6f9b5eacb3e0ad2945001aeeec) but I was clearly smoking crack at the time as it seems painfully obvious that was not the right place to move the filter. 😆
> `gw-cache-buster.php`: Fixed issue where default `gform_post_render` event suppression incorrectly applied to all forms.

- gp-advanced-select/gpadvs-enable-add-new-option.js
- gp-advanced-select/gpadvs-enable-add-new-option.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2449257866/58798/
`gpadvs-enable-add-new-option`: Converted to a PHP snippet to improve compatibility with Save & Continue.
This snippet follows our typical template for PHP/JS snippets. This works around needing to use Early Init as well.
Usage:
```php
new GPASVS_Enable_Add_New_Option(array(
// 'field_id' => 4,
));
```
> `gpadvs-enable-add-new-option.js`: Refactored to be a PHP snippet to improve compatibility with Save & Continue.

- gravity-forms/gw-advanced-merge-tags.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2463972101/59316?folderId=3808239
The `order_summary:my_custom_template` doesn't work when the snippet `GW_Advanced_Merge_Tags` is activated.
The `GW_Advanced_Merge_Tags` snippet just needs to ensure its `gform_replace_merge_tags` logic doesn't happen too soon. The `gform_replace_merge_tags` happens at '10' (order summary and others), we make sure the advanced merge tags merge tag replacement happens later - say '12'.
**BEFORE:**
**AFTER:**
> `gw-advanced-merge-tags.php`: Fixed an compatibility issue with `order_summary` merge tag modifiers.

- gravity-forms/gw-update-posts.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2461660694/59260?folderId=3808239
The update post snippet also updates the Post Date to the current date even when the post date parameter is not set. This fix makes sure we check for the presence of the values provided in the argument before setting them, i.e. `$this->_args['post_date']['date']` and `$this->_args['post_date']['time']`.
> `gw-update-posts.php`: Fixed an issue with Update Posts updating post date time even when value was not set.

- gp-nested-forms/gpnf-limit-entry-min-max-from-field.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2465600705/59366?folderId=7098280
The `attrReadyMaxFieldId` assigned to `self.maxFieldId.replace('.', '_')` can only be applicable if the maxFieldId is of data type string (having a value like '1.4', '2.2, etc). This would be because it is accessing a sub-field (like lists). For a simple text or number field, we just need `self.maxFieldId`. Also, calling `.replace` on a numeric value would trigger a console error.
Thus, this assignment must be updated with a check to ensure we are only applying it where necessary. Rest of the code compilation and processing is fine.
> `gpnf-limit-entry-min-max-from-field.php`: Fixed a possible error with the GPNF Min Max Entry Snippet.

- gravity-forms/gw-cache-buster.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2460911417/59241?folderId=3808239
`PHP Deprecated: Creation of dynamic property GW_Cache_Buster::$_args is deprecated in /.../gw-cache-buster/gw-cache-buster.php on line 20`
With PHP 8.2 the use of dynamic properties in a Class is deprecated. We need to have it explicitly declared.
> `gw-cache-buster.php`: Fixed PHP 8.2 warnings.

- gp-populate-anything/gppa-acf-repeater-mapper.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2470092230/59496?folderId=3808239
A limitation with the [ACF Repeater Mapper snippet](https://github.com/gravitywiz/snippet-library/blob/master/gp-populate-anything/gppa-acf-repeater-mapper.php) if the repeater field has a number attached to the name.
So, if we processed for `$key` as `meta_test_repeater_1_0_name`. This will give us:
`$repeater` as `test_repeater`
`$index` as `1`
`$subfield` as `0_name`
This is because of the additional 1 attached to the name. The `$repeater` is actually `test_repeater_1`, `$index` is `0`, and `$subfield` is `name`.
> `gppa-acf-repeater-mapper.php`: Fixed an issue with regular expression.

- gp-nested-forms/gpnf-auto-attach-child-files.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2481484636/59962?folderId=3808239
This snippet is supposed to auto-attach child files to the notification of the parent form. It works for the GF File upload fields, it doesn't work when an Image Hopper file upload field. This update adds support for that. We need to be specifying what upload files we need from the child entries:
`$upload_fields = GFCommon::get_fields_by_type( $child_form, array( 'fileupload', 'image_hopper', 'image_hopper_post' ) );`
> `gpnf-auto-attach-child-files.php`: Added support for Image Hopper Files.

- gp-advanced-select/gpadvs-enable-add-new-option.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2473904075/59646/
Added support for multi-page forms. The issue was that since the new choices weren't in the field's choices array, they'd be lost when the form is re-rendered.
The logic here is pretty similar to the newly added Save & Continue logic.
> `gpadvs-enable-add-new-option.php`: Added support for multi-page forms.

- gp-nested-forms/gpnf-auto-attach-child-files.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2481484636/59962?folderId=7098280
This does what the previous PR https://github.com/gravitywiz/snippet-library/pull/760 was supposed to do, but didn't because of a wrong commit.
This snippet is supposed to auto-attach child files to the notification of the parent form. It works for the GF File upload fields, it doesn't work when an Image Hopper file upload field. This update adds support for that. We need to be specifying what upload files we need from the child entries:
`$upload_fields = GFCommon::get_fields_by_type( $child_form, array( 'fileupload', 'image_hopper', 'image_hopper_post' ) );`
> `gpnf-auto-attach-child-files.php`: Added support for Image Hopper Files on Child Forms.

- gp-address-autocomplete/gpaa-single-line-as-input.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2491450269/60463
Customer wanted to require a selection when using this snippet to allow single input addresses. This makes sense and I've implemented this as the default mechanism for this snippet as it feels like not having this simply doesn't make sense. 😅
> Updated to require selection from autocomplete suggestions.

- gravity-forms/gw-multi-file-merge-tag.php
This update ensures any modifiers – [such as the native `:download` option](https://docs.gravityforms.com/file-upload/#h-modifiers) or any custom modifiers – outputs the expected value. 
To give you an example, let's say we are using the default settings, and our form has a Multi File Upload field (ID1) and two images uploaded.
**Before Change**
`{File Upload:1}` -> `<img src="{url1}" width="33%" /><img src="{url2}" width="33%" />` 
`{File Upload:1:index[1]}` -> `<img src="{url2}" width="33%" />` 
`{File Upload:1:download}` -> `<img src="{url1}" width="33%" /><img src="{url2}" width="33%" />` 
`{File Upload:1:count}` -> `<img src="{url1}" width="33%" /><img src="{url2}" width="33%" />`
**After Change**
`{File Upload:1}` -> `<img src="{url1}" width="33%" /><img src="{url2}" width="33%" />` …
> Don't Process File Upload merge tag if it contains a modifier other than `index`

- gravity-forms/gw-round-robin.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2523586865/62278?folderId=3808239
Added support for GP Inventory Choice Limits to Round Robin snippet's functionality. If an inventory is exhausted, round robin entry value will not be processed for that option.
> `gw-round-robin.php`: Added support for GP Inventory Choices with Round Robin functionality.

- gravity-forms/gw-all-fields-template.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2517551316/61937?viewId=8134459
With All Fields Template. `:nopricingfields` modifier shows Pricing Fields.
**BEFORE:**
**AFTER:**
> `gw-all-fields-template.php`: Fixed an issue with `nopricingfields` not hiding Product fields from the final result.

- gravity-forms/gw-first-error-focus.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2479112475/59893?folderId=3808239
https://secure.helpscout.net/conversation/2482109891/60004?folderId=3808239
The snippet takes the page to the `gform_wrapper` div on page load (i.e. when there are no rendered errors). The logic to scroll to `gform_wrapper` when there are no errors is the one that is causing the issues: `window.scrollTo(0, $('.gform_wrapper').offset().top);`
**Part - 1:**
https://www.loom.com/share/2a52775855d9413190f361d133a5e504
**Part - 2:**
https://www.loom.com/share/0aae06dc58374e3f86e6ff3cecbdbdd5
> `gw-first-error-focus.php`: Removed behavior to scroll to the top of the form if there is no error unless it's a multi-page form.

- gravity-forms/gw-cache-buster.php
💬 Slack: https://gravitywiz.slack.com/archives/C03T0CNL8AV/p1709131136355889 
Gravity Forms rolled out this change which we now need to account for here.
https://github.com/gravityforms/gravityforms/pull/2762
> `gw-cache-buster.php`: Added new `post_render_script` override for GravityForms change.

- gravity-forms/gw-cache-buster.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2535157762/63075/
Some shortcode  attributes are not passed to the `gravity_form` function, and that is due to the `esc_js` causing the `json_decode` to return NULL.
> `gw-cache-buster.php:` Fixed an issue where some shortcode attributes are not passed to `gravity_form` function.

- gp-nested-forms/gpnf-sync-parent-child-entry-payment-status.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2518151181/61994?folderId=7098280
The gpnf-sync-parent-child-entry-payment-status snippet is causing a fatal error when updating any entry: https://github.com/gravitywiz/snippet-library/blob/master/gp-nested-forms/gpnf-sync-parent-child-entry-payment-status.php
```
PHP Fatal error:  Uncaught TypeError: Illegal offset type in isset or empty in \..\gravityforms\includes\query\class-gf-query.php:
Stack trace:
#0 \..\gravityforms\includes\query\class-gf-query.php(1436): GF_Query->get_entries(Array)
#1 \..\gravityforms\includes\api.php(701): GF_Query->get_entry(Array)
#2 \..\code-snippets\php\snippet-ops.php(582) : eval()'d code(94): GFAPI::get_entry(Array)
#3 \..\public\wp-includes\class-wp-hook.php(326): …
```
> `gpnf-sync-parent-child-entry-payment-status.php`: Fixed a fatal error when the sync parent child entry payment snippet was activated.

- gp-entry-blocks/gpeb-disable-copy-cat-edit.php
- gp-entry-blocks/gpeb-remove-copy-cat-edit.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2530369085/62727?folderId=7098280
Snippet to prevent GPCC from copying values when editing the entry via Entry Blocks.
> `gpeb-disable-copy-cat-edit.php`: Added snippet to disable Copy Cat when editing using Entry Blocks.

- gp-advanced-select/gpadvs-preserve-choice-order.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2522300498/62231?folderId=7098280
Fix PHP warnings with the snippet.
```
Warning: array_flip(): Can only flip STRING and INTEGER values!
Warning: usort() expects parameter 1 to be array, null given
```
> `gpadvs-preserve-choice-order.php`: Fixed PHP warnings.

- gp-copy-cat/gpcc-copy-label.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2521383136/62172?folderId=7098280
GPCC Copy labels snippet copies only from the first radio button when multiple radio buttons are targeting to the same target field.
**BEFORE:** (Issue explained)
https://www.loom.com/share/6e3c06c5c4c04c178c8fe311363eb33b
**AFTER:**
https://www.loom.com/share/119205a37f3f4ecaa66616235bbb33d1
> `gpcc-copy-label.js`: Fixed an issue with copying labels from multiple radio buttons targeted to a single field.

- gravity-forms/gw-prevent-duplicate-selections.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2512621772/61659?folderId=6987275 
`gpadvsPreviousValues` was not initialized before it was used which broke functionality when GPADVS was enabled.
> `gw-prevent-duplicate-selections.php`: Fixed issue where variable was not initialized soon enough and broke functionality when GPADVS was enabled.

- gravity-forms/gw-update-posts.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2545475210/63599/
When using the [Update Posts](https://gravitywiz.com/how-to-update-posts-with-gravity-forms/) snippet, if the "Post ID" field is blank when the form is submitted, then the snippet will update the post that the form is embedded on, instead of just bailing.
**BEFORE**:
https://www.loom.com/share/185dd99a886c4194b0e59f677e2e8cd0
**AFTER**:
https://www.loom.com/share/2f655d3746a14659ba24ed6388c1bcb4
> `gw-update-posts.php`: Fixed issue where an empty post ID would result in the current post getting updated.

- gravity-forms/gw-populate-date.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2544365356/63530?folderId=7098280
The original logic to check for AMPM is to see `$inputs.length === 3`. There are 3 visible fields, one for the HOURS, one for the MINUTES, and third for the AM/PM (select-dropdown). The third is rendered only when the 12hour format is enabled (i.e. AMPM enabled). It is obviously not rendered with the 24hour format.
When we are also using the GP Read Only on the Time field, it adds a hidden input. This makes the number for `$inputs.length` to be 3 when 24hour format is enabled. Also, it makes the value as 4 when the 12hour format is enabled. So the calculation with the 24hour format is as if AMPM is enabled
See Read Only Time is trying to display 1:00 (instead of 13:00) with the **24hour** format
and …
> `gw-populate-date.php`: Fixed an issue with Populate Date Time Snippet and Read Only Time Field.

- gravity-forms/gw-update-posts.php
When set, snippet will append images for ACF Gallery fields instead of replacing. This is currently limited to ACF Gallery fields but could be readily expanded to other field types.
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2476493794/59790
Customer is using our Update Posts snippet to update an ACF gallery field attached to a post. Instead of replacing the images, he wants to append them.
This PR introduces the concept of passing custom parameters per meta value. Instead of setting the key and value, like so:
```php
'my_gallery' => 3
```
...you would instead pass an array as the value with any desired parameters:
```php
'my_gallery' => array(
'field_id' => 3,
'append' => true,
)
```
The previous format still works, of course.
> `gw-update-posts.php`: Added support for specifying an `append` parameter for meta values. 

- experimental/gpnf-gv-duplicate-child-entries.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2547000005/63710?folderId=8181748
Now, nested form entries can be duplicated along with the parent form entry when the 'Duplicate' link is clicked for an entry in GP Entry Blocks (either in a single entry view or all entries view).
> `gpnf-gv-duplicate-child-entries.php`: Added the ability to duplicate nested form (i.e. child) entries for GP Entry Blocks.

- gp-populate-anything/gppa-form-editor-increase-max-string-length.php
- gp-populate-anything/gppa-form-editor-skip-max-string-length.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2546023537/63636?folderId=7098280
This is dependent on the GP Populate Anything Updates pushed with the GPPA PR https://github.com/gravitywiz/gp-populate-anything/pull/524
Example links added here: https://gravitywiz.com/documentation/gppa_form_editor_max_string_length/
> `gppa-form-editor-increase-max-string-length.php`: Added snippet examples for JavaScript filter.

- gp-google-sheets/gpgs-hide-settings-tab.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2545786702/63622?folderId=8181748
The snippet conditionally hides the Google Sheets settings tab from the GF Settings menu tabs.
> `gpgs-hide-settings-tab.php`: Added new snippet for GP Google Sheets.

- gp-advanced-phone-field/gpapf-preserve-default-padding.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2552007047/63952
Depends on https://github.com/gravitywiz/gp-advanced-phone-field/pull/32
Fixed `TypeError: Cannot read properties of undefined (reading 'addEventListener')` console error. Refactored code to use the new `gpapf_after_initialize` [action filter](https://github.com/gravitywiz/gp-advanced-phone-field/pull/32).
> `gpapf-preserve-default-padding.js`: Fixed a console error.

- gravity-forms/gw-format-date-merge-tags.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2559727114/64318?folderId=3808239
https://gravitywiz.com/gravity-forms-date-merge-tags/#comment-901673
Adding a comma to the displayed date format returns an incorrect date. The format used for testing is `{:1:F j&amp;comma; Y}`. Here "1" is the field ID of the date field.
**BEFORE:**
**AFTER:**
> `gw-format-date-merge-tags.php`: Fixed an issue with Captured Dates on Notifications and Confirmation.

- gp-populate-anything/gppa-aggregate-functions.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2553813959/64057?folderId=3808239
The snippet triggers an infinite traversal on each of the `gppa_process_template`, we can unhook it after having it processed once for a template value.
> `gppa-aggregate-functions.php`: Fixed an issue with Aggregate Functions running infinitely.

- gs-product-configurator/gspc-process-entries-on-hold.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2557943787/64230?folderId=8181748
By default, for GSPC-enabled forms, feeds are only triggered when the payment is processing or complete. This new snippet makes it possible to trigger feeds when the order is on hold.
> `gspc-process-entries-on-hold.php`: Added a new GSPC snippet that triggers feeds when order is on hold.

- gs-product-configurator/gspc-add-order-meta-to-gf-entry.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2556313259/64159?folderId=8181748
> `gspc-add-order-meta-to-gf-entry.php`: Added a new snippet that adds order metadata to GF entries on export.

- gp-address-autocomplete/gpaa-show-address-in-language.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2577549960/65279
When users enter an address, it is populated from Google based on the browser's language. This PR provides a way to force Google to use a chosen language instead.
> `gpaa-show-address-in-language.php`: Added snippet to show address in a specific language in the address fields.

- gp-address-autocomplete/gpaa-single-line-as-input.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2580726019/65425?folderId=7098280
Use [full street address](https://github.com/gravitywiz/snippet-library/blob/master/gp-address-autocomplete/gpaa-use-full-street-address.js) snippet cannot be directly used with the current Single Line as Input snippet. This update adds an extra argument to the Single Line as Input `use_full_address` and the internal logic with `gpaa_values` processes either functionality accordingly.
Quick Loom:
https://www.loom.com/share/b0633a46e44547189ca51954d524d5c4
> `gpaa-single-line-as-input.php`: Added full address capability to the Single Line as Input functionality.

- gp-nested-forms/gpnf-delete-child-entries-when-parent-value-changes.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2588340284/65814?folderId=7098280
The snippet above doesn't work as expected when there are multiple nested form field on the page. it doesn't delete the nested forms entries when the parent value is changed.
**BEFORE:**
https://www.loom.com/share/c52aa6d524fa4af097b0aa8fe7ff8cde
**AFTER:**
https://www.loom.com/share/8cf6d2c6ec7d45ae958025a919459bcb
> `gpnf-delete-child-entries-when-parent-value-changes.js`: Fixed issue with snippet not working with multiple Nested Forms.

- gp-address-autocomplete/gpaa-always-use-subpremise.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2586015039/65683?folderId=3808239
Added a variable that be can set in the snippet that will dictate where the subpremise is added.
`let addSubpremiseToLine2 = true;`
If `true` , it will add the subpremise to the Address Line 2 input. If false it will append it to the address Street Address input value. Make sure to update the snippet description to indicate this option.
**Sample Address: 5/50 Aaron St, Box Hill NSW, Australia**
With `let addSubpremiseToLine2 = false;`:
With `let addSubpremiseToLine2 = true;`:
> `gpaa-always-use-subpremise.js`: Added option to show subpremise on Address Line 2.

- gravity-forms/gw-multi-file-merge-tag.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2585286901/65650
Fix `Undefined array key "container" ` warning.
> `gw-multi-file-merge-tag.php`: Fixed `undefined array key` warning.

- gravity-forms/gw-disable-submit-button-until-required-fields-are-filled-out.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2570453216/64916/
The [Disable Submit snippet](https://github.com/gravitywiz/snippet-library/blob/master/gravity-forms/gw-disable-submit-button-until-required-fields-are-filled-out.php) doesn't work with a required Upload field, with mutli-file enabled. This adds compatibility for that.
> `gw-disable-submit-button-until-required-fields-are-filled-out.php`: Fixed multiple file upload compatibility with Disable Submit snippet.

- gp-ecommerce-fields/gpecf-deduct-deposit.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2599694484/66359
[Deduct Deposit from Order Summary snippet](https://gravitywiz.com/snippet-library/gpecf-deduct-deposit/) throws an error on submission: Submitted value ($xx) does not match expected value ($xx)
**How the error appears:**
Need to tap the [`gform_product_total`](https://docs.gravityforms.com/gform_product_total/) JS hook to actually update the total value, to prevent it from failing validation.
**BEFORE:** (front-end Deposit value appears as a normal product value getting added to Total)
**AFTER:** (front-end Deposit working as a discount value getting substracted from Total)
> `gpecf-deduct-deposit.php`: Fixed validation error with Deduct Deposit snippet.

- gs-product-configurator/gspc-validate-date-fields-in-cart.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2588416647/65817
Validation of dates field in WooCommerce cart especially when carts are abandoned (for long), then resumed. E.g.:
On 5/6/24: User adds an entry with date 5/7/24 to their cart but abandons cart.
On 5/8/24: User returns to the site. The entry in the cart now has a date in the past OR a date that's invalid according to GP Limit Dates conditions.
> `gspc-validate-date-fields-in-cart.php`: Added validation of date fields in cart.

- gravity-forms/gw-field-to-field-conditional-logic.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2600589764/66401
The snippet isn't working with GP Inventory's "Available" conditional logic option. The issue is non-numeric ids are excluded from the dependencies array. This PR should fix the issue.
> `gw-field-to-field-conditional-logic.php`: Added support for non-numeric rule field ID.

- gravity-forms/gw-require-unique-values.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2583004576/65519
Added support to required unique inputs for `name` field type. Original request was specifying the  inputs id,(not sure if the user can specify the input ids correctly as they are not visible on the editor) but trying to keep it simple by requiring unique value for all inputs.
> `gw-require-unique-values.php`: Added support to required unique field inputs.

- gravity-forms/gw-advanced-merge-tags.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2609518435/66829
Add support for `abbr` merge tag modifier, when used on an address field returns the selected country two-letter code.
> `gw-advanced-merge-tags.php`: Added support for `abbr` address field merge tag modifier.

- gravity-forms/gw-limit-radio-button-selections-across-fields.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2615062924/67085
Snippet to deselects options (in Radio Button field) if same option is selected in another field.
**David's loom of what we intend to achieve:**
https://www.loom.com/share/cd7b743b06184905ad4bd6906a6d8e88
**Loom of how this new snippet works:**
https://www.loom.com/share/3d42f3c88ab14f23ad63d491bb77bac4
> `gw-limit-radio-button-selections-across-fields.js`: Added snippet to limit radio button selections across fields.

- gravity-forms/gw-validate-that-a-value-exists.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2622834298/67455
We were erroneously mapping target field's ID when validating on AJAX side. Fixed it with `sourceFieldId`. This fix had nothing to do with GPUID.
Walkthrough of the issue:
https://www.loom.com/share/42e2401ba9854f64acaf52e8970954fb
> `gw-validate-that-a-value-exists.php`: Fixed an issue with validate value not working with AJAX.

- gravityforms-openai/gfoai-save-prompt-to-entry.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2612211847/66960
Sometimes, a prompt could have a lot of conditionals, so you can't simply copy it using a Live Merge Tag. This snippet grabs the final prompt that's ultimately sent to OpenAI and stores it along with the entry.
> `gfoai-save-prompt-to-entry.php`: Added the ability to save the final prompt to the entry.

- gp-nested-forms/gpnf-map-child-entries-to-acf-repeater-field.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2438225719/58343?folderId=7098280
When the parent form is submitted, a post is created with the Advanced Post Creation add-on. The Nested Form entries should be linked to the targetted repeater field in the created post, but they don't work. This is down to the asynchronous behavior of Gravity Forms Advanced Post Creation Add-on v1.4.0 ([changelog](https://docs.gravityforms.com/advanced-post-creation-change-log/)). Disabling async does resolve the issue.
Also, the snippet is converted to a class-based snippet for easy management by the end user.
> `gpnf-map-child-entries-to-acf-repeater-field.php`: Fixed an issue with nested form field data not displaying on ACF field.

- gravity-forms/gw-advanced-merge-tags.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2616973134/67202
Added support for a :selected modifier that would let you target the selected checkbox by its zero-based index in our [Advanced Merge Tags](https://gravitywiz.com/snippet-library/gw-advanced-merge-tags/) snippet.
**How this update works:**
https://www.loom.com/share/0cc9030f5e4a40b59911ff6af3315078
> `gw-advanced-merge-tags.php`: Added `:selected` modifier to target selected checkbox by index on the Advanced Merge Tags snippet.

- gp-address-autocomplete/gpaa-show-place-name.js
- gp-address-autocomplete/gpaa-show-place-name.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2629624110/67745?folderId=8114575
Fixed `ReferenceError: gform is not defined` console error. The issue here is that the `gform_pre_enqueue_scripts` is called twice. The first call is the culprit. But `wp_head` hook will suffice in this case.
> `gppa-show-place-name.php`: Fixed `gform is not defined` console error.

- gp-limit-dates/gpld-block-date-ranges.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2629654339/67747?folderId=8114575
The snippet doesn't include the End Date in the block dates. This PR will fix the issue.
> `gpld-block-date-range.php`: Fixed an issue where the end date is not included.

- gravity-forms/gw-cache-buster.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2630007391/67768/
When Cache Buster is enabled, Nested Form fields are not being cleared when paying for a form using PayPal.
_Loom demonstrating the issue:_ https://www.loom.com/share/4816b6c7728a416083cfc706b28ff54a?sid=540ba7fe-133d-4e13-b4fb-b00912b4a181
When we submit form with Stripe checkout, `GPNF_Session::get_session_path` gets the correct session path, however, the same on paypal isn't true. It gets an empty session path. `GPNF_Session::delete_cookie`(L180) relies on getting correct cookie to delete it. Since, the session path isn't correct with paypal it fails. This only happens with Cache Buster.
_xDebug snapshot with Stripe:_
_xDebug snapshot with Paypal:_
The fix proposed here is to ensure we have removed all cookies …
> `gw-cache-buster.php`: Fixed issue with Cache Buster not clearing cookies with Paypal checkout and Nested entry.

- gravity-forms/gw-update-posts.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2642126240/68313
When the Snippet is set up with an invalid meta field ID, it throws a fatal error. This PR will fix the issue.
> `gw-update-posts.php`: Fixed fatal error issue caused by invalid field ID.

- gp-address-autocomplete/gpaa-allow-browser-autocomplete.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2642022306/68309
Filter whether browser autocomplete should be prevented, defaults to `true`. This provided an easy override to `false` (i.e. allow browser autocomplete).
> `gpaa-allow-browser-autocomplete.js`: Added snippet to allow browser autocomplete with GPAA.

- gp-address-autocomplete/gpaa-show-place-name.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2629624110/67745?folderId=6987275 
Adds a change event emission so that the event gets propogated after the place name is set in the address field.
This was a suggestion from the customer and I think it makes sense as it may help avoid issues with the event not bubbling for anyone using this in the future.
> `gp-address-autocomplete/gpaa-show-place-name.js`: Added change event when populating address field name.

- gp-address-autocomplete/gpaa-acf-gfur-google-maps.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2648540141/68609
A snippet for mapping `GPPA` address field to `ACF` map field via GF User Registration add-on.
> `gpaa-acf-gfur-google-maps.php`: Added a snippet for mapping `GPAA` address field to `ACF` map field via GF User Registration add-on.

- gravity-forms/gw-dynamic-range.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2649614006/68685
The Dynamic range snippet doesn't work on the front end, for the max value when a decimal is entered. The issue is because on the javascript we are typecasting the current value to integer: `currentValue = parseInt( currentValue );`. Overriding that fixes the issue.
**BEFORE:**
https://www.loom.com/share/c002e98098374e09b65e8782744c2062
**AFTER: (~30 seconds)**
https://www.loom.com/share/643a79c35fbc4c6986835a9e9dc52831
> `gw-dynamic-range.php`: Fixed issue with decimal values on dynamic range.

- gravity-forms/gw-populate-date.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2632728563/67897
When using the [Populate Date/Time snippet](https://github.com/gravitywiz/snippet-library/blob/master/gravity-forms/gw-populate-date.php), if a Time field is shown with conditional logic, it is not populated.
We need to send the Time field, like the Date field, in a string data format and not array.
Summary of the snippet in action:
https://www.loom.com/share/b19cd15445664b8bb00c9898e0fdbdff
> `gw-populate-date.php`: Fixed an issue with default time not loading after conditional logic.

- gravity-forms/gw-disable-autocomplete.php
💬 Slack: https://gravitywiz.slack.com/archives/GMP0ZMNSE/p1721422667276589
Dani reported that this snippet wasn't working for her in Firefox. I confirmed. I fixed.
**Notes:** 
- I simplified the logic on the form autocomplete attribute since, in my testing, it didn't actually have any impact on whether or not the individual inputs were auto-filled.
- I only tested in Chrome and Firefox and scoped the input changes as such. We may end up needing to default to this "new-password" value for all browsers at some point.
> `gw-disable-autocomplete.php`: Fixed issue where Firefox no longer honored the "off" value for the autocomplete attribute.

- gravity-forms/gw-limit-multi-selects.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2499159955/60820/ 
If no options are selected for a configured multi-select, the `$value` arg in `validate()` will be an empty string and the function will return early without setting a validation error.
The fix is to explicity set `$count` to `1` if an empty string is detected so that the remainder of the logic will work as expected.
> `gw-limit-multi-selects.php`: Fixed issue where setting the `min` to `1` did not work.

- gravity-forms/gw-round-robin.php
Ticket: https://secure.helpscout.net/conversation/2655184620/68924/
PHP 8.2 deprecation notice
`Creation of dynamic property GW_Round_Robin::$_args is deprecated`
> `gw-round-robin.php`: Fixed PHP 8.2 warnings.

- gravity-forms/gw-advanced-merge-tags.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2649918005/68702
When the `Advanced Merge Tags` snippet is used, the snippet would replace unknown merge tag label with an empty string hence the issue. This PR will add a check for unknown labels.
> `gw-advanced-merge-tags.php`: Fixed an issue with unknown advanced merge tag label.

- gravity-forms/gw-all-fields-template.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2517551316/61937
Make the logic cleaner, still continues to do the job well. Snapshot of how all the scenarios display correctly.
`{all_fields}`
`{order_summary}`
`{all_fields:nopricingfields}`
> `gw-all-fields-template.php`: Fixed logic for `nopricingfields` scenario.

- gp-nested-forms/gpnf-hide-expired-nested-form-field.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2660146653/69147
Snippet to hide a Nested Form field if the child form has expired (due to a schedule being set up on the child form). Currently, if the child form has expired, the modal will still open and display the form, but there will be an error when adding the entry:
**Demo:**
https://www.loom.com/share/798f30d73d254864aa6a65e7d16d390b
> `gpnf-hide-expired-nested-form-field.php`: Added snippet to Hide Expired Nested Form Field.

- gravity-forms/gw-update-posts.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2661062488/69207
This PR updates the snippet to update posts when the entry is updated via the GravityFlow User input step by tapping the `gravityflow_step_complete` hook.
> `gw-update-posts.php`: Added support for Gravity Flow Workflow Steps.

- gp-media-library/gpml-acf-user-image-field.php
- gp-media-library/gpml-ajax-upload.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2667457194/69503
PHP Warning
```
Deprecated: Creation of dynamic property GPML_ACF_User_Image_Field::$_args is deprecated.
```
> `gpml-acf-user-image-field.php`: Fixed PHP 8.2 warnings.

- gravity-forms/gw-user-registration-update-by-email.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2667097473/69480
An error generated when the [GF User Registration Update by Email](https://github.com/gravitywiz/snippet-library/blob/master/gravity-forms/gw-user-registration-update-by-email.php) snippet is active. This fixes the issue.
> `gw-user-registration-update-by-email.php`: Fixed potential fatal warning generated with the snippet.

- gp-nested-forms/gpnf-child-products-in-parent-order-summary.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2670405760/69619
When the [Include Child Products Directly in Parent Form Order Summary](https://github.com/gravitywiz/snippet-library/blob/master/gp-nested-forms/gpnf-child-products-in-parent-order-summary.php) snippet is active on a site that uses GSPC, the total from the Nested Forms is not added to the Woo product.
The fix here is to modify the child product key within the loop.
> `gpnf-child-products-in-parent-order-summary.php`: Fixed an issue where nested form product field total in not include in woocommerce cart total.

- gs-product-configurator/gspc-sync-field-max-to-wc-quantity.js
When the input is mapped as woocommerce quantity, the max input attribute is not set to the maximum quantity of the selected product. This PR fixed the issue by using the `found_variation` action to listen to changes instead of using the mutation observer.
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2677576845/69900
> `gspc-sync-field-max-to-wc-quantity.js`: Fixed an issue with max attribute when input is mapped as WooCommerce quantity.

- gp-limit-dates/gpld-inline-datepicker-only-for-mobile-devies.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2675073655/69822
Totally missed creating this PR. Doing so now..
Snippet to only apply inline date picker for mobile devices.
EDIT: Lost track of this totally, from what i recall the [JS hook](https://docs.gravityforms.com/gform_datepicker_options_pre_init/) suggested by Dave was causing issues with the broken display on the non-inline datepicker (desktop view)
> `gpld-inline-datepicker-only-for-mobile-devies.php`: Added snippet for inline datepicker to work only on mobile devices.

- gp-nested-forms/gpnf-disable-sessions.php
Closed #874. 
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2677531768/69897
The title says it all. Supported by https://github.com/gravitywiz/gp-nested-forms/pull/287.
> `gpnf-disable-sessions.php:` Fixed an issue where unauthenticated users cannot edit or delete entries.

- gravity-forms/gw-require-unique-values.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2686989633/70358
The snippet doesn't work when the fields involved are Product Choice fields having similar label/value property but different prices.
> `gw-require-unique-values.php`: Fixed issue with Product Value comparison.

- gp-easy-passthrough/gpep-edit-entry.php
- gp-ecommerce-fields/gpecf-set-discount-amount-by-field-value.php
- gp-ecommerce-fields/gpecf-tax-amounts-by-field-value.php
- gp-ecommerce-fields/gpecf-tax-inclusive-order-summary-markup.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2628106398/67682
https://secure.helpscout.net/conversation/2615336042/67099
Formatting: Fixed PHP 8.2 warnings in a handful of snippets.
Error messages like:
Creation of dynamic property GPECF_Discount_Amounts_By_Field_Value::$_args is deprecated
Creation of dynamic property GPEP_Edit_Entry::$process_feeds is deprecated
> `gpecf-set-discount-amount-by-field-value.php`: Fixed PHP 8.2 warnings.

- gp-nested-forms/gpnf-copy-parent-value-manually.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2670546355/69628
The `gpnf-copy-parent-value-manually.js` snippet doesn't work when the parent form source field is a Radio button field.
This PR would fix the issue.
> `gpnf-copy-parent-value-manually.js`: Fixed an issue where source field value is not copied over if it is a dropdown or radio button field.

- gp-easy-passthrough/gpep-edit-entry.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2692325023/70631
The GPEPT Edit Entry snippet doesn't update the total product fields on the backend.  The issue is that the cached product info is used to run the total calculation. The fix here is to purge the cache before the calculation.
> `gpep-edit-entry.php`: Fixed an issue where cached product info are used for total field calculation.

- gp-file-upload-pro/gpfup-require-camera.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2700871854/71092
When using the [Require Camera for Uploads snippet](https://gravitywiz.com/snippet-library/gpfup-require-camera/) and a restriction is set on a field (ex: jpg, png, pdf), Android phones will allow the user to select images from the camera roll, even though they shouldn't be allowed to. This is not the case with iPhones.
This seems more of like something because of a recent update for Chrome Android: https://stackoverflow.com/questions/77876374/html-input-type-file-not-working-to-pull-up-camera-for-pixel-android-14-comb
As a fix, we are adding the `accept` attribute can help restrict it to images from the camera.
**Loom walkthrough with demo of the fix (tested on a Pixel7 via browserstack):** …
> `gpfup-require-camera.js`: Fixed issue with some Android Phones.

- gs-product-configurator/gspc-hidden-product-handler.php
- gs-product-configurator/gspc-unlink-hidden-products-in-cart.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2695302163/70820
When a Woo product has a catalog visibility of hidden, the cart item still shows its product link. This snippet removes it.
**BEFORE:**
**AFTER:**
> `gspc-hidden-product-handler.php`: Added snippet to remove url for Hidden Catalog Products on Cart.

- gravity-forms/gw-none-of-the-above-checkbox.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2711484484/71608
Variable added at the top for specifying whether the "None of the Above" should be disabled - default to false which will change the default behavior of this snippet.
Loom Demonstration:
https://www.loom.com/share/a142a6a2a4da481b83d1d18937c12747
> `gw-none-of-the-above-checkbox.js`: Added setting to not disable None of the Above by default.

- gp-limit-dates/gpld-conditional-limits.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2690682399/70534
Added a new snippet to enable conditional date limits.
> `gpld-conditional-limits.php`: Added a new snippet to enable conditional date limits.

- gp-nested-forms/gpnf-map-child-entries-to-acf-repeater-field.php
- gp-notification-scheduler/gpns-payment-status-conditional-logic.php
- gp-populate-anything/gppa-acf-datepicker-comparison.php
- gravity-forms/gw-all-fields-template.php
- gravity-forms/gw-custom-validation.php
- gravity-forms/gw-require-unique-values.php
Fixing PHPCS issues in these files:
`gravity-forms/gw-all-fields-template.php`
`gp-nested-forms/gpnf-map-child-entries-to-acf-repeater-field.php`
`gp-notification-scheduler/gpns-payment-status-conditional-logic.php`
`gp-populate-anything/gppa-acf-datepicker-comparison.php`
`gravity-forms/gw-custom-validation.php`
`gravity-forms/gw-require-unique-values.php`
> Formatting: Fixed PHPCS issues.

- gp-limit-choices/gplc-gspc-compatibility.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2696647789/70877
Added new snippet to check validation again before an order is created.
> `gplc-gspc-compatibility.php`: Added new snippet to check validation before an order is created.

- gs-product-configurator/gspc-add-entry-data-to-woo-order-custom-field.php
⛑️ Ticket(s): [](https://secure.helpscout.net/conversation/2685171079/70219/)
This snippet will update a custom field on the Woo order with data from the attached GF entry, when the order is created.
For example, a customer collects a name in the GF entry, and needs to send this to ShipStation with the Woo order. ShipStation expects custom data to be stored in a specific custom field on the Woo order. This snippet will allow you to add the data from the entry into that custom field on the order.
> `gspc-add-entry-data-to-woo-order-custom-field.php`: Added new snippet.

- gp-populate-anything/gppa-lmt-extract-first-character.php
⛑️ Ticket(s): [](https://secure.helpscout.net/conversation/2671741596/69678/)
This snippet will return the first character of the string when using a Live Merge Tag.
For example, taking a Name field and extracting the first character of the name.
> `gppa-lmt-extract-first-character.php`: Added new snippet.

- gravity-forms/gw-progress-meter.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2711207909/71589
When the total paid count is calculated refunds are included, this PR will the issue by excluding refunds.
> `gw-progress-meter.php`: Fixed an issue where refunds are included in the total paid count.

- gravity-forms/gw-populate-date.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2721507824/72066
The [GW Populate Date](https://gravitywiz.com/snippet-library/gw-populate-date/) snippet is causing a deprecation warning for PHP 8.2:
**Deprecated: Using ${var} in strings is deprecated, use {$var} instead**
Relates to line 249 in the snippet:
`$date = "${hour}:${minute} ${ampm}";`
In PHP 8.2, the recommended way to use string interpolation with variables is to place the dollar sign inside the curly braces. Reference [link](https://www.php.net/manual/en/language.types.string.php#language.types.string.parsing.complex)
> `gw-populate-date`: Fixed PHP 8.2 deprecation notice.

- gp-entry-blocks/gpeb-process-feeds-on-edit.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2720318050/72019
Added the ability to exclude certain feeds from being processed by specifying their feed IDs.
> `gpeb-process-feeds-on-edit.php`: Added the ability to exclude certain feeds from being processed.

- gp-file-upload-pro/gpfup-enforce-exact-dimensions.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2720536211/72026/
💬 Slack: https://gravitywiz.slack.com/archives/GMP0ZMNSE/p1727779512582999
Snippet to force users to upload an image of a specific size. So if a user uploads a different-sized image, a validation error will be thrown.
Current GPFUP code logic only adds validation setting for min dimensions [here](https://github.com/gravitywiz/gp-file-upload-pro/blob/44623cfbe4c8ffaee8352f013baf8e92655df9b0/js/src/frontend/GPFUPField.ts#L522-L578)
We are going to use the filter for that and apply the exact settings.
Loom Demo:
https://www.loom.com/share/4b28e2dbdbbb4b399b7220d3d77d71f5
> `gpfup-enforce-exact-dimensions.js`: Added snippet to enforce exact dimensions on file upload.

- gp-inventory/gpi-waiting-list.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2729999524/72460
GP Inventory won't allow for conditional logic when available inventory is less than 0, with the waiting list snippet.
**BEFORE:**
https://www.loom.com/share/335c4889740e4e17acc2db6f922bd64f
**AFTER**:
https://www.loom.com/share/05e89df338944105a4acdc19fc3f39c2
> `gpi-waiting-list.php`: Fixed issue with conditional logic not working for negative stock.

- gp-unique-id/gpuid-dynamic-population.php
The current formatting displays the instructions strangely [in the snippet library](https://gravitywiz.com/snippet-library/gpuid-dynamic-population/).
> Formatting: Fixed instructions format.

- gc-openai/gcoai-stream-to-paragraph-field.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2741927048/73003
Formatting is lost when streaming OpenAI response to a paragraph field with rich text enabled
**Steps to Reproduce**
https://www.loom.com/share/29ced3302a1d4bff82c77deed4fabb54?sid=2caf0989-addf-4649-976f-592cdb72a474
1. Install GC OpenAI
2. Install [this snippet](https://gravitywiz.com/snippet-library/gcoai-stream-to-paragraph-field/) using [Code Chest](https://gravitywiz.com/gravity-forms-code-chest/)
3. Add paragraph field and enable rich text
4. Configure OpenAI stream field to expect rich text in a response
5. Generate text
> `gcoai-stream-to-paragraph-field.js`: Fixed an issue with stream to paragraph field not displaying rich text correctly.

- gravity-forms/gw-disable-submit-button-until-required-fields-are-filled-out.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2740666744/72953
The Disable Submit Button Until Required Fields Are Filled Out snippet is conflicting with GPPA, causing the form to break. Populated fields just pulse and don't update.
Matt A's loom explaining the issue:
https://www.loom.com/share/e98e2369db5a43278f5d2706612fad54
After the update (fix):
https://www.loom.com/share/76f4bf19d9554486bde1a39e74e97ea4
> `gw-disable-submit-button-until-required-fields-are-filled-out.php`: Fixed a compatibility issue with GP Populate Anything.

- gravity-forms/gw-capitilize-submitted-data.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2743721686/73093
Add support for list fields in the snippet.
An entry **before** list field capitalization:
An entry **after** list field capitalization:
> `gw-capitilize-submitted-data.php`: Added support to capitalize list fields.

- gp-inventory/gpi-enable-wpml-for-custom-messages.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2738886758/72893
Depends on https://github.com/gravitywiz/gp-inventory/pull/111
Added a new snippet to enable WPML String Translate for custom Insufficient, Exhausted and Available Inventory messages.
> `gpi-enable-wpml-for-custom-messages.php`: Added snippet to use WPML String Translate for custom GPI messages.

- gravity-forms/gw-all-fields-template.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2740162125/72932
💬 Slack: https://gravitywiz.slack.com/archives/C03T0CNL8AV/p1729715300828389
Adding support for an `:updated modifier` on the `{all_fields}` merge tag to our [All Fields Template](https://gravitywiz.com/gravity-forms-all-fields-template/) snippet/plugin. This modifier should only show fields that were most recently updated.
Update in action:
https://www.loom.com/share/852a5547ac7945f59158d44e769602b8
> `gw-all-fields-template.php`: Added `:updated` modifier for All Fields Template to display only the updated fields.

- gp-limit-submissions/gpls-use-entry-for-each-user-rule-message.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2730567828/72487
When the rule group is set `User` , this snippet will use the current user's latest entry to process the replace merge variable for the limit message.
> `gpls-use-entry-for-each-user-rule-message.php`: Added new snippet to use the current user entry to replace message merge tag variables.

- gravity-forms/gw-format-date-merge-tags.php
⛑️ https://secure.helpscout.net/conversation/2763010990/73925?folderId=8114575
Added `i18n` support for date format using the [`IntlDateFormatter`](https://www.php.net/manual/en/intldateformatter.format.php) This  `IntlDateFormatter` uses the ISO date [format](https://framework.zend.com/manual/1.12/en/zend.date.constants.html#zend.date.constants.selfdefinedformats) codes instead of PHP date format.
> `gw-format-date-merge-tags.php`: Added i18n date format support.

- gravity-forms/gw-cache-buster.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2755652844/73591
Fixed fatal error issue that is coming from the `get_default_theme` function.
> `gw-cache-buster.php`: Fixed fatal error from `get_default_theme` function.

- gravity-forms/gw-cache-buster.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2757816615/73709  https://secure.helpscout.net/conversation/2760713855/73809
Added support for GF Blocks.
> `gw-cache-buster.php`: Added support for Gravity Forms blocks.

- gravity-forms/gw-cache-buster.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2755652844/73591
When cache buster is enabled on a form, the `GPMPN`, the [custom starting page](https://gravitywiz.com/documentation/gravity-forms-multi-page-navigation/#custom-starting-page) is not applied to the form. This fix here is to use the `gpmpn_default_page` filter hook to pass in the custom page param.
> `gw-cache-buster.php`: Fixed GP Multi-Page Navigation compatibility issue where custom starting page is not applied.

- gp-ecommerce-fields/gpecf-set-discount-amount-by-field-value.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2768471028/74224
When using the snippet along with a calculated Number field, if the number is greater than 1000, and so includes a comma, only the digits in front of the comma are being copied to the Discount field.
**BEFORE:**
**AFTER:**
> `gpecf-set-discount-amount-by-field-value.php`: Fixed an issue with comma values in discount calculations.

- gc-airtable/gca-create-relation.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2768092049/74169?viewId=6987275 
Adds a snippet to demonstrate how to create a Relation in Airtable while processing a GC Airtable Feed.
Relies on: https://github.com/gravitywiz/gc-airtable/pull/4
> `gca-create-relation.php`: Added snippete demonstrating how to create a relation with GCA.

- experimental/gfcs-auto-chained-select.php
https://www.notion.so/gravitywiz/Gravity-Wiz-Gravity-Forms-Chained-Selects-Auto-Select-Only-Option-15200ab68edf80fc87b1d03d58823c4a?pvs=4
> `gfcs-auto-chained-select.php`: Migrated.

- gs-product-configurator/gspc-clear-stale-entries-on-load.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2762295831/73881
**GSPC**: Added a new snippet to clear stale entries on site load.
> `gspc-clear-stale-entries-on-load.php`: Added asnippet to clear stale entries on site load.

- gp-nested-forms/gpnf-detach-child-entry-from-parent.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2779018255/74896
Snippet to add a metabox to child entry detail views that, when clicked, will detach the child entry from the parent entry. 
Demo:
https://www.loom.com/share/84a6fc86c75449baa544cd8080c3ed15
> `gpnf-detach-child-entry-from-parent.php`: Added snippet to display a metabox on Entry details for nested entries to detach from Parent Entry.

- gp-populate-anything/gppa-force-dyn-pop-on-gv-edit.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2771470716/74423
and others
_Note from Samuel- "The [Force Dynamic Population When Editing via GravityView](https://gravitywiz.com/snippet-library/gppa-force-dyn-pop-on-gv-edit/) snippet is not working, but it appears you have a working version in your gist here: https://gist.github.com/saifsultanc/766625ff2122a82e48394d08074492ce"_
This minor edit was done quite a few months back, but wasn't merged here on Snippet Library. I think the issue was with the `$_this->entry` not having the updated field values. So instead of passing it, leave the parameter empty (null pass). The logic inside GPPA's `populate_field` will itself fetch the updated values. That's about it.
> `gppa-force-dyn-pop-on-gv-edit.php`: Fixed an issue with the snippet dynamic population.

- gp-unique-id/gpuid-fill-sequence-gaps.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2790631747/75478
The snippet does not seem to work, it hasn't been update in over 2 years. The DB we are accessing is `wp_rg_lead_detail`, but it seems GF 2.3+ it's expected that the `wp_gf_entry_meta` should be used instead. GF codebase for context: https://github.com/gravityforms/gravityforms/blob/master/export.php#L892-L910
So we just apply the DB update, and that fixes the issue.
Here is how it works after the update:
https://www.loom.com/share/1819b282338d4832a68ce985787b16bb
> `gpuid-fill-sequence-gaps.php`: Fixed an issue with the snippet not working.

- gravity-forms/gw-create-coupon.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2786023627/75268#thread-8459491127
This PR fix the coupon description not set in WooCommerce. Instead of `post_content`, we need to use `post_excerpt` to set the coupon description in WooCommerce.
> `gw-create-coupon.php`: Fixed WooCommerce coupon description not set issue.

- experimental/gppa-click-image-choice-image-wrapper.js
https://github.com/gravitywiz/gp-populate-anything/pull/578/files#r1890791270
💬 GF Issue reported: https://github.com/gravityforms/gravityforms/issues/3050
Reference: https://github.com/gravitywiz/gp-populate-anything/pull/578/files#r1890791270
Clicking the Image Wrapper does not trigger click on the image choices, this addresses that till Gravity Forms releases a patch for it natively.
> `gppa-click-image-choice-image-wrapper.js`: Added snippet to trigger dynamic populate on Image Choice's Wrapper getting clicked.

- gp-file-upload-pro/gpfup-limit-aspect-ratio-of-mp4-mov-files.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2768731176/74236
The ability to specify ratios for videos with GPFUP.
https://www.loom.com/share/b05a322bbf204e49b23ae366a123be96
> `gpfup-limit-aspect-ratio-of-mp4-mov-files.js`: Added snippet to limit Aspect Ratio of uploaded video files.

- gp-populate-anything/gppa-remove-empty-choices.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2804238036/75977
The snippet to remove choices, which is used in [this tutorial](https://gravitywiz.com/preferred-contact-method-gravity-forms/), isn't working as expected.
**BEFORE:**
https://www.loom.com/share/010f6586aa44455293a1cc6116f9a86c
**AFTER:**
https://www.loom.com/share/7826aadc3ccc4cddb2b36937a1f06319
> `gppa-remove-empty-choices.js`: Fixed an issue with empty choices not getting removed.

- gp-advanced-select/gpadvs-enable-add-new-option.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2806641061/76034
The functionality to Add New with the snippet above doesn't work if no result is populated into the field.
BEFORE (Samuel):
https://www.loom.com/share/fc8ada4515724f3e8a76294da9910c33?sid=c12dbaf0-3a19-4265-b7a5-4435ac2f8e71
AFTER:
https://www.loom.com/share/fc15e97fed40415899d55be5fc84339e
> `gpadvs-enable-add-new-option.php`: Added ability to add new options when "No Results" are returned from Populate Anything.

- gravity-forms/gw-validate-that-a-value-exists.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2810746176/76183
The snippet throws an error on the console
When declaring the script on `load_form_script`, we just need to ensure that its registered on the footer and not directly invoked (like [here](https://github.com/gravitywiz/snippet-library/blob/master/gw-snippet-template.php#L86))
This wasn't evident with GF 2.8 and prior. GF 2.9 updated exposed that issue.
> `gw-validate-that-a-value-exists.php`: Fixed an issue with script not working with value validation snippet.

- gp-limit-checkboxes/gplcb-conditional-limits.php
- gravity-forms/gw-coupons-exclude-products.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2811485469/76267
Same issue as https://github.com/gravitywiz/snippet-library/pull/979
> `gplcb-conditional-limits.php`: Fixed an issue with script generating console errors.

- gp-nested-forms/gpnf-delay-child-notifications-for-parent-payment.php
This PR allows to send notification instantly even if parent entry doesn't have payment status.
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2794049850/75576
Delay notification only checks for the payment status of parent entry `Paid` & `Active`. But, it doesn't send notification if there is no payment status for the parent entry.
So, this fix checks whether the payment status is available or not. If not, it allows to send notification.
> `gpnf-delay-child-notifications-for-parent-payment.php`: Added send notification if no payment status for parent entry.

- gp-populate-anything/gppa-gpeb-force-rehydration-on-edit.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2810857077/76190
https://gravitywiz.com/snippet-library/gppa-gpeb-force-rehydration-on-edit/
The snippet above to rehydrate populate fields when editing an entry via GPEB is no longer working.
Here's a video demo of the issue (Samuel): https://www.loom.com/share/21999b9a22ac4255aa76555a82bb5aac?sid=d9d2c107-da16-43dd-98ad-342f5804091d
Fix similar to https://github.com/gravitywiz/snippet-library/pull/935
> `gppa-gpeb-force-rehydration-on-edit.php`: Fixed issue with rehydration not working when editing entries with GP Entry Blocks.

- gp-nested-forms/gpnf-child-products-in-parent-order-summary.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2807549547/76063
Include Child Products Directly in Parent Form Order Summary after combining identical products into single lines on the order summary.
Matt A's loom:
https://www.loom.com/share/14394db590894d0b937e4d546067f4a6
After update, similar products of two nested will be merged like this on the order summary-
> `gpnf-child-products-in-parent-order-summary.php`: Added support for merging child products in parent order summary.

- gp-nested-forms/gpnf-export-child-field-header.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2429207246/57777
With the introduction of input-specific export columns in https://github.com/gravitywiz/gp-nested-forms/pull/57, this snippet must be updated to account for this new scenario.
> `gpnf-export-child-field-header.php`: Updated to add support for handling input-specific column headers.

- gravity-forms/gw-gravity-forms-filter-out-zero-dollar-products.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2408973399/56781/
Updated snippet to prevent the removal of $0 products that contained non-$0 options.
All products removed. 😆
> Fixed issue where zero-dollar products that had none-zero-dollar options were removed.

- gp-populate-anything/gppa-use-choice-labels-when-populating-from-another-field.php
- gravity-forms/gw-round-robin.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2164237011/44637/
Customer wanted support for skipping conditionally hidden Round Robin fields. They had figured out how to skip the hidden field but the Round Robin sequence would restart on the next submission where the Round Robin field was not hidden.
This PR refactors their code and adds support for ensuring the Round Robin sequence is preserved when working with conditional fields.
> Added support for skipping conditionally hidden Round Robin fields.

- gp-copy-cat/gpcc-list-rows-as-new-lines.js
We had a customer in the comment section who was getting an error message because they added the snippet as PHP instead of Javascript.
https://gravitywiz.com/gravity-wiz-weekly-155/comment-page-1/#comment-827773
Added the instruction on how to add the Javascript snippet to the form.
> Added Instructions

- experimental/gpafp-replace-space-separator.php
This snippet replaces the space separator when using the phone[nationalNumberFormatted] modifier.
Ticket: https://secure.helpscout.net/conversation/2164492172/44662?folderId=3775888
> `gpafp-replace-space-separator.php`: Added a new snippet to replace the space separator.

- gp-populate-anything/gppa-populate-from-multiple-forms.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/1992124058/38187?folderId=14964
The snippet wasn't setting the value property of the choice-based field when populated. When a multi-select field is used, it displays the value property of the field on the entry page, and because the value property hasn't been set by the snippet it displays the entry ID. Added a line of code to also set the value.
> Updated the snippet to also set the value property

- gp-populate-anything/gppa-acf-repeater-mapper.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2576524151/65219/
When using the [GPPA ACF Repeater Mapper](https://github.com/gravitywiz/snippet-library/blob/4bfeb339090e89416c52ea20464a1ff872ae7729/gp-populate-anything/gppa-acf-repeater-mapper.php) snippet, static values set in the Choice Template are ignored.
> `gppa-acf-repeater-mapper.php`: Added support for custom values with ACF field property template.

- gp-notification-scheduler/gpns-add-other-fields-to-date-schedule.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2115235612/42388?folderId=7098280
Add a field other than the Date field to the Notification Scheduler. In this instance, a "Single Line Text Field" was used.
> `gpns-add-other-fields-to-date-schedule.php`: Added other fields to the GP Notification Scheduler.

- gravityforms-openai/gf-openai-post-save-result-to-field.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2190755593/45844?folderId=7098280
Add support to populate fields with Open AI generated values.
> `gf-openai-post-save-result-to-field.php`: Added snippet to populate fields with Open AI generated values.

- gravity-forms/gw-double-confirmation-fields.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2214432238/46871?folderId=3808239
Added custom validation message to this snippet. This can be used as follows:
```
register_confirmation_fields( 404, array( 3, 4 ), "Please compare the values." );
register_confirmation_fields( 406, array( 1, 3 ), "Please correct these values" );
register_confirmation_fields( 406, array( 4, 5 ), "These should also match" );
```
Here is a quick screencast of the update: https://www.loom.com/share/ad511b6c0abf47d4a86b7965446a5889
> `gw-double-confirmation-fields.php`: Updated snippet to use custom validation message.

- gravity-forms/gw-preserve-datepicker-date-selection-when-changing-months.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2725332347/72239
Issues with edge cases. For instance, if we had the selection as 31 October and then we chose the month of April. Since it cannot select 31st April, it is going to end up selection as 1st of May (outside our month selection of April). Likewise, 30 April and then selecting February would select 2nd March (for non-leap) and 1st March (for leap year). All these edge cases have been handled with a `maxDay`, so any date selection is capped to that max value.
**BEFORE:**
https://www.loom.com/share/cdf3a97e31684d3899311a24c6aeb6f6
**AFTER:**
https://www.loom.com/share/45ad6bb1f061409195bbc20910846c3e
> `gw-preserve-datepicker-date-selection-when-changing-months.js`: Fixed an issue with edge cases like 29 February, 31 April etc.

- gp-conditional-pricing/gpcp-product-pricing-labels.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2816007580/76520
Snippet is incorrectly handling values containing non-zero values after the comma for prices in Euros.
**Steps to reproduce:**
1. Steps to Reproduce
2. Set default currency in Gravity Forms to Euros.
3. Create a basic form (I included my export).
4. Add a product field. Set field type to drop down.
5. Add demo choices with varying prices. Make sure to include some that have nonzero numbers after the comma (e.g. 7,50)
6. Add this JS [snippet](https://gravitywiz.com/snippet-library/gpcp-product-pricing-labels-2/). Needs this [PHP counterpart](https://gravitywiz.com/snippet-library/gpcp-product-pricing-labels/)
7. Preview form
**FORM SETUP:**
**BEFORE**:
**AFTER**:
The snippet uses the Gravity Forms method …
> `gpcp-product-pricing-labels.js`: Fixed an issue with decimal comma prices.

- gravity-forms/gw-all-fields-template.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2460908266/59240?folderId=3808239
The All Fields Template is causing a fatal error:
`Warning: Undefined variable $input_ids in /.../gw-all-fields-template/gw-all-fields-template.php on line 201`
The issue is down to the `$input_ids` only getting initialized in the preceding else block (and not the if). This leads to potential scenarios of tapping in on that value/variable even though it does not exist.
**BEFORE:**
**AFTER:**
> `gw-all-fields-template.php`: Fixed a fatal error with the snippet and Nested Forms.

- gravity-forms/gw-zip-files.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2331036263/53520/
The  [Zip Files](https://github.com/gravitywiz/snippet-library/blob/master/gravity-forms/gw-zip-files.php) snippet to generate a zip of all uploaded files from the submitted entry does not support merge tags. This update adds support for it.
Update in action (~30 seconds):
https://www.loom.com/share/63ad5a18b0d74c52a101edd91f75f976
> `gw-zip-files.php`: Updated snippet to add support for merge tags in zip files.

- gravity-forms/gw-submission-limit.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2819966166/76685
This snippet causes a following fatal error just by adding it to the website.
`Fatal error: Cannot redeclare GW_Submission_Limit::$_args`
This PR fixes this issue.
> `gw-submission-limit.php`: Fixed fatal error: `Cannot redeclare GW_Submission_Limit::$_args`.

- gp-populate-anything/gppa-post-meta-datepicker-comparison.php
https://www.notion.so/gravitywiz/Deprecate-Post-meta-date-comparison-snippet-16000ab68edf80acb3e1cfbf75952021?pvs=4
The functionality of this snippet is now possible without the snippet.
> `gppa-post-meta-datepicker-comparison.php`: Added "Deprecated" message.

- gravity-forms/gw-populate-date.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2819440177/76669
The "Populate Date" snippet is not working with the Radio field as the input field, but it functions correctly with the Number and Dropdown fields. Need to add separate logic to get exact value from the selected choice in the targetted `gfield_radio`.
> `gw-populate-date.php`: Fixed an issue with Radio Button used as Modifier with Populate Date Snippet.

- gravity-forms/gw-choice-counter.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2801436161/75906
[Choice Counter snippet](https://github.com/gravitywiz/snippet-library/blob/master/gravity-forms/gw-choice-counter.php), and this is bizarrely counting the unselected choice.
Loom:
https://www.loom.com/share/2cbd1299f83c4d218602b29a3995c75e
> `gw-choice-counter.php`: Fixed an issue with the choice counter counting disabled checkboxes.

- gravity-forms/gw-limit-columns-in-survey-field-to-single-selection.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2816944674/76575
To limit the selection to only one choice per column in his Likert (Survey) field.
> `gw-limit-columns-in-survey-field-to-single-selection.js`: Added snippet to limit columns in survey field to single selections.

- gp-limit-dates/gpld-conditional-limits.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2819363473/76665
This snippet works only if the `Minimum Date` or `Maximum Date` field is set in the GP Limit Dates perk.
The issue arises when neither date is set, as the `gp-limit-dates` JavaScript is not enqueued, causing it to not function.
To resolve this, add the following filter to ensure the JavaScript is enqueued for the form and field.
> `gpld-conditional-limits.php`: Fixed issue where GP Limit Dates' frontend assets were not being enqueued when using snippet.

- gravity-forms/gw-limit-columns-in-survey-field-to-single-selection.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2816944674/76575
The snippet wasn't working for the Gravity Forms 2.5 Theme. It was working, just the `gsurvey-likert-selected` CSS class was no there. I don't know my local backup was messed up and it wasn't showing GF 2.5 Theme correctly, as @mcglenn07 pointed out. Thanks to him!
> `gw-limit-columns-in-survey-field-to-single-selection.js`: Fixed issue with snippet not working with GF2.5 theme.

- gravity-forms/gw-cache-buster.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2827184964/77017
When using Cache Buster with a form that has a schedule, if the form is expired, the following PHP warning is being thrown, and the form expiration message does not show:
`PHP Warning:  Undefined array key "page_number" in ...\plugins\gravityforms\form_display.php on line 727`
As Gravity Forms does it [here](https://github.com/gravityforms/gravityforms/blob/master/includes/api.php#L1800) to check for form expiration, we have added the logic on the required spot at Cache Buster. Since, an expired form won't have a page number set.
```php
$form_restriction_error = rgars( GFFormDisplay::$submission, $form_id . '/form_restriction_error' );
```
**Post Update:**
> `gw-cache-buster.php`: Fixed an issue with Cache Buster and Expired Forms.

- gp-multi-page-navigation/gpmpn-dropdown-navigation.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2825118959/76919
Provide variable at the top of the snippet that will be used as an option name template. Include a merge tag for the page number and page name.
`const pageNameTemplate = 'Step {pageNumber}: {pageName}';`
The steps in dropdown will follow this template. Like so -
> `gpmpn-dropdown-navigation.js`: Added page names in dropdown navigation.

- gp-populate-anything/gppa-acf-date-formatter.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2826054984/76967
Similar ticket: https://secure.helpscout.net/conversation/2601997622/66482
While using ACF & [this snippet](https://gravitywiz.com/snippet-library/gppa-acf-date-formatter/) together resulting in a one-day discrepancy. 
This issue was related to timezone. 
Here's the customers screencast explains this issue.
https://video.tsttechnology.com/conversations/cf879d60-9004-5cec-99c4-0d8fde4dba88
> `gppa-acf-date-formatter.php`: Fixed date formatting issue caused by timezone offset resulting in a one-day discrepancy.

- gp-qr-code/gpqr-play-beep-on-scan.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2830602037/77180
A solution to play a sound when a QR code is scanned.
Instruction Video: https://www.loom.com/share/7f413231517b423eba3ccc1bf3055b40
> `gpqr-play-beep-on-scan.js`: Added snippet to play beep sound on successful QR Code scan.

- gp-nested-forms/gpnf-gv-duplicate-child-entries.php
https://secure.helpscout.net/conversation/2835085683/77419?viewId=14964
The snippet was migrated to a new location, but the URL provided was incorrect. The correct URL has been added.
> `gpnf-gv-duplicate-child-entries.php`: Fixed URL in the snippet header.

- gravity-forms/gw-min-and-max-character-limit.php
- gravity-forms/gw-round-robin.php
⛑️ Ticket(s): https://secure.helpscout.net/link/to/conversation
📓 Notion: https://notion.so/link/to/card
💬 Slack: https://slack.com/link/to/thread-or-message
i18n is crucial when developing WP plugins :). This fix provides a better character count. As simple as it is, a form submission could be prevented because of incorrect validation, which might lead to e.g. loss of sale or lead.
> Fix character count with the better mb_strlen

- gravity-forms/gw-delay-feed-till-user-registration.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2826984822/77005
The user had a registration form that has a GF User Registration feed and Notion feed. They want to send the user ID of the account that is created when the form is submitted to Notion. Currently, it appears the notion feed is processed before the account is created, so it doesn't get the user ID. They are looking for a way to delay the Notion feed until the account is created, and the user ID is assigned to the entry created by property.
The snippet added makes it extensible to other combination with the User Registration feed, by just specifying a different addon slug (like gc-openai or any other).
Instruction Video:
https://www.loom.com/share/176456848c614ab6a3792ca1f9ed9c14
> `gw-delay-feed-till-user-registration.php`: Added snippet to delay a feed until the User Registration feed had its user activated.

- gravity-forms/gw-cache-buster.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2840306289/77678
Cache Buster is causing fatal error when the following filter is used with GF Gutenberg Blocks.
`add_filter( 'gfcb_enable_cache_buster', '__return_true' );`
Following fatal error occurs:
`PHP Fatal error:  Uncaught TypeError: json_decode(): Argument #1 ($json) must be of type string, array given in ...`
Add an additional check to the logic to ensure `json_decode` is not processed on a value that is already correctly set in the `array` form. For further context, here is a debug snapshot of the values at this code line on a simple gravity forms block:
> `gw-cache-buster.php`: Fixed an issue with Cache Buster plugin causing fatal error.

- gc-notion/gcn-radio-button-to-date-property-mapping.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2791555192/75505?viewId=6987275 
Adds a snippet showing how to map a radio button to a Notion Date property.
> `gcn-radio-button-to-date-property-mapping.php`: Added snippet to map radio fields to Notion Date properties.

- gravity-forms/gw-add-attachments-by-field.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2850770125/78183
Ability to specify multiple Upload field IDs. Currently, it only accepts one field ID.
**Sample form with 3 file upload fields:**
**Snippet set to upload 2 out of those 3 fields:**
**Notification sent with only the two target file uploads sent:**
> `gw-add-attachments-by-field.php`: Added multiple fields option for the snippet.

- gp-address-autocomplete/gpaa-single-line-as-input.php
Added instructions on how to use the snippet for multiple address fields.
The configuration block can be added multiple times to support adding multiple address fields in the same form or over different forms.  There was a question about it in the loom video.
> Update gpaa-single-line-as-input.php with instructions on using multiple address fields

- gp-populate-anything/gppa-use-acf-choice-label.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2846332119/77984
User is attempting to grab the Label of an ACF field using this snippet: https://gravitywiz.com/snippet-library/gppa-use-acf-choice-label/.
This works as intended when the ACF field's return value is set to `label`, but their field is set to `Both (Array)`, so the following error is being thrown.
`Uncaught Error: str_contains(): Argument #1 ($haystack) must be of type string, array given
in /wp-includes/blocks.php on line 1817`
This PR fixes this fatal error.
> `gppa-use-acf-choice-label.php`: Fixed PHP fatal error when ACF field set return value as return `Both (array)`.

- gravity-forms/gw-entry-count-shortcode-advanced.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2857827771/78525
Customer wanted the ability to filter entries where a given combination of fields had specific values. To support this (and more use cases in the future), I've added support for a `field_filters` and `field_filters_mode` attribute which map directly to GFAPI::get_entries() `field_filters` parameter.
See the updated snippet header for instructions on how to use these attributes.
> Added support for filtering by multiple field values (via `field_filters` and `field_filters_mode` attributes).

- gravity-forms/gw-all-fields-template.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2849211669/78114
Added filter similar to GPNF's template filter [here](https://github.com/gravitywiz/gp-nested-forms/blob/4eb7aa27ff841ee43882b758b8704c48d8f1233c/includes/class-gp-template.php#L187).
This filter could be utilized as follows:
```php
add_filter( 'gwaft_template_output', function( $content, $slug, $name, $data, $suffixes ) {
// Modify the content as needed.
if ( in_array( 'collapsible', $suffixes ) ) {
$content .= 'whatever we like';
}
return $content;
}, 10, 5 );
```
> `gw-all-fields-template.php`: Added filter to customize template content.

- gravity-forms/gw-populate-date.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2851510985/78218
In all other cases, if no source_field_id is defined, Populate Date defaults to today. But if a field-based modifier is used, it doesn't do this and the snippet just doesn't work.
So this works, to populate today +1 day:
```
new GW_Populate_Date( array(
'form_id'         => 39,
'target_field_id' => 6,
'modifier'        => '+1 day'
) );
```
But this doesn't work to populate today +n days:
```
new GW_Populate_Date( array(
'form_id'         => 1895,
'target_field_id' => 2,
'modifier'        => array(
'type'     => 'field',
'inputId'  => 3,
'modifier' => '+{0} days',
),
) );
```
This update ensures the fix. Loom: https://www.loom.com/share/7980b5df520848b2a76a278960407789
> `gw-populate-date.php`: Added support for date population when source field ID wasn't provided.

- gp-nested-forms/gpnf-limit-entry-min-max-from-field-usage.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2859609766/78584
📓 Ticket Thread Reference: https://secure.helpscout.net/conversation/2859609766/78584#thread-8676640964
Deprecated this snippet as initialising of `GP_Nested_Forms_Dynamic_Entry_Min_Max` is now available in `gpnf-limit-entry-min-max-from-field.php` snippet.
> `gpnf-limit-entry-min-max-from-field-usage.php`: Deprecated snippet as functionality is now in `gpnf-limit-entry-min-max-from-field.php` snippet.

- gp-populate-anything/gppa-replace-field-with-spinner-instead-of-pulsing.js
Just something I noticed.
See PR title.
> `gppa-replace-field-with-spinner-instead-of-pulsing.js`: Fixed URL in the header.

- gp-entry-blocks/gpeb-remove-fields-on-edit.php
Just something I noticed.
The snippet was incorrectly titled "Set Fields as Readonly On Edit", this PR renames it to "Remove Fields On Edit".
> `gpeb-remove-fields-on-edit.php`: Fixed incorrect title in the header.

- gp-nested-forms/gpnf-gflow-auto-attach-child-entries.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2834613157/77386
A new child form entry that is added within a GravityFlow update input workflow is not auto-attached to the parent form until the parent form is submitted.
Similar to GravityView: https://gravitywiz.com/snippet-library/gpnf-gv-auto-attach-child-entries/
Loom: https://www.loom.com/share/44434c1fc8b346e1bcbcac3240e629cd
> `gpnf-gflow-auto-attach-child-entries.php`: Added snippet to Auto-attach Child Entries to Parent when Editing via Gravity Flow.

- gravity-forms/gw-coupons-exclude-products.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2856409848/78480
Updating the snippet so it is possible to exclude product Option fields from a coupon.
For example, the customer has a Product field with a price of $100, and an Option field (attached to the Product field) with a price of $10. If the user applied a 100% coupon, this should not apply to the Option field, so the form total should be $10.
Loom:
https://www.loom.com/share/1149b9eed4d74afbac8d94c5ae2a9e0a
> `gw-coupons-exclude-products.php`: Added functionality to exclude discounts on options of a product field.

- gravity-forms/gw-choice-counter.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2866195352/78865
The snippet above is used to get the number of selected choices in a multi-choice field. It works, but it appears it doesn't properly trigger the change event, which also doesn't update the form total.
Fix to ensure the change event triggers properly. This would include native event listeners and Gravity Forms logic.
**BEFORE:**
https://www.loom.com/share/53434d41b639452f8162cb6f1c33fe4e
**AFTER:**
https://www.loom.com/share/3ff480ee39254a3f895d785945b79cef
> `gw-choice-counter.php`: Fixed Choice Counter not triggering quantity updates.

- gravity-forms/gwaft-template-collapsible.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2849211669/78114
The collapsible templates snippet does not work because the values of `$page_groups` and `$pages` are an "index" behind. 
Adjustment for the index issue, and adding a field visibility check.
**BEFORE** Customer described issue (was also reproduced locally with a simple form):
https://app.screencast.com/wVMGdfNrt8gY2
**AFTER** the snippet update:
https://www.loom.com/share/457a4df1ae314b92a54e5f18b3e7ad71
> `gwaft-template-collapsible.php`: Fixed an issue with page numbers and hidden fields.

- gravity-forms/gw-min-and-max-character-limit.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2867998139/78938
Min Max character limit validation make sense when the field has a value. If we want to make sure field has a value, that can be handled through field `Required` rules. 
So, this we can do min max character limit validation only for the filed that has a value.
> `gw-min-and-max-character-limit.php`: Added support to run validation only when the field has a value.

- gravity-forms/gw-entry-count-shortcode-advanced.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2857827771/78525
This PR supports merge tags in the `field_filters` attribute. That means the following shortcode will work as expected.
`[gravityforms action="entry_count" id="21" field_filters="31:is:{user:user_login},29:is:"]`
> `gw-entry-count-shortcode-advanced.php`: Added support for merge tags in field filters.

- gp-entry-blocks/gpeb-process-feeds-on-edit.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2878525752/79569
The snippet is supposed to process feeds on a form when the entry is updated via GPEB, however, it's causing a critical error. Fixed the issue by adding a safety check.
> `gpeb-process-feeds-on-edit.php`: Fixed an issue with the snippet causing fatal error.

- gp-advanced-select/gpadvs-clear-button.js
- gp-advanced-select/gpadvs-dropdown-remove-button.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2861069601/78654?viewId=6987275 
Adds the "remove button" plugin for Dropdown fields.
> `gpadvs-dropdown-remove-button.js`: Added snippet to show remove button on Dropdown fields.

- gc-openai/gcoai-stream-to-paragraph-field.js
⛑️ Ticket(s): [https://secure.helpscout.net/conversation/2853989407/78340?viewId=8172236](https://secure.helpscout.net/conversation/2853989407/78340?viewId=8172236)
If the Response field is set to a plain text Paragraph field and there are rich text enabled Paragraph fields elsewhere on the form, the `gcoai-stream-to-paragraph-field` snippet fails to copy OpenAI's output to the Response field. This happens because the code checks if TinyMCE is globally available, not whether the specific Response field has TinyMCE enabled.
This PR fixes this by modifying the TinyMCE detection to specifically check if the target Response field has TinyMCE enabled, rather than just checking if TinyMCE exists globally.
Additionally, this PR removes duplicate code at the end of the snippet.
> `gcoai-stream-to-paragraph-field.js`: Fixed duplicate code and an issue with snippet not working.

- gp-terms-of-service/gptos-terms-only-modifier.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2876696517/79496
https://gravitywiz.slack.com/archives/GMP0ZMNSE/p1741974702635409
Added a `:terms_only` merge tag modifier that would allow you to display the terms in notifications or confirmations without also having to display the value /text of the checkbox.
https://www.loom.com/share/d69c48bea2d1429ab019310d2bc6c1e6
> `gptos-terms-only-modifier.php`: Added snippet to only display terms with the TOS checkbox.

- gp-nested-forms/gpnf-override-parent-merge-tag-on-submission.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2849364535/78123
Related PR: https://github.com/gravitywiz/gp-file-renamer/pull/22
The customer has a nested form with an Upload field. They are using the `{Parent}` merge tag in a field, and then using this in GPFR to name the uploaded file, based on a value in the parent form.
However, they want it so if the user changes the value on the parent form before submitting, the uploaded file is renamed.
> `gpnf-override-parent-merge-tag-on-submission.php`: Added support to rename uploaded files in child entries.

- gravity-forms/gw-rich-text-html-fields.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2882543004/79740
This PR will allow switching to text & visual mode in editor.
> `gw-rich-text-html-fields.php`: Added support to switch between visual and text mode.

- gravity-forms/gw-field-to-field-conditional-logic.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2885654688/79887
When using the [Field to Field Conditional Logic snippet](https://github.com/gravitywiz/snippet-library/blob/master/gravity-forms/gw-field-to-field-conditional-logic.php), if a numeric field value has thousand separators, the conditional logic works on the frontend form, but fails on submission.
Matt A's loom:
https://www.loom.com/share/c2f1e00a73044c2fb4121c9e822b550e
Loom describing the fix and quick walkthrough:
https://www.loom.com/share/dc56e01f090d4a2c81c50e7fe589f400
> `gw-field-to-field-conditional-logic.php`: Fixed an issue with numeric comparison in field to field conditional logic.

- gp-easy-passthrough/gpep-update-other-form-entry-by-ep-token.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2883160941/79774
This snippet previously used `GFAPI::update_entry_field()`, which updated a specific field but did not trigger post-entry update actions. Now, it has been updated to use `GFAPI::update_entry`, ensuring that post-entry update actions are triggered and subsequent actions are performed as expected.
> `gpep-update-other-form-entry-by-ep-token.php`: Improved snippet to support post entry update actions.

- gp-nested-forms/gpnf-sort-nested-form-entries.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2876515303/79476
This snippet uses `gpnf_sorted_entries` JS filter to sort nested form entries in frontend.
> `gpnf-sort-nested-form-entries.js`: Added support to sort nested form entries.

- gp-nested-forms/gpnf-limit-entry-min-max-from-field.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2897379455/81715
When using the [Dynamically Set Entry Min/Max From Field Value](https://gravitywiz.com/snippet-library/gpnf-limit-entry-min-max-from-field/) snippet, the Nested Form shows "maximum number reached" before any child entry is even added.
The key issue was default-ing to a zero max value.
> `gpnf-limit-entry-min-max-from-field.php`: Fixed an issue with the snippet not working correctly on form load.

- gravity-forms/gwaft-template-collapsible.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2872221797/79232
When using the [all fields collapsible sections](https://github.com/gravitywiz/snippet-library/blob/master/gravity-forms/gwaft-template-collapsible.php) snippet, if there is a pricing field on the form, the order summary is included in its own section. However, this also causes the page names to be showing incorrectly on the sections, and the section the order summary is included in does not have a title.
Matt A's loom explaining the issue:
https://www.loom.com/share/48c97b4b77054d36ab5c64973bd8ea84
Handle the "Order Summary" page has been proposed with this PR.
How this update works:
https://www.loom.com/share/728fc541438d4041a8e8e91ceee87e58
> `gwaft-template-collapsible.php`: Added Order Summary as an additional last page.

- gp-copy-cat/gpcc-copy-to-conditionally-hidden-fields.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2893866689/81562
The snippet above to Copy Values for Conditionally Hidden Fields doesn't support conditional copy cat.
Demo of the issue (Samuel):
https://www.loom.com/share/a49b8943c29e4955a807135bd7df24f9
Demo of the fix:
https://www.loom.com/share/43be9c8dbb8740448fd3102b8fb995a5
> `gpcc-copy-to-conditionally-hidden-fields.php`: Fixed an issue with copying value with multi input field triggers.

- gp-populate-anything/gppa-use-choice-value-instead-of-label.php
📓 Notion: https://www.notion.so/gravitywiz/Doc-Update-GPPA-How-to-display-choice-values-instead-of-labels-when-viewing-an-entry-1af00ab68edf819d9673d7c674855483?pvs=4
This snippet shows field values rather than labels on GPPA enabled fields when viewing an entry in the backend.
> `gppa-use-choice-value-instead-of-label.php`: Added new snippet.

- gp-inventory/gpi-enable-wpml-for-custom-messages.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2892903236/81524?viewId=14964
Added usage instructions as it wasn't clear how to get the strings into WPML once the snippet was installed.
> `gpi-enable-wpml-for-custom-messages.php`: Added usage instructions.

- gp-nested-forms/gpnf-set-created-by-property-on-child-entries-after-user-registration.php
Update request from support.
Glenn reported typo: "Propery" ➡️ "Property"
> `gpnf-set-created-by-property-on-child-entries-after-user-registration.php`: Fixed typo in the header.

- gp-populate-anything/gppa-acf-repeater-mapper.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2904943955/82068
This PR added support for `Image Choice` field in GPPA ACF Repeater Mapper snippet.
> `gppa-acf-repeater-mapper.php`: Added `Image Choice` field support in acf repeater mapper.

- gp-easy-passthrough/gpep-passthrough-consent-field.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2906273408/82137
Added support for passthrough with Consent field, which is delisted from mapping on GPEP here: https://github.com/gravitywiz/gp-easy-passthrough/pull/62
How this snippet works:
https://www.loom.com/share/209126dc84ab483b9025c040f5adf450
> `gpep-passthrough-consent-field.php`: Added snippet for easy passthrough on Consent Field.

- gp-file-upload-pro/gpfup-update-filename-markup.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2736841634/72809
💬 Slack: https://gravitywiz.slack.com/archives/C03T0CNL8AV/p1742222792311989
This snippet will help update the filename markup of uploaded files through GP File Upload PRO.
> `gpfup-update-filename-markup.php`: Added new snippet.

- gravity-forms/gw-merge-tag-modifier-remove-spaces.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2909059270/82229?viewId=14960
Adds a merge tag modifier to remove spaces from a value.
> `gw-merge-tag-modifier-remove-spaces.php`: Added new snippet.

- gp-qr-code/gpqr-add-support-for-camera-zoom.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2905448332/82090
Reference: https://github.com/gravitywiz/gp-qr-code/pull/30#issuecomment-2825270328
By default, disable camera zoom during QR code scanning. This snippet helps you enable camera zoom during QR code scanning.
> `gpqr-add-support-for-camera-zoom.js`: Added support for camera zoom during QR code scanning.

- gravity-forms/gw-choice-counter.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2917523082/82535
The Choice Counter is not working with Image Choice Field. The count is 1 off; you select two, it shows 1. You select 3 it'll show 2.
This update addresses an off-by-one issue when counting selected options in Gravity Forms' Image Choice fields. The problem occurs because clicking on an image triggers a click on the associated label, which then toggles the underlying checkbox. However, the checkbox state wasn't immediately updated at the time of the event, so there was a slight delay before the DOM reflected the change.
Previously, the count was being calculated immediately on click, which sometimes captured the state before the checkbox had updated, leading to inaccurate totals.
**BEFORE:**
**AFTER:**
> `gw-choice-counter.php`: Fixed an issue with Choice Counter not working for Image Choice field.

- gp-auto-list-field/gpalf-count-only-non-blank-rows.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2916143012/82450
By default, GP Auto List Field calculates the all rows (including blank rows) when we use `:count` modifier. This snippet is useful when you want to count only non-blank rows.
> `gpalf-count-only-non-blank-rows.js`: Added support to calculate only non-blank rows in a list field.

- gravity-forms/gw-conditional-logic-operator-does-not-contain.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2901482497/81913
Snippet that adds 'does not contain' operator for conditional logic comparison
Inspired from https://gravitywiz.com/snippet-library/gw-conditional-logic-operator-is-in/
Loom Demo: 
https://www.loom.com/share/8e1b27ec47b341dbb4f0da2bec6a960b
> `gw-conditional-logic-operator-does-not-contain.php`: Added snippet for does not contain conditional logic comparison.

- gp-nested-forms/gpnf-limit-entry-min-max-from-field.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2900858881/81887
The snippet to set the min/max of nested form entries is generating errors in the browser console and affecting the Nested Forms field.
https://www.loom.com/share/4f8c17e6082a4b1f9f29ce1f61d296f0?sid=cb9a84fa-2b25-4c62-b6b9-3d76a9377702
This PR updates the logic for triggering Knockout reactivity when the max value field is changed in a GPNestedForms context.
Currently, we have `.valueHasMutated()` on the entries observable to force recalculation when max field value is changed. However, in some scenarios, entries is a computed observable (not writable) and does not support `.valueHasMutated()`, leading to a console error. This update adds a fallback by reassigning a shallow clone of entriesRaw() to itself.
> `gpnf-limit-entry-min-max-from-field.php`: Fixed an issue with entry min max recalculation logic not working.

- gp-populate-anything/gppa-colorpicker-choice-template.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2908760149/82217
Jetsloth Gravity Forms Color Picker doesn't work on a dynamically populated field. Add support for using Jetsloth Gravity Forms Color Picker on a GPPA populated field
Loom (Samuel):
https://www.loom.com/share/072f38457d3347bbac3c4771bb3b883e
We have added support it. How it looks after snippet added:
https://www.loom.com/share/c062a781a86242de9f1ebb92492a408c
> `gppa-colorpicker-choice-template.php`: Added Color Picker choice template for GPPA to work with Jet Sloth Color Picker plugin.

- gravity-forms/gw-advanced-merge-tags.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2893613491/81558
Added support for a `:selected` modifier that would let you target the selected multi select choice by its zero-based index in our [Advanced Merge Tags](https://gravitywiz.com/snippet-library/gw-advanced-merge-tags/) snippet.
David's loom:
https://www.loom.com/share/a0f523d97c964e698c7d8b0ee56e2da2
All the documentation we have on the :selected modifier:
https://gravitywiz.com/gravity-wiz-weekly-233/#h-advanced-merge-tags-target-selected-checkboxes
After the update:
https://www.loom.com/share/02471d2ea98d456c8f0a2a41af4da937
> `gw-advanced-merge-tags.php`: Added `:selected` modifier to target selected multi select choice by index on the Advanced Merge Tags snippet.

- gp-nested-forms/gpnf-attach-child-entry-by-field.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2896177464/81660
When a required field in the nested form is not filled out and the validation is displayed, the hidden field (hidden by the snippet) is also displayed.
Loom: https://www.loom.com/share/750a1f3a31be4bce8c1100adb8087922
The logic for hiding the field with the filter `gform_pre_render` does not seem to work post validation fail on Nested Form Modal. This is because a condition in an edge case check `rgar( $_REQUEST, 'action' ) !== 'gpnf_refresh_markup' )` is true on Nested Form submission. We can add an additionally check for `gform_submission_method` on POST to ensure we correctly validate for hidden field scenario.
> `gpnf-attach-child-entry-by-field.php`: Fixed an issue with snippet not working on nested modal failed validation.

- gs-product-configurator/gspc-remove-price-from-addon-display.php
💬 Slack: https://gravitywiz.slack.com/archives/D042URGA4QM/p1746440777693109
(Reported by Samuel)
Typo with the snippet
`$field->cssClass`
Is supposed to be
`$product_field ->cssClass`
> `gspc-remove-price-from-addon-display.php`: Fixed a typo with the snippet.

- gp-inventory/gpi-inventory-shortcode.php
📓 Notion: https://www.notion.so/gravitywiz/GPI-1-0-1871242613d84640b0b5b189c64e9230?pvs=4 
💬 GPI Changes: https://github.com/gravitywiz/gp-inventory/pull/118
Deprecates this snippet as the shortcode functionality is now in GPI 1.0.
> `gpi-inventory-shortcode.php`: Deprecated snippet as functionality is now in GPI 1.0.

- gravity-forms/gw-conditional-logic-operator-does-not-contain.php
💬 Slack: https://gravitywiz.slack.com/archives/C04RQJ232PQ/p1746134330652079
The does not contain rule renders select of dropdown, instead of the text box.
David's loom explaining the issue:
https://www.loom.com/share/fc3e8050e0284dc480247ad2e35112ff
This PR adds the override for `does_not_contain` operator as well. Loom Demo: https://www.loom.com/share/5eeed1dd533449eab06cef3088922def
I had initially thought of the approach of using 
```js
gform.addFilter( 'gform_conditional_logic_values_input', function( str, objectType, ruleIndex, selectedFieldId, value ) {
const operator = jQuery( '#field_rule_operator_' + ruleIndex ).val();
if ( operator !== 'does_not_contain' ) {
return str;
}
str = '<input type="text" placeholder="' + gf_vars['enterValue'] + '" data-js-rule-input="value" …
```
> `gw-conditional-logic-operator-does-not-contain.php`: Fixed rule value for `does not contain` rule.

- gp-populate-anything/gppa-sort-by-time-field.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2908841996/82222?viewId=7627047
💬 Slack: https://gravitywiz.slack.com/archives/GMP0ZMNSE/p1746536433476309
This snippet is intended for when populating Times from a GF entry into a choice-based field. It will sort the times chronologically.
> `gppa-sort-by-time-field.php`: Added new snippet.

- gp-auto-list-field/gpalf-count-only-non-blank-rows.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2921955434/82734
Previously, non-blank rows were recalculated only when a user added or removed a row.
This PR enhances that behaviour by also triggering recalculations when a list field value changes.
Here’s the recorded Loom
https://www.loom.com/share/c901a19a3bc1478f828dedc7a3f464f9?sid=3332c522-f652-4356-8701-37d65f32a57c
> `gpalf-count-only-non-blank-rows.js`: Added support to recalculate non-blank rows when a list field value changes.

- gp-populate-anything/gppa-populate-child-entries.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2917938488/82554
Due to some JS error in console, field doesn't populate on first load. If we reload the page, it populates. 
Here's the loom recording of this issue. This PR fixes this issue.
https://www.loom.com/share/7fc577ae7c274ec48df5a1b3c36fe995?sid=26c1e9f0-ec10-473e-b6e7-bad4622b9ed8
> `gppa-populate-child-entries.php`: Fixed field does not populate on first load issue.

- gp-populate-anything/gppa-force-lmt-populate-on-edit.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2918356655/82575
💬 Slack: https://gravitywiz.slack.com/archives/D042XMBHJ91/p1745768566723809?thread_ts=1745647036.839519&cid=D042XMBHJ91
Live Merge Tags does not appear to be working when editing entries via the Entry Details page.
Snippet Demo:
https://www.loom.com/share/6a7f28fc0cde406798d5bad4b386a70a
> `gppa-force-lmt-populate-on-edit.php`: Added snippet to update Live Merge Tags when editing entries.

- gravity-forms/gw-disable-submission-on-enter.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2931919718/83124
[Disable Submission on Enter](https://gravitywiz.com/snippet-library/gw-disable-submission-on-enter/) snippet and Gravity Forms Conversational Forms Add-on incompatibility. The snippet works as expected when Conversational forms is not active on the form, but once it is active on the form, the snippet doesn't work.
We have updated to
1. Use `addEventListener` with `keydown` to catch `Enter` across all input elements.
2. Check for `.gform_wrapper` as a parent to confirm the event is inside a Gravity Form field.
3. Add `stopImmediatePropagation()` to prevent interference from other listeners.
This works reliably with GF Conversational Forms Add-on, and continues to work with normal form preview/form front end pages. …
> `gw-disable-submission-on-enter.js`: Fixed an issue with disable enter snippet not working with Conversational Forms.

- gp-nested-forms/gpnf-hide-quantity-in-summary-field-values.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2929910662/83058
To remove the quantity from the product data which is display on the Nested Forms Summary table.
The snippet is language independent!
**_Deutsch:_**
**_English:_**
> `gpnf-hide-quantity-in-summary-field-values.php`: Added snippet to hide quantity from GPNF summary field values.

- gp-nested-forms/gpnf-sortable-entries.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2918586555/82589
The snippet doesn't appear to work when applied to all forms and also all nested forms field on a form. It only works when the configuration is set to apply it to a specific form and specific Nested Forms field.
Loom of the issue (Samuel):
https://www.loom.com/share/bff4f13258cd4ddaa8fc24e7819558b7
After the update:
https://www.loom.com/share/837b523b30ad495c945a2e976fd896ac
> `gpnf-sortable-entries.php`: Fixed an issue with sortable entries not working correctly.

- gp-limit-dates/gpld-push-min-date-to-next-day-after-set-time.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2875355741/79394
The snippet above doesn't work, if the site timezone is set to something like Chicago.
Steps to recreate the issue
Here's the video demo of the issue: https://www.loom.com/share/4d5d42b268764351ac52ed29fe69d865?sid=0e71fa96-ff02-4be0-908b-52a85d4ae7b4
We had `strtotime( 'midnight tomorrow', $current_time->getTimestamp() )`  which caused issues because `strtotime()` interprets relative times in UTC, which seems to getting incorrect results in different timezones
This fix proposed here ensures that "tomorrow midnight" is correctly calculated in the same timezone as `$current_time` by using new a `DateTime` object specifying "tomorrow midnight".
> `gpld-push-min-date-to-next-day-after-set-time.php`: Fixed an issue with timezones.

- gp-unique-id/gpuid-generate-post-workflow.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2931821452/83120
The Unique ID to be created only after an approval step in Gravity Flow.
Demo:
https://www.loom.com/share/e799e8b4b0984d99a66da79faa34ffee
> `gpuid-generate-post-workflow.php`: Added snippet to delay generation of Unique ID until a workflow step is complete.

- gp-entry-blocks/gpeb-multi-field-sorting.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2945420521/83832
Add support for multi-level sorting in Entry Blocks, allowing users to define a primary and secondary sort field.
Demo:
https://www.loom.com/share/b9867d2735d44519bf563961e9b30bd2
> `gpeb-multi-field-sorting.php`: Added snippet for multi field sorting on Entry Blocks.

- gravity-forms/gw-capitilize-submitted-data.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2943198385/83618
https://gravitywiz.com/snippet-library/gw-capitilize-submitted-data/
The snippet above is causing a fatal error if the form is submitted with a conditionally hidden List field.
```
PHP Fatal error:  Uncaught TypeError: array_map(): Argument #2 ($array) must be of type array, null given in ...
```
Loom (Samuel):
https://www.loom.com/share/f13287a7c9b84a8d9950bc2878fbf567
> `gw-capitilize-submitted-data.php`: Fixed an issue with processing hidden list field.

- gravity-forms/gw-consolidate-multiple-list-fields-to-single-list-field.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2932462254/83138
Customer wants to consolidate rows from multiple List fields into a single List field.
Instructions and Demo:
https://www.loom.com/share/8b45a92cf56249a982aa1aa6e1301778
> `gw-consolidate-multiple-list-fields-to-single-list-field.php`: Added snippet to consolidate multiple list fields to a single list field.

- gs-product-configurator/gspc-map-order-data-to-entry.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2936045784/83304
Inspired from https://gravitywiz.com/snippet-library/gspc-populate-field-with-order-id/ to support capturing different types of WooCommerce order data (order ID, name, email) with a config instead of class-based. Example:
```php
new GSPC_Map_Order_Data_to_Entry( array( 
'field_map' => array(
1   => 'id',
2.3 => 'billing/first_name',
2.6 => 'billing/last_name',
3   => 'email', 
) 
) );
```
Setup and Walkthrough **Loom**:
https://www.loom.com/share/423b1e3835dc4757aae26a3efe9351b0
> `gspc-map-order-data-to-entry.php`: Added snippet to map order data to entry.

- gp-populate-anything/gppa-preserve-selections.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2954151326/84317
The snippet to preserve the selected choice on repopulation, doesn't work on Checkbox fields.
This update needs GPPA PR: https://github.com/gravitywiz/gp-populate-anything/pull/625
https://www.loom.com/share/4128bac6460b4892b0a0b710ded0069c
> `gppa-preserve-selections.php`: Fixed an issue with preserve selections not working correctly for checkbox field.

- gc-openai/gcoai-stream-to-paragraph-field.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2957026305/84491
Update Stream to Paragraph Field (Multi-field Support)
> `gcoai-stream-to-paragraph-field.js`: Added support for multiple OpenAI streams.

- gravity-forms/gw-shortcode-attr-field-props.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2960746738/84687
Assigning `$_args` to `array()`.
We did a lot of these [here](https://github.com/gravitywiz/snippet-library/pull/761). Somehow this one was left out. 😬
> `gw-shortcode-attr-field-props.php`: Fixed potential PHP warnings.

- gp-file-upload-pro/gpfup-count-files-groups.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2951970232/84219
Add support for grouping file upload fields in the GPFUP Count Files snippet. Allow defining multiple groups and assigning each group’s count to a different number field.
https://www.loom.com/share/2328e327125844bebdcabf7c9baaabca
> `gpfup-count-files-groups.js`: Added snippet to count files in groups.

- gravity-forms/gw-populate-date.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2966564752/85024
The  `strftime` function, which is used in the Populate Dates snippet, is deprecated as of PHP 8.1.0 (reference: https://www.php.net/manual/en/function.strftime.php)
Also, it will be removed from PHP 9.0 (reference: https://php.watch/versions/8.1/strftime-gmstrftime-deprecated).
Time to move on!
> `gw-populate-date.php`: Fixed a deprecated warning notice.

- gp-entry-blocks/gpeb-filter-by-nested-field.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2943573391/83636
Add support to make it possible to include the child form field values to the filter block on the parent form.
Loom Demo:
https://www.loom.com/share/f795e8b5ef58489794dca96e83fcd230
> `gpeb-filter-by-nested-field.php`: Added snippet to allow filtering data via nested entries.

- gp-inventory/gpi-disable-object-cache.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2894376170/81592
This snippet helps to disable object cache in GP Inventory.
> `gpi-disable-object-cache.php`: Added new snippet to disable object cache in GP Inventory.

- gp-media-library/gpml-acf-user-image-field.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2921885802/82733
File uploaded to an ACF Image field on the user profile, when user profile is updated with GFUR is removed.
https://www.loom.com/share/029fcc517e50428d81800577d1106661?sid=ac7c7d82-17ae-4161-bda6-f4c3478d5e50
> `gpml-acf-user-image-field.php`: Fixed an issue with User Image getting removed on form resubmission.

- gp-nested-forms/gpnf-gv-auto-approve-child-entries-with-parent-entry.php
💬 Slack: https://gravitywiz.slack.com/archives/GMP0ZMNSE/p1732000088338319
Auto-appprove Child Entries when its Parent Entry is approved with GravityView
https://www.loom.com/share/a8ab5395a91d437eb1b393d7ba5b50c4
> `gpnf-gv-auto-approve-child-entries-with-parent-entry.php`: Added snippet to auto approve nested entries when parent entry is approved.

- gp-randomizer/gpr-randomize-fields-to-its-own-page.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2981566709/85763
Needs the new filter `gpr_filtered_fields` from https://github.com/gravitywiz/gp-randomizer/pull/16
Demo of the snippet: https://www.loom.com/share/2dd4f3c6995349ae91d4b88f3990294b
> `gpr-randomize-fields-to-its-own-page.php`: Added snippet to randomize fields to its own page.

- gp-nested-forms/gpnf-sort-nested-form-entries.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2995555966/86254?viewId=3808239
**Issue:** Date fields were being sorted alphabetically instead of chronologically, causing unexpected ordering (see [Matt's loom](https://www.loom.com/share/52ed275489a54b75be2f63727fdecdd2))
Snippet now automatically detects date fields and sorts them chronologically.
> `gpnf-sort-nested-form-entries.php`: Added support for sorting by Date fields.

- gp-copy-cat/gpcc-copy-option-to-checkbox.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2973256443/85365
Make the Option field compatible to be used with [GP Copy Cat](https://gravitywiz.com/documentation/gravity-forms-copy-cat/) and a receiving Checkbox field.
https://www.loom.com/share/0897b49b88ca43be9590e2aef13de50a
> `gpcc-copy-option-to-checkbox.js`: Added a snippet to copy Option field selected value to Checkbox field.

- gp-advanced-select/gpadvs-caret-position.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2977271468/85589
A snippet to include the [Caret Position plugin](https://tom-select.js.org/plugins/caret-position/) for Advanced Select.
How the update works:
https://www.loom.com/share/207872ed42ec4e84be6edc514be01e43
> `gpadvs-caret-position.js`: Added snippet to include Caret Position with GPAS.

- gp-advanced-select/gpadvs-search-exact-match.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2986058780/85959
💬 Slack: https://gravitywiz.slack.com/archives/GMP0ZMNSE/p1751379142647819
By default, Advanced Select will return any item whose label contains the search query. This snippet will change the search algorithm to only return items whose label matches the search query exactly.
TomSelect score [docs here](https://tom-select.js.org/docs/#:~:text=or%20no_results%20templates.-,score(search),-Overrides%20the%20scoring).
Instruction Video:
https://www.loom.com/share/4266734e5ab14870ba6b8bba28d01f68
> `gpadvs-search-exact-match.js`: Added snippet to enable exact match functionality with GP Advanced Select.

- gp-populate-anything/gppa-disable-gfml-pre-render-callback.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2975924505/85517
The value modifier of a merge tag doesn't work when WPML String translations is activated, even when using this [snippet](https://gravitywiz.com/snippet-library/gppa-disable-gfml-pre-render-callback/).
It seems we need to also target `gform_merge_tag_filter` in the disable logic, probably applicable for the newer versions of GFML.
**BEFORE**:
**AFTER**:
> `gppa-disable-gfml-pre-render-callback.php`: Fixed an issue with snippet not working for newer versions of GPML.

- gravity-forms/gw-gravity-forms-rounding.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2981539269/85760
The GF Rounding snippet isn't working as expected.
**ISSUE 1**
_**The minimum rounding doesn't work when the value is entered. It works only when you're using the number field controls to increase or decrease the value.**_
We had `if( value != '' )`, which we changed to `if( value !== '' )`
Switching from loose inequality (`!=`) to strict inequality (`!==`) to prevent unintended type coercion. This ensures that numeric 0 and empty string '' are treated as distinct values during comparison. With `!=`, javascript converts `0 != ''` as a numeric comparison with both values as `0`.
**ISSUE 2**
_**When the rounding is applied to a quantity value, it doesn't update the total.**_
Using `$input.val( value ).change();` alone …
> `gw-gravity-forms-rounding.php`: Fixed an issue with rounding now updating form total.

- gravity-forms/gw-product-quantity-conditional.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2951687684/84205
Targeting Single Product field's quantity input to be applicable in Gravity Forms' regular conditional logic.
Snippet Demo:
https://www.loom.com/share/38547a28853f4706b10cfdb42eaa45ca
> `gw-product-quantity-conditional.php`: Added snippet to use quantity value of Product Field as a conditional logic field.

- gp-pay-per-word/gpppw-capture-count-as-field-value.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/3028599571/87494
When using the gpppw_word_count snippet to populate a text field with the word count from a paragraph field, we relied on triggering the `.change()` event to ensure that the value could be used in Gravity Forms conditional logic. However, this approach caused a JavaScript error — specifically `Uncaught RangeError: Maximum call stack size exceeded` — which ultimately prevented the form from loading in the browser.
The root cause was that `.change()` was being triggered even when the field value hadn’t changed. Since that field was used in conditional logic, Gravity Forms repeatedly re-evaluated conditions and retriggered the same logic, leading to an infinite loop.
This PR proposes to add a check to compare the …
> `gpppw-capture-count-as-field-value.js`: Fixed an issue with snippet not working with Conditional Logic in play.

- gravity-forms/gw-require-unique-values.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/3019475786/87093?viewId=8172236
**Original issue/feature request:** https://www.loom.com/share/7efd82e759514e21866854c87a802f2a (By Matt A.)
This adds support for allowing multi-input fields to be validated as a single, combined value.
**Quick loom showing new feature:** https://www.loom.com/share/22a0b59a9b6f46c69f708621f78d507b
> `gw-require-unique-values.php`: Added support for whole-field validation for multi-input fields.

- gp-unique-id/gpuid-multiple-ids.php
https://gravitywiz.com/gravity-forms-build-raffle-or-lottery/
This is to extend the raffle/lottery ticket example on here: https://gravitywiz.com/gravity-forms-build-raffle-or-lottery/
While the guide supports "packages" of pre-defined counts for choice selections, it does not allow user-defined counts for multiple ticket types.
This PR allows you to specify multiple field IDs that will all be counted and totalled to the final count allowing you to sell multiple ticket types with as many as a user would like to purchase.
> `gpuid-multiple-ids.php`: Added option to use multiple fields for count

- gp-nested-forms/gpnf-map-child-entries-to-acf-repeater-field.php
💬 Slack: https://gravitywiz.slack.com/archives/D042URGA4QM/p1756134823778349
Props to @sbassah for pointing this out! 🙌 
Fix the param count for the [hook](https://docs.gravityforms.com/gform_advancedpostcreation_post_after_creation/).
> `gpnf-map-child-entries-to-acf-repeater-field.php`: Fixed an issue with snippet param count.

- gravity-forms/gw-update-posts.php
⛑️ Ticket(s):https://secure.helpscout.net/conversation/3048075959/88266
The Update Posts (https://gravitywiz.com/snippet-library/gw-update-posts/) snippet is deactivating automatically due to an error on line 360-361 with WPCode snippets. Use `rgar` instead and it fixes the issue.
> `gw-update-posts.php`: Fixed an issue with snippet not working in some scenarios.

- gp-ecommerce-fields/gpecf-deduct-deposit.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/3042483189/88050
The snippet to use a product field to deduct deposit is causing GF to display incorrect calculations on the frontend when the Deposit field is conditionally hidden.
**BEFORE** (Credits Samuel):
https://www.loom.com/share/ad6470f9886c4a0983e253b23b796cd0
**AFTER**:
https://www.loom.com/share/4448c9551ec246c4b8756e3a64e839c0
> `gpecf-deduct-deposit.php`: Fixed an issue where disabled deposit field caused issues with calculations.

- gp-inventory/gpi-show-inventory-only-for-logged-in-users.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/3048324137/88279/
Show Inventory Only For Logged In users only.
https://www.loom.com/share/2d9843302a54456987ed2c66a83612ba
> `gpi-show-inventory-only-for-logged-in-users.php`: Added snippet to show available inventory message only for logged in user.

- gp-submit-to-access/gpsa-enable-for-all-posts-of-type.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/3050511236/88377?viewId=6987275 
Allows GPSA to be enabled via filter for all Posts of a given type.
Relies on: https://github.com/gravitywiz/gp-submit-to-access/pull/10
> `gpsa-enable-for-all-posts-of-type.php`: Added snippet to allow enabling GPSA via snippet for all posts of type.

- gravity-forms/gw-conditional-logic-operator-is-in.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/3056241699/88571?viewId=8172236
This PR adds `is_in` as a custom import operator to GP Conditional Pricing. This goes hand-in-hand with another new [PR for GPCP](https://github.com/gravitywiz/gwconditionalpricing/pull/76), which adds the `gpcp_supported_import_operators` filter.
> `gw-conditional-logic-operator-is-in.php`: Added GPCP CSV Import support for `is_in` operator.

- gp-nested-forms/gpnf-hide-empty-columns.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/3069272683/89066
Updated `gpnf_hec_column_has_value()` to correctly detect values stored on sub-inputs (e.g. `8.3`, `8.6`) in addition to the actual field ID (e.g. `8`).
Fields like Name or Address, which store values across multiple sub-input IDs, were not being detected.
> `gpnf-hide-empty-columns.php`: Fixed an issue withsnippet not working for fields having data stored on sub field IDs like Name, Address, etc.

- gravity-forms/gw-cid-image-handler.php
⛑️ Ticket(s): https://secure.helpscout.net/link/to/conversation
📓 Notion: https://notion.so/link/to/card
💬 Slack: https://slack.com/link/to/thread-or-message
> `gw-cid-image-handler.php`: Added new snippet.

- gp-limit-submissions/gpls-set-limit-by-woo-product-purchase-count.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/3068506982/89018?viewId=7627047
Added a new snippet that sets the GPLS limit to the number of times the current user has purchased a specific Woo product.
> `gpls-set-limit-by-woo-product-purchase-count.php`: Added new snippet.

- gravity-forms/gw-delay-feed-till-user-registration.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/3089322500/89859
Missing `$form` object fixed, grab it from `$entry` because `_args` may have it missing it globally applied.
> `gw-delay-feed-till-user-registration.php`: Fixed an issue with delayed feed not processing due to missing form object data.

- experimental/gpeb-export-entries-csv.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/3093956084/90023
Appears like this:
To make it appear along side the entries table, like this:
**_An additional snippet would be required:_**
```php
add_action( 'wp_footer', function() {
// UPDATE: to your page slug.
if ( ! is_page( 'page-slug' ) ) {
return;
}
?>
<script>
document.addEventListener( 'DOMContentLoaded', function() {
const exportLink = document.querySelector( '.gpeb-export-csv-link' );
const entriesBlock = document.querySelector( '.wp-block-gp-entry-blocks-entries' );
if ( exportLink && entriesBlock ) {
entriesBlock.parentNode.insertBefore( exportLink, entriesBlock );
}
});
</script>
<?php
});
```
> `gpeb-export-entries-csv.php`: Added experimental export entries snippet.
