gravity-forms/gw-gravity-forms-rounding.php
This PR imports the Rounding by Increments snippet and implements the following updates:
- Prevent rounding of floats if entered number is not greater than max
- Prevent rounding of floats if entered number is not less than min
- Adds support for rounding by decimal value
- Adds `gw-rounding-custom` filter to allow end-users to implement rounding algorithm of choice
- General PHPCS house-keeping
Additional info in HS.
=> Rounding by Increments Update

gravity-forms/gw-create-coupon.php
An update for the snippet to pass a field id to get a value that will be used to set the coupon name.
=> Added a parameter to pass a title for coupon code

gravity-forms/gw-create-coupon.php
This PR adds support to set the coupon limit using a field value in addition to setting a static limit
=> Added support to set the coupon limit using a field value

gravity-forms/gw-advanced-conditional-shortcodes.php
This PR imports the Advanced Conditional Shortcodes snippet and converts it to a plugin.
=> Add gw-advanced-conditional-shortcodes.php and convert to plugin

gp-limit-dates/gpld-exclude-blocked-dates-from-modifiers.php
This PR adds a plugin header for gpld-exclude-blocked-dates-from-modifiers.php
=> Added plugin header to gpld-exclude-blocked-dates-from-modifiers.php

gp-conditional-pricing/gpcp-product-pricing-labels.js, gp-conditional-pricing/gpcp-product-pricing-labels.php
Original gist: https://gist.github.com/spivurno/cc461abccceaf9aec531210cb0846476
=> Added gpcp-product-pricing-labels.js and gpcp-product-pricing-labels.php

gp-limit-submissions/gpls-disable-limits-for-specific-user-role.php, gp-limit-submissions/gpls-disable-rule-for-user-role.php
Snippet to disable Limit Submission Rule for Specific User Role
=> Gpls disable rule for user role

gravity-forms/gw-populate-date.php
This PR replaces the old `strtotime.js` with the current release.
Most notably this fixes `last day of` which returned `yesterday` in the old version.
#22863
=> Added the latest version of `strtotime.js`.

gravity-forms/gw-gravity-forms-rename-uploaded-files-usage.php
This PR migrates the usage examples file for the Rename Uploaded Files snippet.
[Current documentation](https://gravitywiz.com/rename-uploaded-files-for-gravity-form/)
#22992
=> Added Rename Uploaded Files snippet usage file.

gravity-forms/gw-edit-product-and-payment-details.php
Original Gist: https://gist.github.com/spivurno/416f1981e48bd3227e6b
=> Edit Products & Payment Details

gravity-forms/gw-validate-that-a-value-exists.php
Original Gist: https://gist.github.com/spivurno/e84523ef4feba903c80b
=> Validate that a Value Exists

gp-easy-passthrough/gpep-save-token-to-field.php
Original Gist: https://gist.github.com/spivurno/f30988968900333c631e81a9c873358a
=> Gravity Perks // Easy Passthrough // Save EP Token to Field

gp-limit-choices/gplc-field-groups.php
Original Gist: https://gist.github.com/spivurno/8ca209fbb5068e62655ddf91678830a3
=> Gravity Perks // GP Limit Choices // Field Groups

gp-populate-anything/gppa-populate-child-entries.php
Original Gist: https://gist.github.com/spivurno/dc425112b60c8aea98b7b947a50a8cf3
=> Gravity Perks // Populate Anything // Populate Child Entries

gp-easy-passthrough/gpep-edit-entry.php
Original Gist: https://gist.github.com/spivurno/8b42143282c0fbec54e8c18de5124809
=> Gravity Perks // Easy Passthrough // Edit Entry

gravity-forms/gw-quantity-as-decimal.php
Original Gist: https://gist.github.com/spivurno/3710739
=> Gravity Wiz // Enable Decimal Values for Quantity Fields

gravity-forms/gw-validate-current-password.php
Original Gist: https://gist.github.com/spivurno/eebad70856ec3be400ccdeface37479a
=> Gravity Wiz // Gravity Forms // Validate Current Password

gravity-forms/gw-schedule-post-by-date-field-multi-form.php
Original Gist: https://gist.github.com/spivurno/4dfae7f6dd4bd15b8a6986436989c687
=> Schedule a Post by Date Field (for Multiple Forms)

gravity-forms/gw-set-entry-created-by.php
Original Gist: https://gist.github.com/spivurno/2cb857c17b10731828fb
=> Set Entry Creator by Field Value

gravity-forms/gw-set-list-field-rows-by-field-value.php
Original Gist: https://gist.github.com/spivurno/3708793
=> Set Number of List Field Rows by Field Value

gravity-forms/gw-redirect-if-email-exists.php
Original Gist: https://gist.github.com/spivurno/93f1581eef68fe6724eb9fc75d41e73a
=> Gravity Wiz // Gravity Forms // Redirect if Email Exists

gp-multi-page-navigation/gpmpn-disable-multi-page-navigation-page-links.css
Original Snippet: https://secure.helpscout.net/conversation/1446028451/23053/
=> Disable Multi-Page Navigation Links via CSS

gp-nested-forms/gpnf-display-child-entries-table-format.php
Original Gist: https://gist.github.com/spivurno/3a3b92bf32824a414c87c23bbf5ca335#file-gp-nested-forms-display-child-entries-table-format-php
=> Display Child Entries in Table Format for All Fields

gravity-forms/gw-all-fields-template.php
[HS#23585](https://secure.helpscout.net/conversation/1471850947/23585/)
Use the new `gwaft_modifier_value_CUSTOMVALUE` filter to replace your custom value with field IDs dynamically.
=> Added support for custom modifier values.

gp-limit-checkboxes/gplcb-set-max-by-field-value.js
Original Gist: https://gist.github.com/spivurno/09aee6a8ec9ceb684cf5bf0d9c51e19f
=> Set Max Limit by Field Value

gp-unique-id/gpuid-username-validation.php
Original Gist: https://gist.github.com/spivurno/aa4f7bbb66fed3300746
=> Unique ID as Username

gp-populate-anything/gppa-merge-tag-context-modifier.php
Original Gist: https://gist.github.com/spivurno/9dbbf27c88c5656eaf1b64be97e7ca41
=> Replace Merge Tags in Specific Context

wc-gf-product-addons/wcgfpa-remove-fields.php
Added snippet to remove fields from product description in the cart
=>  Remove Fields From Product Description

gp-nested-forms/gpnf-triggered-population.php
Original Gist: https://gist.github.com/spivurno/89974e5030b8c68c578b1e55bdfac9c1
=> Add Child Entry on Trigger

gp-post-content-merge-tags/gppcmt-save-confirmation-url-to-field.php
Original Gist: https://gist.github.com/spivurno/8ab397d2f4c21bd5205e8c30716f8a62
=> Save Confirmation URL to Field

gp-ecommerce-fields/gpecf-deduct-deposit.php
Original Gist: https://gist.github.com/spivurno/da655f24c07e6204a11e2e647113677f
=> Deduct Deposit from Order Summary

gp-read-only/gpro-disable-for-admins.php
Original Gist: https://gist.github.com/spivurno/c37ee64c1a63300e90fe9db6218e959a#file-gp-read-only-disable-for-admins-php
=> Disable Read Only for Admins

gravity-forms/gw-notification-events.php
Original Gist: https://gist.github.com/spivurno/bd9d8e118f45999fb08c
=> Added gw-notification-events.php

gravity-forms/gw-save-and-continue-auto-load.php
Original Gist: https://gist.github.com/spivurno/c48bcf30eb70093c99fd26fe41945795
=> Save & Continue Auto Load for Gravity Forms

gp-limit-choices/gplc-spots-left-plus-waiting-list.php
Original Gist: https://gist.github.com/spivurno/82092c812c49891670dc
=> Spots Left + Waiting List Message

gravity-forms/gw-hide-css-fields-from-all-fields.php
Original Gist: https://gist.github.com/spivurno/bbdf4a29adb382c9f897
=> Hide Fields Hidden via CSS Classes from {all_fields} Merge Tag

gp-nested-forms/gpnf-display-child-entries-table-format.php
Updated the snippet to support displaying all Child form fields in table format.
Updated the snippet description and usage example
=> Added support to show all fields in table format

gp-unique-id/gpuid-wait-for-payment-support-for-payfast.php
Original Snippet: https://snippi.com/s/i38sr1d
=> Add Wait-for-payment Support for PayFast

gravity-forms/gw-update-posts.php
This adds support for updating post categories and custom taxonomies. It assumes the user is populating taxonomies into a Checkbox field.
=> Added support for updating post categories and custom taxonomies.

gravity-forms/gw-numbering-list-field-rows.css
Original Code: https://snippi.com/s/82acsaz
=> Numbering List Field Rows

gravity-forms/gw-update-posts.php
The idea for this is a choice field with the different post status as available choices.
This choice field can be populated via GPPA:
=> Added support for updating post status.

gravity-forms/gw-update-posts.php
[HS#25449](https://secure.helpscout.net/conversation/1551081560/25449/)
=> Added support for updating featured image via File Upload field.

gravity-forms/gw-random-fields.php
[HS#25521](https://secure.helpscout.net/conversation/1553478273/25521)
This PR adds support for randomizing field order which is enabled by default. This feature can be disabled by passing `true` for the new `$perserve_field` parameter when instantiating the class.
`new GFRandomFields( 123, 2, array( 1, 2, 4, 5, 7 ), true );`
=> Added support for randomizing field order.

gp-nested-forms/gpnf-display-child-entries-table-format.php
This PR cleans up the GPNF Display Table Format for All Fields snippet and fixes a potential PHP warning.
Not related to fixing any particular issue.
=> GP Nested Forms // Display Table Format for All Fields Cleanup.

gravity-forms/gw-submit-to-access.php
Add option to use `per_page` as value for `gwsa_require_submission` meta to require forms to be submitted on the current page.
This allows you to re-use a form on multiple pages while requiring it to be resubmitted each time.
=> Added support for requiring submission on current page with Snippet to Access using `per_page` value in `gwsa_require_submission` meta

gp-limit-dates/gp-limit-dates-mobile-styling-inline-datepicker.css
Replaces [this snippet](https://gist.github.com/spivurno/9680c3aa2791e0558668b285c369618d) with styles for GF 2.5
=> Added mobile styles for inline datepicker in GF 2.5

gravity-forms/gw-populate-date.php
[HS#26609](https://secure.helpscout.net/conversation/1599101905/26609)
This PR adds support for populating/modifying times from one Time field into another. 
Here is a form export:
[gravityforms-export-2021-08-13.json.zip](https://github.com/gravitywiz/snippet-library/files/6984892/gravityforms-export-2021-08-13.json.zip)
...and example configuration:
```php
new GW_Populate_Date( array(
'form_id'         => 123,
'source_field_id' => 1,
'target_field_id' => 2,
'modifier'        => array(
'type'     => 'field',
'inputId'  => 4,
'modifier' => '+{0} minutes',
),
) );
```
=> Added support for populating/modifying times from one Time field to another.

gp-populate-anything/gppa-aggregate-functions.php
Original Snippet: https://snippi.com/s/ukdqjfw
=> Add Support for Aggregate Functions

gravity-forms/gw-require-unique-values.php
Original Gist: https://gist.github.com/spivurno/4fb1d71a69771fe9e5f6#file-gw-gravity-forms-require-unique-values-php
=> Require Unique Values Between Fields

gravity-forms/gw-email-domain-validator.php
Original Gist: https://gist.github.com/spivurno/4055158
=> Email Domain Validator

gp-populate-anything/gppa-force-dyn-pop-on-gv-edit.php
Orginal Gist:  https://gist.github.com/spivurno/a80d7ac9d3bb62aa0febe86af7b93f8f
There is no plugin header because the snippet is short.
=> Force Dynamic Population When Editing via GV

gp-nested-forms/gpnf-custom-parent-form-merge-tags.php
Original: https://secure.helpscout.net/conversation/1482476571/23771/#thread-4381809302
=> Custom Parent Form Merge Tags

gp-limit-choices/gplc-spots-left-admin-only.php
Original Gist: https://gist.github.com/spivurno/73ad5599740a20521165
=> Display How Many Spots Left to Admins Only

gp-limit-choices/gplc-daily-limit.php
Original Gist: https://gist.github.com/spivurno/2b3839548318449da7dc/
=> Daily Limit

gravity-forms/gw-require-unique-values-usage.php
Original Gist: https://gist.github.com/spivurno/4fb1d71a69771fe9e5f6#file-z-gw-gravity-forms-require-unique-values-usage-php
=> Require Unique Values Between Fields Usage

gravity-forms/gw-manual-notifications.php
Original Gist: https://gist.github.com/spivurno/667e6c1ed3a64fe53b58
=> Send Manual Notifications

gravity-forms/gw-display-prices-for-choice-based-product-fields.php
Original Gist: https://gist.github.com/spivurno/a52923aadd37cc0151ce33c92662ba60
=> Display Price for Drop Down and Radio Button Product Fields

gp-populate-anything/gppa-filter-by-relative-dates.php
Original Gist: https://gist.github.com/claygriffiths/bdd06373bb04ab7a62fd0330c23d619d
=> Filter Results on Relative Dates

gp-limit-submissions/gpls-apply-same-feed-to-group.php
Original Gist: https://gist.github.com/spivurno/10c51485d70e7ff2fac3cca8a70aedc2
=> Apply Limit Feed to Group of Forms

gravity-forms/gw-user-registration-skip-registration-for-existing-email.php
Original Gist: https://gist.github.com/spivurno/ef6572a77cdc7483c40777e65467f448
=> User Registration // Skip Registration if Email Exists

gp-limit-submissions/gpls-global-feeds.php
Original Gist: https://gist.github.com/spivurno/82506e4de2c579d6b1e4c083bb753a0f
=> Apply Limit Feeds Globally

gp-unique-id/gpuid-global-sequential-id.php
Original Gist: https://gist.github.com/spivurno/1179e999d795d6a9189a
=> Share a global sequential unique ID across all forms

gravity-forms/gw-list-field-as-choices.php
Original Gist: https://gist.github.com/spivurno/8202318#file-gw-gravity-forms-list-field-as-choices-php
=> Use List Field as Choices for Gravity Forms

gravity-forms/gw-list-field-as-choices-usage.php
Original Gist:  https://gist.github.com/spivurno/8202318#file-gw-gravity-forms-list-field-as-choices-usage-php
=> Usage configuration for Snippet

gravity-forms/gw-currency-symbol-right-to-left.php
Original Gist: https://gist.github.com/spivurno/0d772bae83bb216e89aa
=> Move Currency Symbol from the Right to the Left

gp-populate-anything/gppa-set-post-taxonomy-terms.php
Original GIst: https://gist.github.com/spivurno/aff119c1a0513421823d30d13fb241cb
=> Set Post Taxonomy Terms

gp-copy-cat/gpcc-copy-product-value.js
Original Gist: https://gist.github.com/spivurno/d3ddce62882808d6dae177c3a528e2f1
=> Copy Product Value Without the Price

gravity-forms/gw-format-date-merge-tags.php
Original gist: https://gist.github.com/spivurno/f1fb2f0f3650d63acfb5ed644296abda
=> Added Format Date Merge Tags snippet

gravity-forms/gw-gravity-forms-custom-js.php
[HS#27390](https://secure.helpscout.net/conversation/1630758040/27390)
This PR refactors custom JS to be enqueued as an init script rather than output directly to the footer. This resolves an issue with Gravity Forms 2.5 where custom JS (which is bound by default to the `gform_post_render` event) was being triggered before registered init scripts instead of after (as is the case with GF 2.4).
By registering the custom JS as an init script on a very late priority (e.g. 99), we can ensure that it is triggered after all other init scripts.
I was unable to detect a way to do this without registering the JS as an init script. There is no window where the script could be bound to the `gform_post_render` event _after_ all other scripts without missing the actual triggering of the …
=> Refactored custom JavaScript to be enqueued as an init script for better compatibility with Gravity Forms 2.5.

gp-populate-anything/gppa-display-post-featured-image.php
Original Code: https://secure.helpscout.net/conversation/1633486080/27506/#thread-4783912279
https://snippi.com/s/7rd1p9l
=> Display Post Featured Image

gp-populate-anything/gppa-display-post-featured-image.php
Removed the plugin header as requested by Scott.
=> Removed the plugin header

gp-preview-submission/gpps-hidden-field-from-preview.php
Original Gist: https://gist.github.com/spivurno/7bc96d50c1299a484166df0d06b96b48
=> Hide Hidden-visibility Fields from Preview

gravity-forms/gw-user-registration-update-by-email.php
Original Gist: https://gist.github.com/spivurno/3bb450d5469df7b10f6d273a6cd24272
=> Update by Email

gravity-forms/gw-capitilize-submitted-data.php
Original Gist: https://gist.github.com/spivurno/4c388975448ae97a447a
=> Capitalize Submitted Data

gp-unique-id/gpuid-shared-sequences.php
Original Gist: https://gist.github.com/spivurno/80136faa684c923d9f8db20be0c7f7b4
=> Share Sequential ID

experimental/gw-validate-postcode.php
As requested in this [ticket](https://secure.helpscout.net/conversation/1691274072/28775?folderId=3775888). Here's a simple version of the snippet to validate the postcode against the UK regex pattern.
=> Validate UK Postcode

gp-nested-forms/gpnf-hourly-cron.php
Original Gist: https://gist.github.com/spivurno/961aae8e182d5bee0b75c67807f596a2
=> gpnf-hourly-cron.php

gravity-forms/gw-quantity-as-decimal.php
Updated the snippet header and added a Plugin header
=> Added a Plugin Header

gravity-forms/gw-calculated-shipping.php
Original Gist: https://gist.github.com/spivurno/7356056
=> Calculated Shipping

gravity-forms/gw-three-decimal-currencies.php
Original Gist: https://gist.github.com/spivurno/a79c5f6bb9d783f3ff9b2a7c51e56df0
=> Three Decimal Currencies

gp-ecommerce-fields/gpecf-set-tax-amount-dynamically.php
Original Gist: https://gist.github.com/spivurno/cfb2ad05a62d7c76edcba9656634e066
=> Set Tax Amount Dynamically

gp-limit-submissions/gpls-dynamically-set-limit.php
Original Gist: https://gist.github.com/spivurno/7d41492281d02c167cea5f205be6295c
=> Dynamically Set Limit

gp-copy-cat/gpcc-copy-label.js
Original Gist: https://gist.github.com/spivurno/96793af8d1523621a082d5579dd66cc7
=> Copy Label (instead of Value)

gravity-forms/gw-notify-author-on-publish.php
Original Gist: https://gist.github.com/spivurno/3710966
=> Notify Author When Post is Published

gravity-forms/gw-notify-user-on-publish.php
Original Gist: https://gist.github.com/spivurno/3710975
=> Notify User When Submitted Post is Published

gp-media-library/gpml-acf-user-image-field.php
Original Gist: https://gist.github.com/spivurno/331d60d84a869a3b1e103de5a38cfb3e
=> Populate ACF Image Fields in User Profile

gravity-forms/gw-prevent-duplicate-submissions.php
Original Gist: https://gist.github.com/spivurno/53e94532ce38efbd49c05fb16122436b
=> Prevent Duplicate Submissions from Double Clicks

gp-nested-forms/gpnf-require-unique-values.php
Original Gist: https://gist.github.com/spivurno/e7ea0631603b6bb7fa9a737cfd601f30
=> Require Unique Value Between Parent & Child

gp-unique-id/gpuid-site-address-title-validation.php
Original Snippet :https://gist.github.com/spivurno/0ae1c3ecf3c9e852d8ea
=> Unique ID as Site Address and Site Title

gravity-forms/gw-multiple-entries-list-field.php
Original Gist: https://gist.github.com/spivurno/fbbb2515da8e0b91251ce58962f661d9
=> Create Multiple Entries by List Field Rows

gravity-forms/gw-current-time-merge-tags.php
Original Gist: https://gist.github.com/scyt/40b5f0e4575f33f5ffea29501677c7e9
=> Current Time Merge Tags

gravity-forms/gw-allow-create-and-update-feeds.php
Original Gist: https://gist.github.com/spivurno/0dbc279bed71d189eba164ea56db4205
=> GFUR - Update & Create Feeds on Same Form

gp-populate-anything/gppa-populate-all-results.php
I've created a video walkthrough for our spell crafted GPPA All Results snippet 👏
=> added video walkthrough for GPPA All Results

gravity-forms/gw-validate-current-password.php
First time I've used this snippet! A cool one 🆒
=> added video to showcase GW Validate Current Password snippet for GFUR

gravity-forms/gw-feed-specific-submit-button.php
Original Snippet : https://gist.github.com/spivurno/33440426a38c976b0c4d6a692ccc5c9a
=> Feed-specific Submit Button

gravity-forms/gw-get-form-id-by-form_title.php
Original Gist: https://gist.github.com/spivurno/5cc99da16d877ba32616a368d1a60c88
=> Get Form ID by Form Title

gravity-forms/gw-populate-current-quarter.php
I've created this videos since I wasn't sure how to use the snippet. I've found an HS thread with the reference to use it [HS#21817](https://secure.helpscout.net/conversation/1386182183/21817/)
=> added Instruction Video for populating current quarter of the year

gp-nested-forms/gpnf-disable-sessions.php
Original Gist: https://gist.github.com/spivurno/014ec4c4dbcfa76a593d1f8149921295
=> Disable Session Storage

gp-address-autocomplete/gpaa-single-line-as-input.php
Original Snippets: https://github.com/gravitywiz/snippet-library/commit/3a3d93ce4642a305df434564195e45269c8e8159
=> Use Single Line Text field as Autocomplete Input

gp-inventory/gpi-show-current-inventory-on-entries-list.php
Added support to display inventory for choice-based fields on the entry page.
=> Added Support for Choice Based fields

gp-populate-anything/gppa-explode-commas-as-choices.php
=> Fix typo on line 16.  "All" should be "allow"

gp-limit-choices/gplc-spots-left.php
This PR fixes the issue where the snippet wasn't displaying the correct noun based on the Spot left.
=> ~ Fixed the Spot left noun

gravity-forms/gw-min-and-max-character-limit.php
Original Snippet: https://gist.github.com/spivurno/8220561#file-gw-gravity-forms-minimum-characters-php
Per the [request of a user](https://secure.helpscout.net/conversation/1820941677/32691?folderId=3775888#thread-5362256382), I added support to use the snippet on multi-input fields
=> Require Minimum and Maximum Character Limit

gp-populate-anything/gppa-acf-repeater-mapper.php
Currently, the snippet only populates values from the Repeater field within a Post. I've added support to populate from a Repeater field that's within the user meta. 
Also, when using a normal dropdown field, it displays a notice warning message when debug is on. I've added support to use the snippet on both the Product dropdown field and the normal dropdown field.
[Ticket](https://secure.helpscout.net/conversation/1805726287/32135?folderId=14964)
=> Added support to populate from User repeater custom field

gp-nested-forms/gpnf-override-parent-merge-tag-on-submission.php
Replaces https://github.com/gravitywiz/snippet-library/pull/291.
=> Added support to exclude fields when using snippet.

gp-nested-forms/gpnf-override-parent-merge-tag-on-submission.php
[HS#29337](https://secure.helpscout.net/conversation/1707991534/29337)
Multiple parent merge tags were not supported in a single default value. When the form was submitted, the default value was replaced with an empty string. That doesn't happen now.
=> Added support for forced replacement of multiple parent merge tags in a single default value.

gravity-forms/gw-round-robin.php
[HS#29963](https://secure.helpscout.net/conversation/1728316556/29963)
Oof. This was a tricky one.
I updated the Round Robin snippet a month ago to allow this customer to use Populate Anything to create dynamic Round Robin lists. Unfortunately, I didn't account for the fact that it always fetched the last submitted entry rather than the last submitted entry that matched Round Robin list for the current entry.
This PR implements basic support for accounting for GPPA filters when fetching the last entry. It's currently limited to a single filter group (no "or" support) and only field to field comparisons (no custom values). This solves the problem for this customer and we can make this more robust as needed.
=> Fixed issue where fetching last entry needed to account for the filters applied to the GPPA-enabled round robin field.

gravity-forms/gw-update-posts.php
[HS#33107](https://secure.helpscout.net/conversation/1833648300/33107/)
=> Added support for mapping all checkboxes of a Checkbox field to a custom field.

gp-populate-anything/gppa-acf-datepicker-comparison.php
Original Snippet: https://gist.github.com/claygriffiths/4cfb85c0d4ef1095cb262021e2d8c749
=> Parse ACF Date Picker Fields for Comparison

gravity-forms/gw-notify-author-on-publish.php, gravity-forms/gw-notify-user-on-publish.php
These snippets include plugin headers, however they require configuration in the snippet.
=> Removed plugin headers.

gravity-forms/gw-dynamic-population-parameters.php
Original Gist: https://gist.githubusercontent.com/spivurno/3708844
=> Use Merge Tags as Dynamic Population Parameters

gravity-forms/gw-display-number-of-entries-left-based-on-entry-limit.php
Original Gist: https://gist.github.com/spivurno/3710935
=> Display Number of Entries Left Based on Entry Limit

gravity-forms/gw-minimum-order-qty.php
Original Gist: https://gist.githubusercontent.com/spivurno/3710681
=> Set a Minimum Order Quantity

gravity-forms/gw-unrequire-required-fields.php
Original Gist: https://gist.githubusercontent.com/spivurno/8748689
=> Unrequire Required Fields for Testing

gravity-forms/gw-skip-pages.php
Replaced spaces with tab per comment: https://github.com/gravitywiz/snippet-library/pull/312
=> ~ replaced space with tabs l8-10

gravity-forms/gw-live-preview.php
Original Gist: https://gist.githubusercontent.com/spivurno/8084779
=> Live Preview

gravity-forms/gw-gravity-forms-subtotal.php
Original Gist: https://gist.githubusercontent.com/spivurno/5409587
=> Subtotal Merge Tag

gravity-forms/gw-include-post-permalink.php
Original Gist: https://gist.github.com/spivurno/c87eab3aa56a5c6bded1/
=> Post Permalink Merge Tag

gravity-forms/gw-disable-html5-validation.php
Original Gist: https://gist.githubusercontent.com/spivurno/6963360
=> Disable HTML5 Validation on Gravity Forms

gravity-forms/gw-dynamic-post-excerpt.php
Original Gist: https://gist.githubusercontent.com/spivurno/b5c7af4635b781c5bdf9
=> Create Dynamic Post Excerpts with Gravity Forms

gravity-forms/gw-close-comments-on-post-creation.php
Original Gist: https://gist.githubusercontent.com/spivurno/3710956
=> Close Comments when Post Created via Gravity Forms

gravity-forms/gw-gravity-forms-filter-out-zero-dollar-products.php
Original Gist: https://gist.github.com/spivurno/7e067632f17554ca541e
=> Added snippet to the library

gp-preview-submission/gpps-live-refresh.php
Original Snippet: https://gist.github.com/spivurno/4bbfcd02ac99b89087f1e7b417ef1a5f
=> GPPS Live Refresh

gravity-forms/gw-save-and-continue-auto-load.php
Details in https://github.com/gravitywiz/gp-nested-forms/pull/188.
=> gw-save-and-continue-auto-load.php: Added support for repopulating child entries in Nested Form fields.

gp-address-autocomplete/gpaa-get-address-time-zone.php
Ticket: https://secure.helpscout.net/conversation/1936445286/36328?folderId=3775888
=> Get Address Time Zone

gravity-forms/gw-update-posts.php
https://secure.helpscout.net/conversation/1933348841/36220?folderId=3775888
=> Fixed an issue with Checkbox field mapping

gp-page-transitions/gppt-disable-hiding-footer.php
Hook Documentation: https://gravitywiz.com/documentation/gppt_hide_footer/#disable-hiding-the-footer
=> Disable Hiding the Form Footer

gp-multi-page-navigation/gpmpn-change-default-form-page.php
Hook Documentation: https://gravitywiz.com/documentation/gpmpn_default_page/#set-default-page-to-second-page
=> Change Default Form Page

gravity-forms/gw-create-coupon.php
https://secure.helpscout.net/conversation/1949115202/36695?folderId=3775888
=> Added Support to set WC Meta value with field value.

gp-word-count/gpwc-disable-truncation.php
Hook Documentation: https://gravitywiz.com/documentation/gpwc_script_args/#disable-truncation
=> Disable truncation

gp-word-count/gpwc-change-word-count-labels.php
Hook Documentation: https://gravitywiz.com/documentation/gpwc_script_args/#change-the-word-counts-labels-for-all-fields
=> Change the Word Count Labels

gp-easy-passthrough/gpep-remove-price-text-in-specific-target-field-value.php
Hook Documentation: https://gravitywiz.com/documentation/gpep_target_field_value/
=> Remove Price at the End of a Specific Target Field’s Value

gp-email-users/gpeu-increase-number-of-concurrent-connections.php
Hook Documentation: https://gravitywiz.com/documentation/gpeu_connection_threshold/#increase-the-number-of-concurrent-connections-to-10
=> Increase Number of Concurrent Connections to 10

gp-file-upload-pro/gpfup-set-total-max-file-size.js
Hook Documentation: https://gravitywiz.com/documentation/gpfup_before_upload/#total-max-file-size
=> Set Total Maximum File Size

gp-file-upload-pro/gpfup-scale-based-on-dimension.js
Hook Documentation: https://gravitywiz.com/documentation/gpfup_image_loader_options/#scale-instead-of-cropping-based-on-dimensions-set-in-the-cropping-settings
=> Scale Uploaded Images

gp-file-upload-pro/gpfup-set-jpeg-quality-for-uplodaed-images.js
Hook Documentation:  https://gravitywiz.com/documentation/gpfup_jpeg_quality/#increase-jpeg-quality-to-1-100-for-all-uploaded-images
=> Set JPEG Quality for all Uploaded Images

gp-file-upload-pro/gpfup-deregister-vue-as-a-dependency.php
Hook Documentation: https://gravitywiz.com/documentation/gpfup_scripts/#deregister-vue-as-a-dependency
=> Deregister Vue as a Dependency

gp-file-upload-pro/gpfup-customize-select-file-button-text.js
Hook Documentation:https://gravitywiz.com/documentation/gpfup_strings/#customize-the-8220-select-file-8221-button-text-for-a-specific-field
=> Customize the “select file” Button Text

gp-file-upload-pro/gpfup-include-image-medata-on-all-uploaded-images.js
Hook Documentation: https://gravitywiz.com/documentation/gpfup_strip_image_metadata/#include-image-metadata-exif-on-all-uploaded-images
=>  Include Image Metadata/EXIF on Uploaded images

gp-inventory/gpi-show-inventory-limit-in-form-editor.php
Hook Documentation: https://gravitywiz.com/documentation/gpi_always_show_inventory_limit_in_editor/#always-use-inventory-limit-in-form-editor
=> Show Inventory Limit in Form Editor

gp-inventory/gpi-set-inventory-limit-by-custom-field.php
Hook Documentation: https://gravitywiz.com/documentation/gpi_inventory_limit_advanced/#set-inventory-limit-by-custom-field
=> Set Inventory Limit by Custom Field

gp-inventory/gpi-add-support-for-field-type.php
Hook Documentation:
https://gravitywiz.com/documentation/gpi_supported_field_types/#add-number-as-a-supported-field-type
=> Add Number as a Supported Field Type

gp-limit-choices/gplc-share-limit-between-two-different-choices.php
Hook Documentation: https://gravitywiz.com/documentation/gplc_choice_counts/#examples
=> Share limit between two different choices on the same field

gp-limit-choices/gplc-override-limit-of-specific-choice.php
Hook Documentation: https://gravitywiz.com/documentation/gplc_choice_limit/#filter-a-specific-choice-8217-s-limit
=> Override Limit of Specific Choice

gp-limit-choices/gplc-customize-out-of-stock-validation-message.php
Hook Documentation: https://gravitywiz.com/documentation/gplc_out_of_stock_message/#examples
=> Customize Out of Stock Validation Message

gp-limit-dates/gpld-populate-new-maximum-date-into-linked-date-field.js
Hook Documentation: https://gravitywiz.com/documentation/gpld_after_set_max_date/#populate-the-new-maximum-date-into-the-field
=> Populate New Maximum Date into Linked Date Field

gp-limit-dates/gpld-automatically-show-linked-datepicker-for-linked-date-field.js
Hook Documentation: https://gravitywiz.com/documentation/gpld_after_set_max_date/#automatically-show-datepicker-for-linked-date-field
=>  Automatically Show Datepicker for Linked Date Field

gp-live-preview/gplp-enable-globally-for-admin.php
Hook Documentation: https://gravitywiz.com/documentation/gplp_enable_globally/#examples
=> Enable Globally For Admins

gp-limit-dates/gpld-automatically-show-datepicker-for-linked-date-field-min.js
Hook Documentation: https://gravitywiz.com/documentation/gpld_after_set_min_date/#automatically-show-datepicker-for-linked-date-field
=> Automatically Show Datepicker for Linked Date Field (Minimum Date)

gp-limit-dates/gpld-populate-new-minimum-date-into-linked-date-field.js
Hook Documentation: https://gravitywiz.com/documentation/gpld_after_set_min_date/#populate-the-new-minimum-date-into-the-field
=> Populate New Minimum Date into Linked Date Field

gp-limit-submissions/gpls-set-limit-period-by-user-meta.php
Hook Documentation: https://gravitywiz.com/documentation/gpls_before_query/#set-limit-period-by-user-meta
=> Set Limit Period by User Meta

gp-limit-submissions/gpls-change-submission-limit-reached-message-for-form.php
Hook Documentation: https://gravitywiz.com/documentation/gpls_limit_message/#change-the-8220-submission-limit-8221-reached-message-for-a-specific-form
=> Change the "submission limit" Reached Message for a Specific Form

gp-limit-submissions/gpls-only-allow-some-rule-types.php
Hook Documentation: https://gravitywiz.com/documentation/gpls_rule_type_choices/#only-allow-some-rule-types
=> Only Allow Some Rule Types

gp-media-library/gpml-set-custom-class-for-linked-image.php
Hook Documentation: https://gravitywiz.com/documentation/gpml_image_merge_tag_link_atts/#examples
=> Set a Custom Class For the Linked Image

gp-media-library/gpml-set-uploaded-images-data.php
Hook Documentation: https://gravitywiz.com/documentation/gpml_media_data/#examples
=> Set Uploaded Image Data

gp-media-library/gpml-add-support-for-custom-acf-field-type.php
Hook Documentation: https://gravitywiz.com/documentation/gpml_supported_acf_field_types/#add-support-for-a-custom-acf-field-type
=> Add Support For a Custom ACF Field Type

gp-auto-login/gpal-redirect-automatically-logged-in-users-to-a-custom-page.php
Hook Documentation: https://gravitywiz.com/documentation/gpal_auto_login_on_redirect_redirect_url/#examples
=> Redirect Automatically Logged-In Users to Custom Page

gp-blocklist/gpb-change-the-validation-message.php
Hook Documentation: https://gravitywiz.com/documentation/gpb_validation_message/#change-the-validation-message
=> Change the Validation Message

gp-better-user-activation/gpbua-change-activation-page-id-depending-on-language-with-polygon.php
Hook Documentation : https://gravitywiz.com/documentation/gpbua_activation_page_id/#change-activation-page-id-depending-on-language-with-polylang
=> Change Activation Page ID Depending on Language With Polylang

gp-date-time-calculator/gpdtc-change-max-delta.php
Hook Documentation: https://gravitywiz.com/documentation/gpdtc_warning_max_delta/
=> Change Max Delta

gp-media-library/gpml-upload-the-original-image-and-thumbnail.php
Hook Documentation: https://gravitywiz.com/documentation/gpml_image_sizes/#examples
=> Upload the Original Image and the Thumbnail

gp-media-library/gpml-return-all-available-image-sizes.php
Hook Documentation:  https://gravitywiz.com/documentation/gpml_merge_tag_image_sizes/#return-all-sizes
=> Return All Available Image Sizes

gp-media-library/gpml-add-a-custom-size.ph
Hook Documentation: https://gravitywiz.com/documentation/gpml_merge_tag_image_sizes/#add-a-custom-size
=> Add A Custom Size

gp-media-library/gpml-add-a-size-to-the-list.php
Hook Documentation: https://gravitywiz.com/documentation/gpml_merge_tag_image_sizes/#add-a-size-to-the-list
=> Add A Size to the List

gp-nested-forms/gpnf-unstick-the-modal-footer.php
Snippet URL: https://gravitywiz.com/documentation/gpnf_init_script_args/#unstick-the-modal-footer
=> Unstick the Modal Footer

gp-nested-forms/gpnf-change-template-for-gravityview-entry-list-view.php
Hook Documentation: https://gravitywiz.com/documentation/gpnf_template_args/
=> Change Template for GravityView Entry List View

gp-notification-scheduler/gpns-send-notification-on-the-last-day-of-every-month.php
Hook Documentation: https://gravitywiz.com/documentation/gpns_schedule_timestamp/#send-notification-on-the-last-day-of-every-month
=>  Send Notification on the last day of every month

gp-notification-scheduler/gpns-send-notification-at-the-beginning-of-next-work-week.php
Hook Documentation: https://gravitywiz.com/documentation/gpns_schedule_timestamp/#send-notification-at-the-beginning-of-the-next-work-week
=> Send Notification at the Beginning of the Next Work Week

gp-notification-scheduler/gpns-change-scope-unsubscribe-success-url.php
Hook Documentation: https://gravitywiz.com/documentation/gpns_unsubscribe_url_args/#change-scope-and-unsubscribe-success-url
=> Change Scope and Unsubscribe Success URL

gravity-forms/gw-user-registration-update-by-email.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/1959544702/37054?folderId=1530128
Provide more control over capabilities for Update by Email. Prior to this PR, it required a user to be logged in with no way to change the behavior.
This PR sets a new required capability of `edit_users` for anyone accessing these forms. This is more strict than the previous requirement of any logged-in user being able to edit.
=> gw-user-registration-update-by-email.php: Added new capability setting.

gp-ecommerce-fields/gpecf-tax-amounts-by-field-value.php
=> Added Instruction Video

gravity-forms/gw-uppercase-entry-value.php
Original Snippet: https://gist.github.com/spivurno/ef07003c5ca878f107a5ba0ac5152ed0#file-gw-gravity-forms-uppercase-entry-value-php
=>  Uppercase Entry Value (by Field)

gp-populate-anything/gppa-replace-live-merge-tags-individually-and-show-spinner.js
Hook Snippet Documentation: https://gravitywiz.com/documentation/gppa_loading_target_meta/#replace-live-merge-tags-individually-and-show-spinner
=> Replace Live Merge Tags and Show Spinner

gp-populate-anything/gppa-replace-field-with-spinner-instead-of-pulsing.js
Hook Documentation Snippet Link: https://gravitywiz.com/documentation/gppa_loading_field_target_meta/#replace-field-with-spinner-instead-of-pulsing
=> Replace Field with Spinner Instead of Pulsing

gp-inventory/gpi-waiting-list.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/1972333442/37514/
* Refactor to class
* Add support for waiting list on Single Products (previously only choice-based)
=> `gpi-waiting-list.php`: Refactor to class and add support for Single Products

gp-file-renamer/gpfr-global-filename-template.php, gp-file-renamer/gpfr-lowercase-all-filenames.php
📓 Notion: https://www.notion.so/gravitywiz/GPFR-1-0-Docs-First-Draft-e7c7f4c11b794039b30f1c49ad01e327
Adding the gpfr_filename example snippets for hook documentation.
=> Add `gpfr_filename` example snippets.

gravity-forms/gw-save-and-continue-auto-load.php
I forgot to bump the version number in a snippet :facepalm:
=> Bump version from 0.5 -> 0.6 in gw-save-and-continue-auto-load

gp-multi-page-navigation/gpmpn-modify-frontend-labels.php
📓 Notion: https://www.notion.so/gravitywiz/Gravity-Forms-Multi-Page-Navigation-54503fb5b4cb474db728010d96dfa0d7
Migrating [gp-multi-page-navigation-hooks-php](https://gist.github.com/spivurno/0ec65dcedf974524bf90#file-gp-multi-page-navigation-hooks-php).
=> Add gpmpn-modify-frontend-labels.php

gp-read-only/gpro-style-guide.css
📓 Notion: https://www.notion.so/gravitywiz/Convert-gist-usage-in-Articles-and-Docs-7fe7869d072347a290af78d85b901405
Migrating [gist](https://gist.github.com/spivurno/50e7cef13e7f254d132d) to Snippet Library.
=> Added `gpro-style-guide.css`.

gp-better-user-activation/gpbua-enable-editor.php
📓 Notion: https://www.notion.so/gravitywiz/Gravity-Forms-Better-User-Activation-faf55c5f428c4ee9ad6287aa19c838e8
Migrating gpbua-enable-editor.php from [gist](https://gist.github.com/spivurno/483ca0ace1be61df682552f5034ccdd1#file-gp-better-user-activation-enable-editor-php)
=> Added gpbua-enable-editor.php

gravity-forms/gw-populate-date-year-from-today.php
📓 Notion: https://www.notion.so/gravitywiz/Populate-Date-One-Year-from-Current-Date-a92e1559b4584da3a78bcedaea6b61f5
Migrating from [gist](https://gist.github.com/spivurno/3708480)
=> Added gw-populate-date-year-from-today.php

gravity-forms/gw-submission-limit.php
📓 Notion: https://www.notion.so/gravitywiz/Better-Limit-Submission-Per-Time-Period-by-User-or-IP-99664afddfff44d4a4a2472ff10afe97
Migrating from [gist](https://gist.github.com/spivurno/4024361)
=> Added gw-submission-limit.php

gravity-forms/gw-better-pre-submission-confirmation.php
📓 Notion: https://www.notion.so/gravitywiz/Better-Pre-submission-Confirmation-127b1cb91c1744f1b555db9607c09178
Migrating from [gist](https://gist.github.com/spivurno/3708630)
=> Added gw-better-pre-submission-confirmation.php

gp-nested-forms/gpnf-triggered-population.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2009533912/38684?folderId=3808239
Allow passing an array to `trigger_field_values` to add a child entry if the selected choice exists in the array of accepted trigger field values.
Example:
```
new GPNF_Triggered_Population( array(
'form_id'              => 123,
'trigger_field_id'     => 4,
'trigger_field_value'  => array(
'Second Choice',
'Third Choice',
),
'nested_form_field_id' => 5,
'field_map'            => array(
// source field ID => target field ID
'6.3' => '3.3',
'6.6' => '3.6',
'7'   => '4',
'8'   => '5',
),
) );
```
=> `gpnf-triggered-population.php`: Added support for passing an array of accepted values in `trigger_field_value`

gp-populate-anything/gppa-select-first-random-choice-on-radio.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2010508229/38708/#thread-5970679827
Functionality for Radio Button populated with GPPA and having 'Randomize Choice Order' (GP Randomizer) to have the first choice as the default selection.
=> Added snippet to Default Check First Radio Button having Randomized Choices

dangerfile.ts, gravity-forms/gw-limit-checkboxes.php
📓 Notion: https://www.notion.so/gravitywiz/Limiting-How-Many-Checkboxes-Can-Be-Checked-e7b0bdd3c3094ceeb2ae941b7f1228a1
Migrating [from gist](https://gist.github.com/spivurno/4005684#file-gistfile1-php).
=> `gw-limit-checkboxes.php`: Migrated from GitHub Gists.

dangerfile.ts
Adds `Refactored` to allowed prefix list in PRs
=> Tooling: Added `Refactored` to list of allowed pr title fixes.

gravity-forms/gw-quantity-as-decimal.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2028999838/39357?folderId=3808239
This adds decimal_comma capability to the snippet.
=> `gw-quantity-as-decimal.php`: Updated snippet to take into account the decimal comma format.

gravity-forms/gw-advanced-merge-tags.php
Ticket: https://secure.helpscout.net/conversation/2040438240/39764?folderId=3775888
Added the `:urlencode` and `:rawurlencode` modifiers.
=> `gw-advanced-merge-tags.php`: Added support for URL encoding.

gravity-forms/gw-split-testing.php
📓 Notion: https://www.notion.so/gravitywiz/Simple-Split-Testing-with-Gravity-Forms-8d66d79ee00043bfa229e38db6ae2e87
Migrated from [this Gist](https://gist.github.com/spivurno/8292521#file-gw-gravity-forms-split-testing-php).
=> `gw-split-testing.php`: Migrated from GitHub Gists.

gravity-forms/gw-set-post-status-by-product-field-value.php
📓 Notion: https://www.notion.so/gravitywiz/Set-Post-Status-by-Field-Value-Advanced-4e46fa7876bd4ffbb1ea5ba2611e99f9
Migrated from [Gist](https://gist.github.com/spivurno/3710757).
=> `gw-set-post-status-by-product-field-value.php`: Migrated from GitHub Gists.

gravity-forms/gw-currencies.json, gravity-forms/gw-currencies.php
📓 Notion: https://www.notion.so/gravitywiz/Gravity-Forms-Currencies-89c140b536104e609647ac40054833dc
Migrating from [Gist](https://gist.github.com/spivurno/ccb38f3c974887d9da26#file-gw-gravity-forms-currencies-php).
=> `gw-currencies.php`: Migrated from GitHub Gists.

gravity-forms/gw-day-count.php
📓 Notion: https://www.notion.so/gravitywiz/Calculate-Number-of-Days-Between-Two-Dates-7e814573b8254662a70ec790766077a8
Migrating from [this Gist](https://gist.github.com/spivurno/4996579#file-gw-gravity-forms-day-count-php).
=> `gw-day-count.php`: Migrated from GitHub Gists.

gravity-forms/gw-dyn-pop-unix-timestamp.php
📓 Notion: https://www.notion.so/gravitywiz/Use-Gravity-Forms-Conditional-Logic-with-Dates-e8ddf7d01a734e75ab745ae5ef4e10ab
Migrated from [this Gist](https://gist.github.com/spivurno/5065194).
I renamed the file and updated the snippet header title to more closely reflect what the snippet does.
=> `gw-dyn-pop-unix-timestamp.php`: Migrated from GitHub Gists.

gp-address-autocomplete/gpaa-show-place-name.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2083857798/41389?folderId=3808239
https://secure.helpscout.net/conversation/2092611916/41678?folderId=3808239
Snippet will only work with the branch on [this](https://github.com/gravitywiz/gp-address-autocomplete/pull/36) gp-address-autocomplete PR.
Tap and display the business/establishment name.
=> `gpaa-show-place-name.php`: Added snippet to show Establishment Place Name.

gp-limit-dates/gpld-last-day-of-the-month-only.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2090349115/41601?folderId=3808239
This snippet only displays the last day of each month for the GPLD.
=> `gpld-last-day-of-the-month-only.php`: Added snippet to display last day of the month only for GPLD.

experimental/gpaa-plus-code.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2087975161/41523 
This snippet was written for a customer and might be useful to others as well.
=> `gpaa-plus-code`: Added experimental script.

experimental/gpaa-street-view.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2089199279/41562/
This snipppet was written for a customer and may be useful to others as well.
=> `gpaa-street-view`: Added experimental snippet.

gp-ecommerce-fields/gpecf-deduct-deposit.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2120042248/42549?folderId=7098280
Fixed Gravity Forms class name.
=> `gpecf-deduct-deposit.php`: Fixed Gravity Forms instance check.

gravity-forms/gw-validate-that-a-value-exists.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2120196167/42557?folderId=7098280
New filter `gwvev_get_entries_args`
=> `gw-validate-that-a-value-exists.php`: Added filter to modify matching entry criteria.

gp-address-autocomplete/gpaa-map-satellite-view.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2146440913/43814?folderId=6987275 
Adds a javascript snippet to default all maps to the "satellite" type map view.
=> `gpaa-map-satellite-view.js`: Added new snippet to default map view to the "satellite" type.

gp-advanced-save-and-continue/vgx-salesforce-compatibility.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2142013154/43605?folderId=6987275 
💬 Slack: https://gravitywiz.slack.com/archives/CRGJU47T3/p1676391656253689 
See [the Slack thread](https://gravitywiz.slack.com/archives/CRGJU47T3/p1676391656253689) for more details.
=> `vgx-salesforce-compatibility.php`: Added snippet to make GPFR compatible with the VGX Salesforce plugin.

gp-advanced-save-and-continue/gpasc-gf-salesforce-compatibility.php
Dave pointed out that the naming here was a little confusing so this aims to fix that!
=> `gpasc-gf-salesforce-compatibility.php`: Refactored file for better clarity and added link to 3rd party script.

gravity-forms/gw-manual-entries.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2151850985/44078/
User was looking for a way to add new entries from Entry Blocks. Used this plugin as a base. Added a new filter and converted to a singleton to make this more accessible to external modifications.
Resulting snippet: https://github.com/gravitywiz/snippet-library/blob/master/gp-entry-blocks/gpeb-add-new-entry.php
=> Added `gfme_is_add_entry_request` filter and converted class to a singleton.

experimental/gpep-duplicate-child-entries.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2212148379/46703?folderId=1530128
=> `gpep-duplicate-child-entries.php`: Added new experimental snippet.

gp-populate-anything/gppa-aggregate-functions.php, gp-populate-anything/gppa-populate-all-results-as-list.php, gp-populate-anything/gppa-populate-all-results.php, gp-populate-anything/gppa-populate-unique-results-count.php
A batch of updates bringing snippets that relied on having access to all objects that matched the filters instead of the first matching result.
=> Updated snippets for compatiblity with GPPA 2.0.

gravity-forms/gw-field-to-field-conditional-logic.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2268303929/49864?folderId=3808239
Fixed PHP 8 warnings with the snippet.
=> `gw-field-to-field-conditional-logic.php`: Fixed PHP 8 warnings.

wc-gf-product-addons/wcgfpa-remove-fields.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2279400746/50706?folderId=3808239
Fixed the issue with the snippet processing the field setting for all fields together.
=> `wcgfpa-remove-fields.php`: Fixed an issue with the snippet processing all field settings together.

gravity-forms/gw-update-posts.php
Updated the author name on this snippet.
=> `gw-update-posts.php`: Updated author name.

gp-date-time-calculator/gpdtc-format-hours-mins.php, gp-limit-choices/gplc-field-groups.php, gp-multi-page-navigation/gpmpn-page-permalinks.php, gp-populate-anything/gppa-populate-child-entries.php, gp-preview-submission/gpps-live-refresh.php, gravity-forms/gw-dynamic-range.php, gravity-forms/gw-feed-specific-submit-button.php, gravity-forms/gw-field-to-field-conditional-logic.php, gravity-forms/gw-gravity-forms-rounding.php, gravity-forms/gw-manual-entries.php, gravity-forms/gw-populate-date.php, gravity-forms/gw-prevent-duplicate-selections.php, gravity-forms/gw-set-list-field-rows-by-field-value.php, gravity-forms/gw-time-sensitive-choices.php, gravity-forms/gw-validate-that-a-value-exists.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2447901846/58752?folderId=14960
Some of our snippets include version numbers. I neglected to update these as part of my bulk update for GF 2.8 compat here: https://github.com/gravitywiz/snippet-library/pull/737/
=> Updated versions for all snippets that had listed versions and were updated for GF 2.8 compatibility.

gp-google-sheets/gpgs-process-feed-on-partial-entry-save.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2416316042/57116?folderId=3808239
Send partial entries to Google Sheets via GPGS.
**Form setup and current behaviour with Partial Entries & GPGS:**
https://www.loom.com/share/4fb6d380af41403ba42982876a4d51db
**After applying the snippet to trigger Partial Entries to GPGS:**
https://www.loom.com/share/a1634cc65a454549b1e768ea26fffbc8
=> `gpgs-process-feed-on-partial-entry-save.php`: Added a snippet to trigger Google Sheets Feeds for Partial Entries.

gravity-forms/gw-cache-buster.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2505977055/61172?folderId=7098280
When using the Cache Buster, the `{embed_url}` merge tag returns a gfcb URL instead of the standard URL.
**Steps to Reproduce**
1. Add `{embed_url}` to your form notification or confirmation.
2. Embed the form on your site using Cache Buster.
3. Submit an entry.
4. Check notification, URL is different than normal. Example: `https://yoursite.local/wp-admin/admin-ajax.php?action=gfcb_get_form&form_id=1302`
To fix the issue we add the `gform_pre_replace_merge_tags` to check for `{embed_url}` merge tag and ensure the original link continues to be sent forth, and not the gfcb cache builder link.
=> `gw-cache-buster.php`: Improved support for `{embed_url}` and updating the `source_url` property on the entry during submission.

gp-populate-anything/gppa-acf-repeater-mapper.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2535376039/63084
Add support for `WP_Term` object.
=> `gppa-acf-repeater-mapper.php`: Added support for `WP_Term` object.

gp-entry-blocks/gpeb-disable-conditional-logic.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2552427358/63973/
Snippet that removes conditional logic from all fields when editing an entry via Entry Blocks.
=> `gpeb-disable-conditional-logic.php`: Added snippet to disable Field Conditional Logic when editing using Entry Blocks.

gravity-forms/gw-all-checkboxes-checked.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2549746277/63832?folderId=7098280#
This snippet populates a Hidden field with the value of 1 if every checkbox in a given field is checked and a 0 if every checkbox in that field is not checked.
Screencast:
https://www.loom.com/share/5c55fe7fa415428aa48b249d6ead071f
=> `gw-all-checkboxes-checked.js`: Added snippet to trigger conditional logic evaluation when all checkboxes are checked.

gravity-forms/gw-create-coupon.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2555639705/64138?folderId=8181748
=> `gw-create-coupon.php`: Added the ability to create coupons only when certain fields are not empty.

gp-advanced-select/gpadvs-enable-globally.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2560781858/64368?folderId=7098280
Functionality to apply Advanced Select on all forms and all fields, can be customizable only to a specific form or apply to all forms.
=> `gpadvs-enable-globally.php`: Added functionality to enable GP Advanced Select Globally.

gp-advanced-select/gpadvs-auto-select-on-match.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2546318031/63648?folderId=8181748
The newly-added snippet automatically selects the (single) matching option as the user types to filter the options in an enhanced select field.
=> `gpadvs-auto-select-on-match.js`: Added new snippet for GP Advanced Select.

gp-nested-forms/gpnf-gravitypdf-auto-attach-child-pdfs.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2576657078/65227
=> `gpnf-gravitypdf-auto-attach-child-pdfs.php`: Added a snippet for attaching child entry PDFs generated by GravityPDF to parent entry notifications.

gp-advanced-select/gpadvs-enable-add-new-option.php
⛑️ https://secure.helpscout.net/conversation/2571319811/64967
=> `gpadvs-enable-add-new-option.php`: Added functionality to create new terms on form submission.

gravity-forms/gw-update-posts.php
⛑️ https://secure.helpscout.net/conversation/2568090323/64768
=> `gw-update-posts.php`: Fixed ACF field Bidirectional update.

gp-entry-blocks/gpeb-entry-edit-timestamp.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2582701663/65507?folderId=7098280
Display the entry edit timestamp:
https://www.loom.com/share/af4e456263324971b3463ff344c77830
=> `gpeb-entry-edit-timestamp.php`: Added snippet to display edit entry timestamp.

gp-address-autocomplete/gpaa-generate-static-map.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2615434629/67102
Added static map generation for created entries. Map is added to `gpaa_map_{FIELDID}` entry meta.
Snippet in action:
https://www.loom.com/share/3f849ad53c0745e082caf55adaedbe9d
=> `gpaa-generate-static-map.php`: Added a snippet for generating Static Maps with entries.

gp-advanced-select/gpadvs-enable-add-new-option.php
Fixed typos in the snippet description.
=> `gpadvs-enable-add-new-option.php`: Fixed typos in description.

gravity-forms/gw-cache-buster.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2629263002/67735?folderId=8114575
{embed_post} merge tags are not working when Cache Buster is active on a form. The issue here is that the `global $post` is not available in Ajax context. This PR should fix the issue.
=> `gw-cache-buster.php`: Fixed an issue where field default value that contains `{embed_post}` merge tags  is not replaced.

gravity-forms/gw-select-all-multi-select.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2637029038/68103
The snippet above doesn't work when the results of multi select field is dynamically filtered based on a field value.
Loom of the issue (Credits: Samuel)
https://www.loom.com/share/3b402f06f9ff4e02b55ee0b8c5f1a0f2?sid=51bb0ba0-5b42-4c38-84f1-7deaf8c4db31
=> `gw-select-all-multi-select.js`: Added support for dynamically populated Multi Select Fields.

gp-nested-forms/gpnf-post-specific-sessions.php, gp-nested-forms/gpnf-user-specific-sessions.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2642090145/68311
Added a new Snippet for scoping  `GPNF` session by currently logged in user.
=> `gpnf-user-specific-sessions.php`: Added a new Snippet for scoping session by currently logged in user.

gp-address-autocomplete/gpaa-capture-neighborhood-separately.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2642548768/68339
Added a new `GPAA` Snippet for capturing neighborhoods separately.
=> `gpaa-capture-neighborhood-separately.js`: Added a new Snippet for capturing neighborhood separately.

gp-multi-page-navigation/gpmpn-dropdown-navigation.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2660745826/69190?folderId=7098280
Created a snippet that creates a drop down based on the current pages. Pages with actual page links from GPMPN will be enabled. Pages without page links will be disabled. Select a page will trigger a click on the corresponding page link, navigating the form to that page.
**Demo:**
https://www.loom.com/share/38fcc941036842d6a81a599fd8de39d7
=> `gpmpn-dropdown-navigation.js`: Added snippet for displaying multi page navigation as a dropdown.

gp-copy-cat/gpcc-conditional-copy.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2637685533/68121
Copying with condition feature of Copy cat to copy values from one field to another based on if another field contains a value, with extended check to see if the value in the condition field is a specific value.
(version 1):
https://www.loom.com/share/f8db53c9359c45d8bc160d6e1d8eb4fc
**(version 2):**
https://www.loom.com/share/0b02559975444a139519b6830c7fc6d8
=> `gpcc-conditional-copy.js`: Added snippet for conditional copy based on trigger field value.

gc-google-sheets/gcgs-hide-settings-tab.php, gc-google-sheets/gcgs-process-feed-on-partial-entry-save.php, gc-google-sheets/gcgs-send-number-as-string.php
Just something that needed to be done as part of the GPGS to GCGS conversion.
=> Added (converted) GPGS snippets to GCGS.

gp-file-upload-pro/gpfup-customize-select-file-button-text.js
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2638580355/68176
Change all the text displayed on File Upload Pro for clarity.
**Default:**
**After customization:**
=> `gpfup-customize-select-file-button-text.js`: Added customization for Drop Files Here and Or texts.

gravity-forms/gw-disable-submit-button-until-required-fields-are-filled-out.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2687203302/70371
Fixed typo where "Field Out" should be "Filled Out".
=> `gw-disable-submit-button-until-required-fields-are-filled-out.php`: Fixed typo in description.

gp-entry-blocks/gpeb-gfapc-update-post.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2713025278/71677
Added a new snippet to update posts when using the `GFAPC` addon.
=> `gpeb-gfapc-update-post.php`: Added a new snippet to update post with using `GFAPC` addon.

gravity-forms/gfcs-auto-chained-select.php
https://www.notion.so/gravitywiz/Gravity-Wiz-Gravity-Forms-Chained-Selects-Auto-Select-Only-Option-15200ab68edf80fc87b1d03d58823c4a?pvs=4
=> `gfcs-auto-chained-select.php`: Migrating from `experimental` folder.

gp-unique-id/gpuid-shared-sequences.php
Updated to take advantage of the upcoming `slug` attribute. 
https://github.com/gravitywiz/gp-unique-id/pull/27
Do not merge until https://github.com/gravitywiz/gp-unique-id/pull/27 is merged and published.
=> `gpuid-shared-sequences.php`: Updated to use the new `slug` attribute.

gp-populate-anything/gppa-acf-datepicker-comparison.php
The URL to the new version in the comment is incorrect. I updated it to the correct version.
The URL to the new version in the comment is incorrect. I updated it to the correct version.
=> `gppa-acf-datepicker-comparison.php`: Fixed New Version URL.

gravity-forms/gw-manual-notifications.php
https://www.notion.so/gravitywiz/Loom-Update-Send-Manual-Notifications-13f00ab68edf809f89bfca9237a77a7f?pvs=4
Updated the instruction video in the snippet header.
=> `gw-manual-notifications.php`: Fixed instruction video in snippet header.

gravity-forms/gw-format-date-merge-tags.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2763010990/73925
Limit snippet by `form_id` settings.
=> `gw-format-date-merge-tags.php`: Added snippet to be limited by `form_id` settings.

gravity-forms/gw-none-of-the-above-checkbox.js
Updated instruction video in snippet header with new Loom recorded by @matty0501
=> `gw-none-of-the-above-checkbox.js`: Updated instruction video in snippet header.

gp-nested-forms/gpnf-limit-entry-min-max-from-field.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2859609766/78584
📓 Ticket Thread Reference: https://secure.helpscout.net/conversation/2859609766/78584#thread-8676640964
Added configuration for this snippet.
=> `gpnf-limit-entry-min-max-from-field.php`: Added snippet usage.

gc-google-sheets/gcgs-gppa-custom-query-builder-args.php
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2850980281/78195
Snippet to add the `is in` functionality to a query coming via Google Sheets for GPPA dynamic population
Related to this https://github.com/gravitywiz/gc-google-sheets/pull/164"
This closes https://github.com/gravitywiz/snippet-library/pull/1037
=> `gcgs-gppa-query-builder-args.php`: Added snippet to customize query builder arguments.

gp-auto-list-field/gpalf-count-only-non-blank-rows.js
💬 Slack: https://gravitywiz.slack.com/archives/C03T0CNL8AV/p1746018940328489
Fixed the snippet title.
=> `gpalf-count-only-non-blank-rows.js`: Fixed snippet title.

gs-product-configurator/gspc-update-post-status-on-wc-order-status-change.php
💬 Slack: https://gravitywiz.slack.com/archives/C03T0CNL8AV/p1747057349417209
Fix the header! 👀
=> `gspc-update-post-status-on-wc-order-status-change.php`: Fixed snippet header.

gp-nested-forms/gpnf-sort-child-entries-by-field-value.php, gp-nested-forms/gpnf-sort-nested-form-entries.js
Re: https://github.com/gravitywiz/snippet-library/pull/1068#pullrequestreview-2881483409
We added this: https://github.com/gravitywiz/snippet-library/pull/1068
So we are deprecating the others
=> `gpnf-sort-nested-form-entries.js`: Added deprecation notice to the snippets.

gravity-forms/gw-rich-text-html-fields.php
Fixed issue where editor tabs were not consistently clickable.
Fixed issue where plugin was unnecessarily dependent on Gravity Perks.
⛑️ Ticket(s): https://secure.helpscout.net/conversation/2987432785/86002
Closes #1082.
=> Fixed issue where editor tabs were not consistently clickable.
